CREATE FULLTEXT INDEX ON [dbo].[SM_SERVICECALL_SEARCH]
    ([SCBODY] TYPE COLUMN [DT] LANGUAGE 1033)
    KEY INDEX [PK_SM_SERVICECALL_SEARCH]
    ON [FullTextCatalog];


GO
CREATE FULLTEXT INDEX ON [dbo].[IT_TASKS_SEARCH]
    ([BODY] TYPE COLUMN [DT] LANGUAGE 1033)
    KEY INDEX [PK_IT_TASKS_SEARCH]
    ON [FullTextCatalog];

