CREATE ROLE [A2Users]
    AUTHORIZATION [db_owner];


GO
ALTER ROLE [A2Users] ADD MEMBER [IPG-DOMAIN\gvartanov];


GO
ALTER ROLE [A2Users] ADD MEMBER [EMEA\GMSA-AzureDO$];


GO
ALTER ROLE [A2Users] ADD MEMBER [EMEA\DEDMS];

