


CREATE VIEW [power_bi].[POWERBI_SERVICEORDERITEMS]
AS

SELECT  
	POI.[ORDERID] [Service Order ID],
	POI.[FRID] [Failure Report],
	CAST(POI.[INC_DATE] AS DATE) [Incoming Date],
	ISNULL(MD.[NAME], '') [Model],
	ISNULL(MD.[CODE], '') [Navision Code (PN)],
	ISNULL(DEV.[SN], '') [SN]

FROM [dbo].[PR_PRORDER_SERVICE] POI WITH(NOLOCK)
INNER JOIN [dbo].[PR_PRORDER] PO WITH(NOLOCK)
	ON PO.[ID] = POI.[ORDERID] AND PO.[ORDERTYPE] = 1 AND PO.[NN] LIKE 'RMA-__-____'
INNER JOIN [dbo].[FC_REPORT] FR WITH(NOLOCK) 
	ON FR.[ID] = POI.[FRID] AND ISNULL(POI.[FRID], '') <> '' AND FR.[INT_EXT] = 2
LEFT JOIN [dbo].[PR_DEVICE] DEV WITH(NOLOCK)
	ON DEV.[ID] = POI.[DEVICEID]
LEFT JOIN [dbo].[PR_MODELS] MD WITH(NOLOCK)
	ON MD.[ID] = DEV.[MODELID]
GO
GRANT SELECT
    ON OBJECT::[power_bi].[POWERBI_SERVICEORDERITEMS] TO [EMEA\ltishina]
    AS [dbo];

