
CREATE VIEW [power_bi].[POWERBI_SERVICEORDER]
AS

/*KB5414*/

SELECT 
	PO.[ID] [Service Order ID],
	CAST(PO.[CDD] AS DATE) [Confirmed Date],
	CUST.[NAME] [Customer],
	DEP.[CODE] [Department],
	CAST(PO.[DD] AS DATE) [Order Date],
	PO.[NN] [Order Number],
	CAST(PO.[EXPDATE] AS DATE) [Planned Date],
	ISNULL((SELECT TOP 1 SC.ND FROM [dbo].[SM_SERVICECASE] SC WHERE SC.SERVORDID = PO.[ID] ORDER BY SC.ID ASC), '') [Service Case],
	CASE PO.[S_S] 
		WHEN 1 THEN 'Created'
		WHEN 1000035 THEN 'In Process'
		WHEN 1000036 THEN 'Completed'
		WHEN 1000037 THEN 'Shipped'
		WHEN 1000143 THEN 'Approved'
		WHEN 1000144 THEN 'Approving expected'
		ELSE CAST(PO.[S_S] AS VARCHAR(10)) 
	END	[State],
	CASE WHEN PO.[URGENCY] IS NULL THEN '' ELSE CASE PO.[URGENCY] 
		WHEN 0 THEN 'Low'
		WHEN 1 THEN 'Default'
		WHEN 2 THEN 'High'
		WHEN 3 THEN 'Very High'
		WHEN 10 THEN 'Exceptional'
		ELSE CAST(PO.[URGENCY] AS VARCHAR(10)) 
	END END [Urgency]
  FROM [dbo].[PR_PRORDER] PO WITH(NOLOCK)
  LEFT JOIN [dbo].[COM_CUSTOMER] CUST WITH(NOLOCK) ON CUST.[ID] = ISNULL(PO.[CUSTOMERID], 0)
  LEFT JOIN [dbo].[COM_DEPARTMENTS] DEP WITH(NOLOCK) ON DEP.[ID] = ISNULL(PO.[DEPARTMENTID], 0)
  WHERE PO.[ORDERTYPE] = 1 AND PO.[NN] LIKE 'RMA-__-____'
	  AND EXISTS(SELECT 1 FROM [dbo].[PR_PRORDER_SERVICE] POI WITH(NOLOCK)
				 INNER JOIN [dbo].[FC_REPORT] FR WITH(NOLOCK)
					ON FR.[ID] = POI.[FRID] AND ISNULL(POI.[FRID], 0) <> 0 AND FR.[INT_EXT] = 2 AND POI.[ORDERID] = PO.[ID])
GO
GRANT SELECT
    ON OBJECT::[power_bi].[POWERBI_SERVICEORDER] TO [EMEA\ltishina]
    AS [dbo];

