


CREATE VIEW [power_bi].[POWERBI_ITEMWAITINGCOSTAPPROVAL]
AS

SELECT 
	ISNULL(MD.[NAME], '') [Model],
	ISNULL(MD.[CODE], '') [Navision Code (PN)], 
	DEV.[SN],
	DL.DD [From DateTime],
	ISNULL(
		(SELECT TOP 1 DL2.DD FROM [dbo].[DEF_LOG] DL2 WITH(NOLOCK) 
		 WHERE DL2.DOCOID = DL.DOCOID AND DL2.DOCID = DL.DOCID AND DL2.EV_TYPE = 20002 AND DL2.CAPTION LIKE '%(2130133)%' AND DL2.DD >= DL.DD 
		 ORDER BY DL2.DD ASC), 
		GETDATE()) [To DateTime]
FROM [dbo].[DEF_LOG] DL WITH(NOLOCK)
INNER JOIN [dbo].[PR_DEVICE] DEV WITH(NOLOCK) ON DEV.ID = DL.DOCID
INNER JOIN [dbo].[PR_MODELS] MD WITH(NOLOCK) ON MD.[ID] = DEV.[MODELID]
WHERE DL.DOCOID = 1000036	-- pr_device
AND DL.EV_TYPE = 20002		-- change state
AND (DL.CAPTION LIKE '%(2130130)%' OR DL.CAPTION LIKE '%(2130131)%' OR DL.CAPTION LIKE '%(2130132)%')	-- pr_setwaitcost
GO
GRANT SELECT
    ON OBJECT::[power_bi].[POWERBI_ITEMWAITINGCOSTAPPROVAL] TO [EMEA\ltishina]
    AS [dbo];

