-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [dbo].[COM_EMPLOYEE_SKILL_EXPIRED_DATES_BY_DATE]
( @depId int, @dateActual datetime)
RETURNS TABLE 
AS
RETURN 
(
    select E.EMPLOYEEID, U.ID as USERID, E.SKILLID, 
         case 
				when E.NOT_EXPIRING=1 then null
                when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=1 then DATEADD(day, S.EXPIRATION_TERM, ISNULL(P.PROLONG_DATE, E.SKILL_DATE))
                when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=2 then DATEADD(week, S.EXPIRATION_TERM, ISNULL(P.PROLONG_DATE, E.SKILL_DATE))
                when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=3 then DATEADD(month, S.EXPIRATION_TERM,ISNULL(P.PROLONG_DATE, E.SKILL_DATE))
                when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=4 then DATEADD(year, S.EXPIRATION_TERM, ISNULL(P.PROLONG_DATE, E.SKILL_DATE))
                when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=1 then DATEADD(day, S.EXPIRATION_TERM, ISNULL(L.LAST_DATE,E.SKILL_DATE))
                when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=2 then DATEADD(week, S.EXPIRATION_TERM, ISNULL(L.LAST_DATE,E.SKILL_DATE))
                when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=3 then DATEADD(month, S.EXPIRATION_TERM, ISNULL(L.LAST_DATE,E.SKILL_DATE))
                when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=4 then DATEADD(year, S.EXPIRATION_TERM, ISNULL(L.LAST_DATE,E.SKILL_DATE))
                else null END as EXPIRED_DATE,
            case 
					when E.NOT_EXPIRING=1 then 0
                    when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=1 and DATEADD(day, S.EXPIRATION_TERM,ISNULL(P.PROLONG_DATE, E.SKILL_DATE))<=@dateActual then 1
                    when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=2 and DATEADD(week, S.EXPIRATION_TERM, ISNULL(P.PROLONG_DATE, E.SKILL_DATE))<=@dateActual then 1
                    when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=3 and DATEADD(month, S.EXPIRATION_TERM, ISNULL(P.PROLONG_DATE, E.SKILL_DATE))<=@dateActual then 1
                    when S.PRODUCTION_SUPPORT=1 AND S.EXPIRATION_TERM_TYPE_ID=4 and DATEADD(year, S.EXPIRATION_TERM, ISNULL(P.PROLONG_DATE, E.SKILL_DATE))<=@dateActual then 1
                    when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=1 and DATEADD(day, S.EXPIRATION_TERM, ISNULL(L.LAST_DATE,E.SKILL_DATE))<=@dateActual then 1
                    when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=2 and DATEADD(week, S.EXPIRATION_TERM, ISNULL(L.LAST_DATE,E.SKILL_DATE))<=@dateActual then 1
                    when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=3 and DATEADD(month, S.EXPIRATION_TERM , ISNULL(L.LAST_DATE,E.SKILL_DATE))<=@dateActual then 1
                    when S.PRODUCTION_SUPPORT=0 AND S.EXPIRATION_TERM_TYPE_ID=4 and DATEADD(year, S.EXPIRATION_TERM, ISNULL(L.LAST_DATE,E.SKILL_DATE))<=@dateActual then 1
                    else 0 END as EXPIRED
        from COM_EMPLOYEE_SKILL E  with (nolock)
             join COM_SKILLS S with (nolock) on E.SKILLID=S.ID
            left join dbo.COM_EMPLOYEE_SKILL_LAST_DATES_BY_DATE(@depId, @dateActual) L on E.SKILLID=L.SKILLID and E.EMPLOYEEID=L.EMPLOYEEID
            join COM_EMPLOYEE EMP on E.EMPLOYEEID=EMP.ID
             join DEF_USERS U on EMP.ID=U.EMPLOYEEID
            left join COM_EMPLOYEE_SKILL_PROLONGATION_DATES P on E.EMPLOYEEID=P.EMPLOYEEID and E.SKILLID=P.SKILLID
        where EMP.S_S<>1000092 
)