CREATE FUNCTION [dbo].[COM_USER_PERSONALNO](@USER_ID INT)
RETURNS nvarchar(20)
AS
BEGIN
       DECLARE @RESULT nvarchar(20)

       
       SELECT @RESULT = EMP.PERSONALNO
       FROM DEF_USERS USR
       JOIN COM_EMPLOYEE EMP ON USR.EMPLOYEEID = EMP.ID
       WHERE USR.ID = @USER_ID

       
       RETURN @RESULT
END