-- =============================================
-- Author:		 Anton Gramatkin
-- Create date: 01.07.2014
-- Description:	Returns operator idle time after operation
-- =============================================
CREATE FUNCTION [dbo].[COM_GET_USER_IDLE_TIME_BY_OPERATION]
(
	@EMPLOYEE_ID INT
	,@OPER_TIME_ID INT
	,@DATE DATETIME
)
RETURNS INT
AS
BEGIN
	DECLARE @START_DATE DATETIME
			,@END_DATE DATETIME
			,@WKT_ID INT
			,@TODAY DATETIME = GETDATE()
			,@DATE2 DATETIME

	SELECT
		@START_DATE = DBEG
		,@END_DATE = DEND
	FROM PR_OPERATION_TIME with (nolock)
	WHERE
		ID = @OPER_TIME_ID

	SET @DATE2 = DATEADD(DAY, 1, @DATE)

	SELECT
		@WKT_ID = COALESCE(EMP.PERSONALWT, WKT.ID)
	FROM COM_EMPLOYEE EMP with (nolock)
		LEFT JOIN COM_WORKTIME WKT with (nolock) ON EMP.DEPID = WKT.DEPID AND WTDEFAULT = 1
	WHERE
		EMP.ID = @EMPLOYEE_ID

	IF @WKT_ID IS NULL -- IF THERE IS NO DEFINED WORKTIME FOR THE EMPLOYEE
		RETURN NULL	  


declare @wturn int
select @wturn = A.WTURN from COM_TURNS A with (nolock) where A.EMPLID = @EMPLOYEE_ID and A.DD = cast(@DATE as date)
set @wturn = ISNULL(@wturn,1)


	-- Declare the return variable here
	DECLARE @RESULT INT = NULL

	IF EXISTS(	SELECT 
					NULL 
				FROM PR_OPERATION_TIME with (nolock)
				WHERE
					EMPID = @EMPLOYEE_ID
				AND (
					(DBEG < @END_DATE
				AND
					ISNULL(DEND, @TODAY) > @END_DATE)  -- IF THERE IS AN OPERATION WHICH WAS STARTED LATER (BUT NOT LATER THEN CURRENT WAS FINISHED) AND WAS FINISHED LATER THEN CURRENT

				OR 
					(DBEG< @START_DATE AND ISNULL(DEND, @TODAY) > @END_DATE) -- IF THERE IS AN OPERATION WHICH WAS STARTED EARLIER AND WAS FINISHED LATER THEN CURRENT
					)
			)

		SET @RESULT = 0

	ELSE
	WITH CTE_MIN_ID AS (
		SELECT
			ISNULL(MIN(ID),-1) AS ID
		FROM PR_OPERATION_TIME with (nolock)
		WHERE
			(DBEG >= @END_DATE AND DBEG < @DATE2/*DATEADD(DAY, 1, @DATE)*/)
		AND
			EMPID = @EMPLOYEE_ID

		UNION
		
		SELECT	-1	
		)

		,CTE_END_DAY AS
				(
					SELECT 
						COALESCE(CAST(CAST(WKT_BR_PERS.TTO AS FLOAT) - FLOOR(CAST(WKT_BR_PERS.TTO AS FLOAT)) + FLOOR(CAST(@DATE AS FLOAT)) AS DATETIME)
								,CAST(CAST(WKT_BR.TTO AS FLOAT) - FLOOR(CAST(WKT_BR.TTO AS FLOAT)) + FLOOR(CAST(@DATE AS FLOAT)) AS DATETIME)
						) AS END_DATE
					FROM COM_EMPLOYEE EMP with (nolock)
						LEFT JOIN [dbo].[COM_WORKTIME] WKT with (nolock) ON EMP.DEPID = WKT.DEPID AND WKT.WTDEFAULT = 1
							LEFT JOIN COM_WORKTIME_BR WKT_BR with (nolock) ON WKT_BR.VNESHID = WKT.ID and WKT_BR.WTURN = @wturn

						LEFT JOIN [dbo].[COM_WORKTIME] WKT_PERS with (nolock) ON EMP.PERSONALWT = WKT_PERS.ID
							LEFT JOIN COM_WORKTIME_BR WKT_BR_PERS with (nolock) ON WKT_BR_PERS.VNESHID = WKT_PERS.ID and WKT_BR_PERS.WTURN = @wturn
					WHERE
						EMP.ID =@EMPLOYEE_ID

					UNION

					SELECT
						DEND
					FROM COM_ADDED_WORKTIME ADD_WKT with (nolock)
					JOIN COM_EMPLOYEE EMP with (nolock) ON EMP.ID = ADD_WKT.EMPLID
					WHERE
						EMP.ID = @EMPLOYEE_ID
					AND 
						(ADD_WKT.DBEG >= @DATE AND ADD_WKT.DBEG < @DATE2/*DATEADD(DAY, 1, @DATE)*/)
			
				)

		SELECT
			@RESULT = 
			CASE
					WHEN @END_DATE < @DATE2/*DATEADD(DAY, 1, @DATE)*/ THEN
						CASE	
							WHEN CTE_MIN_ID.ID != -1 THEN
								 [dbo].[COM_WORK_MINUTS](	@END_DATE 
																	,OP_TIME.DBEG
																	,@WKT_ID 
																	,1
																	, @EMPLOYEE_ID)
							ELSE 
								[dbo].[COM_WORK_MINUTS](	@END_DATE 
																	,(SELECT MAX(END_DATE) FROM CTE_END_DAY)
																	,@WKT_ID 
																	,1
																	, @EMPLOYEE_ID)
						END
					ELSE
						0
			END
		FROM (
				SELECT 
					MAX(ID) AS ID
				FROM 
					CTE_MIN_ID) CTE_MIN_ID
		LEFT JOIN PR_OPERATION_TIME OP_TIME with (nolock) ON CTE_MIN_ID.ID = OP_TIME.ID 
	-- Return the result of the function
	RETURN @RESULT
END