CREATE FUNCTION [dbo].[PR_GET_USER_IDLE_TIME_BEFORE_OPERATION]
(
	--DECLARE 
	@OPER_TIME_ID INT --= 627843
	,@START_DATE DATETIME --= '2014-06-11 08:30:25.103'
	,@END_DATE DATETIME --= '2014-06-11 08:53:49.400'
	,@EMPLOYEE_ID INT --= 6
	,@DATE DATETIME --= '2014-06-11'
)
RETURNS INT
AS
BEGIN
	DECLARE
			@WKT_ID INT
			,@DAY_START DATETIME

	SELECT
		@WKT_ID = 
			COALESCE(EMP.PERSONALWT, WKT.ID)
	FROM COM_EMPLOYEE EMP with (nolock)
		LEFT JOIN COM_WORKTIME WKT with (nolock) ON EMP.DEPID = WKT.DEPID AND WTDEFAULT = 1
	WHERE
		EMP.ID = @EMPLOYEE_ID

	IF @WKT_ID IS NULL -- IF THERE IS NO DEFINED WORKTIME FOR THE EMPLOYEE
		RETURN NULL	  



	-- Declare the return variable here
	DECLARE @RESULT INT = NULL

	IF EXISTS(	SELECT 
					NULL 
				FROM PR_OPERATION_TIME with (nolock)
				WHERE
					EMPID = @EMPLOYEE_ID
				AND (
					DBEG < @START_DATE
					AND
					(DEND IS NULL OR DEND >= @START_DATE)   -- IF THERE IS AN OPERATION WHICH WAS STARTED EARLIER AND WAS FINISHED LATER THEN CURRENT WAS STARTED, OR IS NOT FINISHED YET
					)
			)

		SET @RESULT = 0

	ELSE
	BEGIN
		;WITH CTE_WKT_PERIODS_START AS
					(
						SELECT DISTINCT
							COALESCE(CAST(CAST(WKT_BR_PERS.TFROM AS FLOAT) - FLOOR(CAST(WKT_BR_PERS.TFROM AS FLOAT)) + FLOOR(CAST(@DATE AS FLOAT)) AS DATETIME)
									,CAST(CAST(WKT_BR.TFROM AS FLOAT) - FLOOR(CAST(WKT_BR.TFROM AS FLOAT)) + FLOOR(CAST(@DATE AS FLOAT)) AS DATETIME)
							) AS PERIOD_START
						FROM COM_EMPLOYEE EMP with (nolock)
							LEFT JOIN [dbo].[COM_WORKTIME] WKT with (nolock) ON EMP.DEPID = WKT.DEPID AND WKT.WTDEFAULT = 1
								LEFT JOIN COM_WORKTIME_BR WKT_BR with (nolock) ON WKT_BR.VNESHID = WKT.ID

							LEFT JOIN [dbo].[COM_WORKTIME] WKT_PERS with (nolock) ON EMP.PERSONALWT = WKT_PERS.ID
								LEFT JOIN COM_WORKTIME_BR WKT_BR_PERS with (nolock) ON WKT_BR_PERS.VNESHID = WKT_PERS.ID
						WHERE
							EMP.ID =@EMPLOYEE_ID

						UNION

						SELECT
							DBEG
						FROM COM_ADDED_WORKTIME ADD_WKT with (nolock)
						JOIN COM_EMPLOYEE EMP with (nolock) ON EMP.ID = ADD_WKT.EMPLID
						WHERE
							EMP.ID = @EMPLOYEE_ID
						AND 
							(ADD_WKT.DBEG >= @DATE AND ADD_WKT.DBEG < DATEADD(DAY, 1, @DATE))
					)
			SELECT	
				@DAY_START = MIN(PERIOD_START) 
			FROM CTE_WKT_PERIODS_START

			IF EXISTS(	SELECT 
							ID 
						FROM PR_OPERATION_TIME with (nolock)
						WHERE
							EMPID = @EMPLOYEE_ID
						AND
							(DEND >= @DAY_START AND DEND < @START_DATE)
						)
				WITH CTE_PREV_OP AS (
					SELECT 
						MAX(DEND) AS MAX_DEND
					FROM PR_OPERATION_TIME with (nolock)
					WHERE
						EMPID = @EMPLOYEE_ID
					AND
						(DEND >= @DAY_START AND DEND < @START_DATE)
					)
				SELECT
					@RESULT = [dbo].[COM_WORK_MINUTS](  MAX_DEND 
														,@START_DATE
														,@WKT_ID 
														,1
														, @EMPLOYEE_ID)
				FROM CTE_PREV_OP
			ELSE
				SET @RESULT = [dbo].[COM_WORK_MINUTS](@DAY_START
														,@START_DATE
														,@WKT_ID 
														,1
														, @EMPLOYEE_ID)

	END
			
	-- Return the result of the function
	RETURN @RESULT
END