create FUNCTION [dbo].[PR_PRODUCTION_PLAN3](@DEPID INT ,@START_DATE DATETIME ,@END_DATE DATETIME)
RETURNS @RESULT TABLE (
             CUSTOMER_ID INT
             ,ID INT
             ,PRODUCTION_ORDER_NUM NVARCHAR(50)
             ,SALES_ORDER_NUM NVARCHAR(50)
             ,ORDER_DATE DATETIME
             ,ORDER_EXPECTED_DATE DATETIME
             ,MODEL_ID INT
             ,REVISION_ID INT 
             ,ORDERED_QTY INT
             ,TOT_SHIPPED_DEVICE_QTY INT
             ,S_S INT
             ,REST_QTY int
             ,SUPPLYORDERID int
             ,URGENCY int
             ,ORDER_CDD DATETIME
)
AS
BEGIN
/*
ver.3 Additial field [Confirmed Date]
*/

SELECT @END_DATE = DATEADD(DAY, 1, @END_DATE);


INSERT INTO @RESULT (CUSTOMER_ID,ID,PRODUCTION_ORDER_NUM,SALES_ORDER_NUM,ORDER_DATE,ORDER_EXPECTED_DATE,MODEL_ID,REVISION_ID,ORDERED_QTY,TOT_SHIPPED_DEVICE_QTY,S_S,SUPPLYORDERID,URGENCY,ORDER_CDD,REST_QTY)
SELECT
      CUSTOMER_ID,ORDER_ID,PRODUCTION_ORDER_NUM,SALES_ORDER_NUM,ORDER_DATE,ORDER_EXPECTED_DATE,MODEL_ID,REVISION_ID,ORDERED_QTY,TOT_SHIPPED_DEVICE_QTY,ORDER_STATE,SUPPLYORDERID,URGENCY,[ORDER_CDD]
      ,ORDERED_QTY - TOT_SHIPPED_DEVICE_QTY
FROM (
select 
	CUSTOMER_ID
	,ORDER_ID
	,PRODUCTION_ORDER_NUM
	,SALES_ORDER_NUM
	,ORDER_DATE
	,ORDER_EXPECTED_DATE
	,MODEL_ID
	,REVISION_ID
	,dbo.PR_PRODUCTIONPLAN_ORDERED(ORDER_ID,MODEL_ID,REVISION_ID,SUPPLYORDERID) as ORDERED_QTY
	,dbo.PR_PRODUCTIONPLAN_SHIPPED(ORDER_ID,MODEL_ID,REVISION_ID,CUSTOMER_ID,SUPPLYORDERID) as TOT_SHIPPED_DEVICE_QTY
	,ORDER_STATE
	,SUPPLYORDERID
	,URGENCY
  ,[ORDER_CDD]
from (
SELECT distinct
		isnull(SCST.ID, CST.ID) AS CUSTOMER_ID
		,ORD.ID AS ORDER_ID
		,LTRIM(ORD.NN) AS PRODUCTION_ORDER_NUM
		,CASE	WHEN SUP.ND IS NULL THEN REPLACE(ISNULL(ORD.NN2, 'NA'), '  ', '') 
				ELSE REPLACE(ISNULL(SUP.ND, 'NA'), '  ', '') 
		 END AS SALES_ORDER_NUM
		,ORD.DD AS ORDER_DATE
		,ISNULL(SUP.DD, ORD.EXPDATE) AS ORDER_EXPECTED_DATE
		,MDL.ID AS MODEL_ID
		,REV.ID AS REVISION_ID
		,ORD.S_S AS ORDER_STATE
		,SUP.ID as SUPPLYORDERID
		,isnull(DEV.URGENCY,SUP.URGENCY) as URGENCY
    ,ORD.CDD [ORDER_CDD]
FROM PR_DEVICE DEV with (nolock)
JOIN PR_PRORDER ORD with (nolock) ON DEV.ORDERID = ORD.ID AND ORD.ORDERTYPE = 0
JOIN COM_CUSTOMER CST with (nolock) ON ORD.CUSTOMERID = CST.ID
LEFT JOIN PR_PRORDER_T ORD_T with (nolock) ON ORD.ID = ORD_T.PRORDERID
LEFT JOIN PR_SUPPLY SUP with (nolock) ON DEV.SORDERID = SUP.ID
LEFT JOIN COM_CUSTOMER SCST with (nolock) ON SUP.CUSTOMERID = SCST.ID
JOIN PR_MODELS MDL with (nolock) ON DEV.MODELID = MDL.ID
JOIN PR_REVISION REV with (nolock) ON DEV.REVID = REV.ID
WHERE
	(DEV.SHIPPED_DT >= @START_DATE AND DEV.SHIPPED_DT < @END_DATE
	OR
	ISNULL(SUP.DD, ORD.EXPDATE) >= @START_DATE AND ISNULL(SUP.DD, ORD.EXPDATE) < @END_DATE
	)
AND
	ORD.DEPARTMENTID = @DEPID 
)M
union
SELECT
		CST.ID AS CUSTOMER_ID
		,ORD.ID AS ORDER_ID
		,LTRIM(ORD.NN) AS PRODUCTION_ORDER_NUM
		,REPLACE(ISNULL(ORD.NN2, 'NA'), '  ', '') AS SALES_ORDER_NUM
		,ORD.DD AS ORDER_DATE
		,ORD.EXPDATE AS ORDER_EXPECTED_DATE
		,MDL.ID AS MODEL_ID
		,REV.ID AS REVISION_ID
		,ORD_T.QUANTITY AS ORDERED_QTY
		,0 AS TOT_SHIPPED_DEVICE_QTY
		,ORD.S_S AS ORDER_STATE
		,null as SUPPLYORDERID
		,ORD.URGENCY
    ,ORD.CDD [ORDER_CDD]
	FROM COM_CUSTOMER CST with (nolock)
	JOIN PR_PRORDER ORD with (nolock) ON CST.ID = ORD.CUSTOMERID
		LEFT JOIN PR_PRORDER_T ORD_T with (nolock) ON ORD.ID = ORD_T.PRORDERID
			LEFT JOIN PR_MODELS MDL with (nolock) ON ORD_T.MODELID = MDL.ID
			LEFT JOIN PR_REVISION REV with (nolock) ON ORD_T.REVID = REV.ID
	WHERE 
		(ORD.EXPDATE >= @START_DATE AND ORD.EXPDATE < @END_DATE)
	AND
		ORD.DEPARTMENTID = @DEPID 
	AND
		ORD.ORDERTYPE = 0
	AND
		NOT EXISTS (SELECT 1 FROM PR_DEVICE with (nolock) WHERE ORDERID = ORD.ID) --  по заказам ещё не созданы изделия (заказ не запущен в производство)
		)T

	ORDER BY ORDER_EXPECTED_DATE, PRODUCTION_ORDER_NUM
RETURN
END