-- =============================================
-- Author:		Граматкин Антон
-- Create date: 25-11-2014
-- Description:	Ф-ция отдаёт кол-во приборов, которым осталось пройти указанный этап до конца текущего месяца.
-- =============================================
CREATE FUNCTION PR_STAGE_REST_ITEMS
(
	@STAGE INT
	,@UserId INT
)
RETURNS DECIMAL(16,2)
AS
BEGIN
	DECLARE
		@EXPDATE DATETIME
		,@TODAY DATETIME
		,@RESULT DECIMAL(16,2) = -1

	SELECT @TODAY = GETDATE()
	SELECT @EXPDATE = DATEADD(s,-1,DATEADD(mm, DATEDIFF(m,0,GETDATE())+1,0))


	DECLARE @TMP_DEP TABLE(ID INT PRIMARY KEY)
	INSERT INTO @TMP_DEP
	SELECT 
		ID 
	FROM COM_ACCESS_DEPARTMENTS(@UserId, 3, @TODAY)


	SELECT
		@RESULT = SUM(INCOMPL_PCT)/100
	FROM (

	SELECT DISTINCT
		DEV.ID
		,MDL.NAME
		,ISNULL(SORD.DD, ORD.EXPDATE) AS DATE
		,OPTP.STAGEID
		,100 - ISNULL(dbo.PR_STAGE_INFO(DEV.ID, DEV.ORDERID, @STAGE, @TODAY, @TODAY, 3),0) AS INCOMPL_PCT
		--,1 AS INCOMPL_PCT
	FROM PR_DEVICE DEV
	JOIN PR_MODELS MDL ON DEV.MODELID = MDL.ID
		JOIN PR_MODELTYPE MDLTP ON MDL.TYPEID = MDLTP.ID
			JOIN @TMP_DEP DEP ON MDLTP.DEPARTMENTID = DEP.ID

	JOIN PR_PRORDER ORD ON DEV.ORDERID = ORD.ID
	LEFT JOIN PR_SUPPLY SORD ON DEV.SORDERID = SORD.ID

	JOIN PR_MAP_OPER MOP ON MOP.MAPID = DEV.MAPID
		JOIN PR_OPERATIONS OPTP ON MOP.OPERID = OPTP.ID AND OPTP.STAGEID = @STAGE

	WHERE
		ISNULL(SORD.DD, ORD.EXPDATE) <= @EXPDATE
	AND 
		DEV.COMPLETED_DT IS NULL
	AND 
		DEV.S_S NOT IN (1000078, 1000101)
		)T
	WHERE
		INCOMPL_PCT > 0

	RETURN @RESULT
END