-- =============================================
-- Author:      <Author,,Name>
-- Create date: <Create Date,,>
-- Description: <Description,,>
-- =============================================
CREATE FUNCTION [dbo].[PRR_OPER_RELATIVE_PERF_DETAIL]
(
    @EMP_ID INT
    ,@START_DATE DATE
    ,@END_DATE DATE
    ,@AVIABLE_OPERATIONS NVARCHAR(MAX)
)
RETURNS 
@RES TABLE
(
    EMPLOYEE_ID INT
    ,USER_ID INT
    ,OPERATION_ID INT
    ,OPERATION_NAME NVARCHAR(255)
    ,FINISH_DATE DATETIME
    ,TOTAL_OPER_TIME INT
    ,MANHOUR DECIMAL(10,4)
    ,ORDER_NUM NVARCHAR(255)
    ,DEVICE_SN  NVARCHAR(255)
    ,MODEL_NAME  NVARCHAR(255)
    ,REVISION_NAME  NVARCHAR(255)
    ,MARK_SHARED INT
)
AS
BEGIN
    SELECT @END_DATE = DATEADD(DAY, 1, @END_DATE)

-- SHARED OPERATIONS
DECLARE @TMP_OPERATIONS TABLE ( -- ONLY NOT SHARED OPERATIONS
                ID INT
                ,USR_PER_OPER INT
            )

DECLARE @TMP_AVIABLE_OPER TABLE (
                ID INT PRIMARY KEY
                ,NAME NVARCHAR(255)
                ,MANHOUR DECIMAL(10,4)
            )

;WITH CTE_AV_OP AS (    SELECT CONVERT(INT, Item) AS ID FROM
          ( SELECT Item = x.i.value('(./text())[1]', 'varchar(max)')
            FROM ( SELECT [XML] = CONVERT(XML, '<i>'
            + REPLACE(@AVIABLE_OPERATIONS, ',', '</i><i>') + '</i>').query('.')
              ) AS a CROSS APPLY [XML].nodes('i') AS x(i) ) AS y
          WHERE Item IS NOT NULL
)
INSERT INTO @TMP_AVIABLE_OPER
SELECT
    AV_OP.ID
    ,OP_T.NAME
    ,OP_T.MANHOUR
FROM CTE_AV_OP AV_OP
LEFT JOIN PR_OPERATIONS OP_T ON AV_OP.ID = OP_T.ID


INSERT INTO @TMP_OPERATIONS
    SELECT
        OP.ID
        ,COUNT(DISTINCT OP_TIME.USERID) AS USR_PER_OPER
    FROM PR_OPERATION OP
    JOIN PR_OPERATION_TIME OP_TIME ON OP.ID = OP_TIME.OPERID
    JOIN @TMP_AVIABLE_OPER OP_TYPE ON OP.OPERTYPEID = OP_TYPE.ID
    WHERE
        OP.COMPLETED_DT >= @START_DATE AND OP.COMPLETED_DT < @END_DATE
    GROUP BY
        OP.ID
    HAVING COUNT(DISTINCT OP_TIME.USERID) > 1
-------------------------------------
INSERT INTO @RES

SELECT
    EMPLOYEE_ID
    ,USER_ID
    ,OPERATION_ID
    ,OPERATION_NAME
    ,FINISH_DATE
    ,SUM(TOTAL_OPER_TIME) AS TOTAL_OPER_TIME
    ,MANHOUR
    ,ORDER_NUM
    ,DEVICE_SN
    ,MODEL_NAME
    ,REVISION_NAME
    ,MARK_SHARED
FROM (

SELECT
    EMP.ID  AS EMPLOYEE_ID
    ,USR.ID AS USER_ID
    ,OP.ID AS OPERATION_ID
    ,OP_TYPE.NAME AS OPERATION_NAME
    ,OP.COMPLETED_DT  AS FINISH_DATE
    ,CASE -- IF OPERATION WAS EXECUTED AT MORE THEN 1 ITEM DIVIDE TOTAL ELAPSED TIME TO ITEMS COUNT
            WHEN ISNULL(OP.PREP_RESULT,0) > 1 THEN COALESCE(OP_T.ELAPSEDCORR, OP_T.ELAPSED, 0)/OP.PREP_RESULT
            ELSE COALESCE(OP_T.ELAPSEDCORR, OP_T.ELAPSED, 0)
        END AS TOTAL_OPER_TIME
    ,COALESCE(REV_MH.MANHOUR2, OP_TYPE.MANHOUR, 0)+ COALESCE(ADD_MH.MANHOUR, 0)  AS MANHOUR
    ,COALESCE(SUPP.ND, ORD.NN, 'NA') AS ORDER_NUM
    ,ISNULL(DEV.SN, 'NA') AS DEVICE_SN
    ,ISNULL(MDL.NAME, 'NA') AS MODEL_NAME
    ,ISNULL(REV.NAME, 'NA') AS REVISION_NAME
    ,CASE  -- IF OPERATION SHARED = 1, IF NOT = 0
        WHEN SINGLE_OP.ID IS NOT NULL THEN 1
        ELSE 0
    END AS MARK_SHARED
FROM COM_EMPLOYEE EMP
JOIN DEF_USERS USR ON USR.EMPLOYEEID = EMP.ID
    JOIN PR_OPERATION_TIME OP_T ON OP_T.USERID = USR.ID
        JOIN PR_OPERATION OP ON OP_T.OPERID = OP.ID  AND OP.COMPLETED_DT >= @START_DATE AND OP.COMPLETED_DT < @END_DATE
            JOIN @TMP_AVIABLE_OPER OP_TYPE ON OP.OPERTYPEID = OP_TYPE.ID
            --LEFT JOIN PR_OPERATIONS OP_TYPE ON OP.OPERTYPEID = OP_TYPE.ID
                --JOIN [dbo].[PR_OPERATIONS_GR] OP_TYPE_GR ON OP_TYPE.[OPERGRID] = OP_TYPE_GR.ID
            
            LEFT JOIN PR_DEVICE DEV ON OP.DEVICEID = DEV.ID
                    LEFT JOIN PR_REV_OVER_MH REV_MH ON DEV.REVID = REV_MH.REVID AND REV_MH.OPERID = OP.OPERTYPEID
                    LEFT JOIN PR_SUPPLY SUPP ON DEV.SORDERID = SUPP.ID
                    LEFT JOIN PR_MODELS MDL ON DEV.MODELID = MDL.ID
                    LEFT JOIN PR_REVISION REV ON DEV.REVID = REV.ID

            LEFT JOIN (SELECT 
                            MH.OPERID
                            ,DEV_OPT.DEVICEID
                            ,SUM(MH.MANHOUR2) AS MANHOUR
                        FROM PR_OPER_ADD_MH MH
                        JOIN PR_DEVICE_OPT DEV_OPT ON DEV_OPT.OPTID = MH.OPTID
                        
                        GROUP BY MH.OPERID, DEV_OPT.DEVICEID
                        ) ADD_MH ON ADD_MH.OPERID = OP.OPERTYPEID AND ADD_MH.DEVICEID = OP.DEVICEID

            LEFT JOIN PR_PRORDER ORD ON OP.ORDERID = ORD.ID
            LEFT JOIN @TMP_OPERATIONS SINGLE_OP ON OP.ID = SINGLE_OP.ID
            

WHERE
    EMP.ID = @EMP_ID
--AND
    --OP_TYPE_GR.[DEPARTMENTID] IN (SELECT ID FROM [dbo].[COM_ACCESS_DEPARTMENTS] (dbo.DEF_USERID(),3,GETDATE()))
) T
GROUP BY 
    EMPLOYEE_ID
    ,USER_ID
    ,OPERATION_ID
    ,OPERATION_NAME
    ,FINISH_DATE
    ,MANHOUR
    ,ORDER_NUM
    ,DEVICE_SN
    ,MODEL_NAME
    ,REVISION_NAME
    ,MARK_SHARED
ORDER BY FINISH_DATE


    
    RETURN 
END