CREATE TABLE [dbo].[COM_SENDED_REPORTS] (
    [ID]           INT         IDENTITY (1, 1) NOT NULL,
    [REPORT_NAME]  NCHAR (250) NOT NULL,
    [LAST_SEND_DT] DATETIME    NOT NULL,
    CONSTRAINT [PK_COM_SENDED_REPORTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

