CREATE TABLE [dbo].[COM_CUST_ENDUSERS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [ENDUSERID] INT              NOT NULL,
    [CODE]      NVARCHAR (10)    NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_CUST_ENDUSERS_ENDUSERID] FOREIGN KEY ([ENDUSERID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_COM_CUST_ENDUSERS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_CUST_ENDUSERS]
    ON [dbo].[COM_CUST_ENDUSERS]([VNESHID] ASC, [CODE] ASC);

