CREATE TABLE [dbo].[COM_MANAGED_ADDR_GROUPS_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [ADUSERID] UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_MANAGED_ADDR_GROUPS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_MANAGED_ADDR_GROUPS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_MANAGED_ADDR_GROUPS_T]
    ON [dbo].[COM_MANAGED_ADDR_GROUPS_T]([VNESHID] ASC);

