CREATE TABLE [dbo].[COM_ZEITARBEITREPORT_WASNOTIFYED] (
    [ID]    INT IDENTITY (1, 1) NOT NULL,
    [EMPID] INT NOT NULL,
    [WEEKN] INT NOT NULL,
    [NMODE] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_ZEITARBEITREPORT_WASNOTIFYED]
    ON [dbo].[COM_ZEITARBEITREPORT_WASNOTIFYED]([EMPID] ASC, [WEEKN] ASC, [NMODE] ASC);

