CREATE TABLE [dbo].[COM_PERSONALWORKTIME_HISTORY] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NOT NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [EMPLOYEEID] INT              NOT NULL,
    [PERSONALWT] INT              NULL,
    [DBEG]       DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_PERSONALWORKTIME_HISTORY_EMPLOYEEID] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_COM_PERSONALWORKTIME_HISTORY_PERSONALWT] FOREIGN KEY ([PERSONALWT]) REFERENCES [dbo].[COM_WORKTIME] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_PERSONALWORKTIME_HISTORY]
    ON [dbo].[COM_PERSONALWORKTIME_HISTORY]([EMPLOYEEID] ASC)
    INCLUDE([PERSONALWT], [DBEG]);

