CREATE TABLE [dbo].[COM_ADDED_WORKTIME_PLAN_T] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GID]    UNIQUEIDENTIFIER NOT NULL,
    [S_CR]   INT              NOT NULL,
    [S_CDT]  DATETIME         NOT NULL,
    [S_MR]   INT              NULL,
    [S_MDT]  DATETIME         NULL,
    [ARC]    INT              NULL,
    [PLANID] INT              NOT NULL,
    [EMPID]  INT              NOT NULL,
    [HOURS]  DECIMAL (10, 2)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_ADDED_WORKTIME_PLAN_T_EMPID] FOREIGN KEY ([EMPID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_ADDED_WORKTIME_PLAN_T_PLANID] FOREIGN KEY ([PLANID]) REFERENCES [dbo].[COM_ADDED_WORKTIME_PLAN] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_ADDED_WORKTIME_PLAN_T_1]
    ON [dbo].[COM_ADDED_WORKTIME_PLAN_T]([PLANID] ASC, [EMPID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_ADDED_WORKTIME_PLAN_T]
    ON [dbo].[COM_ADDED_WORKTIME_PLAN_T]([PLANID] ASC);

