CREATE TABLE [dbo].[COM_MESSAGE_EMPL_FILES] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [FILEID]   INT              NOT NULL,
    [OPENDATE] DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_MESSAGE_EMPL_FILES_FILEID] FOREIGN KEY ([FILEID]) REFERENCES [dbo].[COM_SPV_MESSAGE_FILES] ([ID]),
    CONSTRAINT [FK_COM_MESSAGE_EMPL_FILES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_MESSAGE_EMPL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_MESSAGE_EMPL_FILES]
    ON [dbo].[COM_MESSAGE_EMPL_FILES]([VNESHID] ASC);

