CREATE TABLE [dbo].[COM_SPECIAL_LEAVES_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [CODE]    NVARCHAR (10)    NOT NULL,
    [NAME]    NVARCHAR (100)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_SPECIAL_LEAVES_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_SPECIAL_LEAVES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_SPECIAL_LEAVES_T]
    ON [dbo].[COM_SPECIAL_LEAVES_T]([VNESHID] ASC);

