CREATE TABLE [dbo].[COM_COUNTRIES] (
    [ID]    INT              IDENTITY (1, 1) NOT NULL,
    [GID]   UNIQUEIDENTIFIER NULL,
    [S_CR]  INT              NULL,
    [S_CDT] DATETIME         NULL,
    [S_MR]  INT              NULL,
    [S_MDT] DATETIME         NULL,
    [CODE]  NVARCHAR (10)    NOT NULL,
    [NAME]  NVARCHAR (100)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_COUNTRIES_NAME]
    ON [dbo].[COM_COUNTRIES]([NAME] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_COUNTRIES_CODE]
    ON [dbo].[COM_COUNTRIES]([CODE] ASC);

