CREATE TABLE [dbo].[COM_ADP_EMPLOYEE] (
    [AOID]          NVARCHAR (20)  NOT NULL,
    [FIRSTNAME]     NVARCHAR (100) NOT NULL,
    [LASTNAME]      NVARCHAR (100) NOT NULL,
    [HIREDATE]      DATE           NULL,
    [TERMINATEDATE] DATE           NULL,
    [EMPLOYEEID]    INT            NULL,
    [FULLNAME]      AS             (([FIRSTNAME]+' ')+[LASTNAME]),
    [WORKERID]      NVARCHAR (100) NULL,
    [POSITIONID]    NVARCHAR (100) NULL,
    [WACOUNT]       INT            NULL,
    CONSTRAINT [PK_COM_ADP_EMPLOYEE] PRIMARY KEY CLUSTERED ([AOID] ASC)
);

