CREATE TABLE [dbo].[COM_EMPL_PERIODS] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GID]    UNIQUEIDENTIFIER NULL,
    [S_CR]   INT              NOT NULL,
    [S_CDT]  DATETIME         NOT NULL,
    [S_MR]   INT              NULL,
    [S_MDT]  DATETIME         NULL,
    [ARC]    INT              NULL,
    [EMPLID] INT              NOT NULL,
    [DBEG]   DATETIME         NOT NULL,
    [DEND]   DATETIME         NULL,
    [DEPID]  INT              NOT NULL,
    [REMARK] NVARCHAR (1000)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_EMPL_PERIODS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_COM_EMPL_PERIODS_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_EMPL_PERIODS_DBEG_DEND_EMPLID_DEPID]
    ON [dbo].[COM_EMPL_PERIODS]([DBEG] ASC, [DEND] ASC)
    INCLUDE([EMPLID], [DEPID]);


GO
CREATE NONCLUSTERED INDEX [IX_COM_EMPL_PERIODS]
    ON [dbo].[COM_EMPL_PERIODS]([EMPLID] ASC)
    INCLUDE([DBEG], [DEND]);

