CREATE TABLE [dbo].[COM_WORKTIME_NW_WEEKS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [WEEKN]   INT              NOT NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_WORKTIME_NW_WEEKS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_WORKTIME] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_WORKTIME_NW_WEEKS2]
    ON [dbo].[COM_WORKTIME_NW_WEEKS]([VNESHID] ASC, [WEEKN] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_WORKTIME_NW_WEEKS]
    ON [dbo].[COM_WORKTIME_NW_WEEKS]([VNESHID] ASC);

