CREATE TABLE [dbo].[COM_CUST_GROUP_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [VNESHID] INT              NOT NULL,
    [CUSTID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_COM_CUST_GROUP_T_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_COM_CUST_GROUP_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_CUST_GROUP] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_CUST_GROUP_T]
    ON [dbo].[COM_CUST_GROUP_T]([VNESHID] ASC) WITH (FILLFACTOR = 90);


GO
GRANT SELECT
    ON OBJECT::[dbo].[COM_CUST_GROUP_T] TO [IPG-DOMAIN\IPGL_Integr_MSCRM]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[COM_CUST_GROUP_T] TO [EMEA\DEPCS]
    AS [dbo];

