CREATE TABLE [dbo].[COM_EVENTS_AND_METRICS] (
    [ID]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [S_CR]         INT             NOT NULL,
    [S_CDT]        DATETIME        NOT NULL,
    [NAME]         VARCHAR (30)    NOT NULL,
    [OBJECT_ID]    INT             NULL,
    [MACHINE_NAME] VARCHAR (15)    NULL,
    [METRICS_JSON] NVARCHAR (4000) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_EVENTS_AND_METRICS_NAME]
    ON [dbo].[COM_EVENTS_AND_METRICS]([NAME] ASC, [OBJECT_ID] ASC);

