CREATE TABLE [dbo].[COM_TRAINING_MAINTENANCE] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [GID]                UNIQUEIDENTIFIER NULL,
    [S_CR]               INT              NOT NULL,
    [S_CDT]              DATETIME         NOT NULL,
    [S_MR]               INT              NULL,
    [S_MDT]              DATETIME         NULL,
    [ARC]                INT              NULL,
    [TRAININGID]         INT              NOT NULL,
    [EQID]               INT              NOT NULL,
    [OPERFORM_ID]        INT              NOT NULL,
    [OPERID]             INT              NULL,
    [TRAINER_ID]         INT              NOT NULL,
    [CHECKED_TRAINER_ID] INT              NULL,
    [CHECKED_TRAINER_DT] DATETIME         NULL,
    [TRAINING_STATE]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_TRAINING_MAINTENANCE_CHECKED_TRAINER_ID] FOREIGN KEY ([CHECKED_TRAINER_ID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_MAINTENANCE_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_MAINTENANCE_OPERFORM_ID] FOREIGN KEY ([OPERFORM_ID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_MAINTENANCE_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_MAINTENANCE_TRAINER_ID] FOREIGN KEY ([TRAINER_ID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_MAINTENANCE_TRAININGID] FOREIGN KEY ([TRAININGID]) REFERENCES [dbo].[COM_TRAINING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_TRAINING_MAINTENANCE]
    ON [dbo].[COM_TRAINING_MAINTENANCE]([TRAININGID] ASC);

