CREATE TABLE [dbo].[COM_CUST_CONTACTS] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NULL,
    [S_CDT]         DATETIME         NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [NAME]          NVARCHAR (100)   NOT NULL,
    [PHONE]         NVARCHAR (100)   NULL,
    [EMAIL]         NVARCHAR (250)   NULL,
    [CONTACTTYPEID] INT              NULL,
    [CUSTOMERID]    INT              NOT NULL,
    [REMARK]        NTEXT            NULL,
    [temp_SID]      INT              NULL,
    [FAXN]          NVARCHAR (100)   NULL,
    [CODE]          NVARCHAR (16)    NULL,
    [MOBILEPHONE]   NVARCHAR (100)   NULL,
    [CRMGUID]       UNIQUEIDENTIFIER NULL,
    [S_S]           INT              NOT NULL,
    [FIRSTNAME]     NVARCHAR (100)   NULL,
    [LASTNAME]      NVARCHAR (100)   NULL,
    [temp_WG]       INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_CUST_CONTACTS_CONTACTTYPEID] FOREIGN KEY ([CONTACTTYPEID]) REFERENCES [dbo].[COM_CONTACTTYPE] ([ID]),
    CONSTRAINT [FK_COM_CUST_CONTACTS_CUSTOMERID] FOREIGN KEY ([CUSTOMERID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_CUST_CONTACTS_EMAIL]
    ON [dbo].[COM_CUST_CONTACTS]([EMAIL] ASC) WHERE ([EMAIL] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_CUST_CONTACTS_CRMGUID]
    ON [dbo].[COM_CUST_CONTACTS]([CRMGUID] ASC) WHERE ([CRMGUID] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_CUST_CONTACTS_CODE]
    ON [dbo].[COM_CUST_CONTACTS]([CODE] ASC) WHERE ([CODE] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_COM_CUST_CONTACTS]
    ON [dbo].[COM_CUST_CONTACTS]([CUSTOMERID] ASC);

