CREATE TABLE [dbo].[COM_WORKTIME_BR] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [TFROM]    DATETIME         NOT NULL,
    [TTO]      DATETIME         NOT NULL,
    [WTURN]    INT              NOT NULL,
    [TDEXTDAY] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_COM_WORKTIME_BR_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_WORKTIME] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_WORKTIME_BR_VNESHIDWTURN]
    ON [dbo].[COM_WORKTIME_BR]([VNESHID] ASC, [WTURN] ASC)
    INCLUDE([TFROM], [TTO]);


GO
CREATE NONCLUSTERED INDEX [IX_COM_WORKTIME_BR]
    ON [dbo].[COM_WORKTIME_BR]([VNESHID] ASC) WITH (FILLFACTOR = 90);

