CREATE TABLE [dbo].[COM_MESSAGE_EMPL] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [VNESHID]       INT              NOT NULL,
    [EMPLID]        INT              NOT NULL,
    [READED]        DATETIME         NULL,
    [FILESOPENDATE] DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_MESSAGE_EMPL_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_MESSAGE_EMPL_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[COM_SPV_MESSAGE] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_MESSAGE_EMPL_1]
    ON [dbo].[COM_MESSAGE_EMPL]([VNESHID] ASC, [EMPLID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_MESSAGE_EMPL]
    ON [dbo].[COM_MESSAGE_EMPL]([VNESHID] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_MESSAGE_EMPL_IMPLID]
    ON [dbo].[COM_MESSAGE_EMPL]([EMPLID] ASC);

