CREATE TABLE [dbo].[COM_EMPLOYEE_SKILL_PROLONGATION] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [EMPLOYEEID]   INT              NULL,
    [SKILLID]      INT              NULL,
    [PROLONG_DATE] DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_EMPLOYEE_SKILL_PROLONGATION_EMPLOYEEID] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_EMPLOYEE_SKILL_PROLONGATION_SKILLID] FOREIGN KEY ([SKILLID]) REFERENCES [dbo].[COM_SKILLS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_EMPLOYEE_SKILL_PROLONGATION]
    ON [dbo].[COM_EMPLOYEE_SKILL_PROLONGATION]([EMPLOYEEID] ASC, [SKILLID] ASC);

