CREATE TABLE [dbo].[COM_ADP_POSITIONIDS] (
    [ID]         INT            IDENTITY (1, 1) NOT NULL,
    [AOID]       NVARCHAR (20)  NULL,
    [POSITIONID] NVARCHAR (100) NULL,
    CONSTRAINT [PK_COM_ADP_POSITIONIDS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_ADP_POSITIONIDS_COM_ADP_EMPLOYEE] FOREIGN KEY ([AOID]) REFERENCES [dbo].[COM_ADP_EMPLOYEE] ([AOID])
);

