CREATE TABLE [dbo].[COM_TRAINING_PREPARATORY] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [GID]                UNIQUEIDENTIFIER NULL,
    [S_CR]               INT              NOT NULL,
    [S_CDT]              DATETIME         NOT NULL,
    [S_MR]               INT              NULL,
    [S_MDT]              DATETIME         NULL,
    [ARC]                INT              NULL,
    [TRAINING_ID]        INT              NOT NULL,
    [PREPARATORY_ID]     INT              NULL,
    [TRAINER_ID]         INT              NULL,
    [OPERID]             INT              NULL,
    [CHECKED_TRAINER_ID] INT              NULL,
    [CHECKED_TRAINER_DT] DATETIME         NULL,
    [TRAINING_STATE]     INT              NULL,
    [OPERTYPEID]         INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_TRAINING_PREPARATORY_CHECKED_TRAINER_ID] FOREIGN KEY ([CHECKED_TRAINER_ID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_PREPARATORY_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_PREPARATORY_OPERTYPEID] FOREIGN KEY ([OPERTYPEID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_PREPARATORY_PREPARATORY_ID] FOREIGN KEY ([PREPARATORY_ID]) REFERENCES [dbo].[PR_PREPARATORY] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_PREPARATORY_TRAINER_ID] FOREIGN KEY ([TRAINER_ID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_PREPARATORY_TRAINING_ID] FOREIGN KEY ([TRAINING_ID]) REFERENCES [dbo].[COM_TRAINING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_TRAINING_PREPARATORY_OPERTYPEID]
    ON [dbo].[COM_TRAINING_PREPARATORY]([OPERTYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_TRAINING_PREPARATORY_OPERID]
    ON [dbo].[COM_TRAINING_PREPARATORY]([OPERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_TRAINING_PREPARATORY]
    ON [dbo].[COM_TRAINING_PREPARATORY]([TRAINING_ID] ASC);

