CREATE TABLE [dbo].[COM_VACATIONS_INFO] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [PERSONALNO] NVARCHAR (20)    NOT NULL,
    [DD]         DATETIME         NOT NULL,
    [ENTITLED]   DECIMAL (12, 2)  NULL,
    [APPROVED]   DECIMAL (12, 2)  NULL,
    [REQUESTED]  DECIMAL (12, 2)  NULL,
    [AVAILABLE]  DECIMAL (12, 2)  NULL,
    [EMPLOYEEID] INT              NULL,
    [INFOSOURCE] NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_VACATIONS_INFO_PERSONALNO]
    ON [dbo].[COM_VACATIONS_INFO]([PERSONALNO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_VACATIONS_INFO_EMPLOYEEID]
    ON [dbo].[COM_VACATIONS_INFO]([EMPLOYEEID] ASC) WHERE ([EMPLOYEEID] IS NOT NULL);

