CREATE TABLE [dbo].[COM_OPERATION_GROUP_SKILL] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [OPERGROUP_ID] INT              NOT NULL,
    [SKILLID]      INT              NOT NULL,
    [MODELID]      INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_OPERATION_GROUP_SKILL_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_COM_OPERATION_GROUP_SKILL_OPERGROUP_ID] FOREIGN KEY ([OPERGROUP_ID]) REFERENCES [dbo].[PR_OPERATIONS_GR] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_COM_OPERATION_GROUP_SKILL_SKILLID] FOREIGN KEY ([SKILLID]) REFERENCES [dbo].[COM_SKILLS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_OPERATION_GROUP_SKILL_1]
    ON [dbo].[COM_OPERATION_GROUP_SKILL]([OPERGROUP_ID] ASC, [SKILLID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_OPERATION_GROUP_SKILL]
    ON [dbo].[COM_OPERATION_GROUP_SKILL]([OPERGROUP_ID] ASC);

