CREATE TABLE [dbo].[COM_TURNS] (
    [ID]     INT      IDENTITY (1, 1) NOT NULL,
    [EMPLID] INT      NOT NULL,
    [DD]     DATE     NOT NULL,
    [WTURN]  INT      NOT NULL,
    [S_CR]   INT      NULL,
    [S_MR]   INT      NULL,
    [S_CDT]  DATETIME NULL,
    [S_MDT]  DATETIME NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_TURNS_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_TURNS]
    ON [dbo].[COM_TURNS]([EMPLID] ASC, [DD] ASC)
    INCLUDE([WTURN]);

