CREATE TABLE [dbo].[COM_ADP_TIMEOFF] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [EMPLOYEEID]  INT            NOT NULL,
    [REQUESTID]   NVARCHAR (200) NULL,
    [ENTRYID]     NVARCHAR (200) NULL,
    [ENTRYTYPE]   NVARCHAR (200) NULL,
    [ENTRYSTATUS] NVARCHAR (200) NULL,
    [DBEG]        DATE           NULL,
    [DEND]        DATE           NULL,
    [STTARTTIME]  NVARCHAR (50)  NULL,
    [QTY]         DECIMAL (6, 2) NULL,
    [TIMECODE]    NVARCHAR (200) NULL,
    CONSTRAINT [PK_COM_ADP_TIMEOFF] PRIMARY KEY CLUSTERED ([ID] ASC)
);

