CREATE TABLE [dbo].[COM_TRAINING_OPERATIONS] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [GID]                UNIQUEIDENTIFIER NULL,
    [S_CR]               INT              NOT NULL,
    [S_CDT]              DATETIME         NOT NULL,
    [S_MR]               INT              NULL,
    [S_MDT]              DATETIME         NULL,
    [ARC]                INT              NULL,
    [TRAININGID]         INT              NOT NULL,
    [DEVICE_ID]          INT              NULL,
    [MAPOPER_ID]         INT              NULL,
    [TRAINER_ID]         INT              NULL,
    [OPERID]             INT              NULL,
    [CHECKED_TRAINER_ID] INT              NULL,
    [CHECKED_TRAINER_DT] DATETIME         NULL,
    [TRAINING_STATE]     INT              NULL,
    [MODELID]            INT              NULL,
    [REVISIONID]         INT              NULL,
    [OPERTYPEID]         INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_TRAINING_OPERATIONS_CHECKED_TRAINER_ID] FOREIGN KEY ([CHECKED_TRAINER_ID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_OPERATIONS_DEVICE_ID] FOREIGN KEY ([DEVICE_ID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_OPERATIONS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_OPERATIONS_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_OPERATIONS_OPERTYPEID] FOREIGN KEY ([OPERTYPEID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_OPERATIONS_REVISIONID] FOREIGN KEY ([REVISIONID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_COM_TRAINING_OPERATIONS_TRAINER_ID] FOREIGN KEY ([TRAINER_ID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_TRAINING_PREPARATORY_OPERTYPEID]
    ON [dbo].[COM_TRAINING_OPERATIONS]([OPERTYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_TRAINING_OPERATIONS_OPERID]
    ON [dbo].[COM_TRAINING_OPERATIONS]([OPERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_TRAINING_OPERATIONS_DEVICEID]
    ON [dbo].[COM_TRAINING_OPERATIONS]([DEVICE_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_COM_TRAINING_OPERATIONS]
    ON [dbo].[COM_TRAINING_OPERATIONS]([TRAININGID] ASC);

