CREATE TABLE [dbo].[COM_ZEITARBEITREPORT] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [GID]              UNIQUEIDENTIFIER NULL,
    [S_CR]             INT              NOT NULL,
    [S_CDT]            DATETIME         NOT NULL,
    [S_MR]             INT              NULL,
    [S_MDT]            DATETIME         NULL,
    [ARC]              INT              NULL,
    [EMPLID]           INT              NOT NULL,
    [REMARK]           NTEXT            NULL,
    [D1_START]         DATETIME         NULL,
    [D1_END]           DATETIME         NULL,
    [D1_PAUSE]         DATETIME         NULL,
    [WEEKDD]           DATETIME         NOT NULL,
    [D2_START]         DATETIME         NULL,
    [D2_END]           DATETIME         NULL,
    [D2_PAUSE]         DATETIME         NULL,
    [D3_START]         DATETIME         NULL,
    [D3_END]           DATETIME         NULL,
    [D3_PAUSE]         DATETIME         NULL,
    [D4_START]         DATETIME         NULL,
    [D4_END]           DATETIME         NULL,
    [D4_PAUSE]         DATETIME         NULL,
    [D5_START]         DATETIME         NULL,
    [D5_END]           DATETIME         NULL,
    [D5_PAUSE]         DATETIME         NULL,
    [D6_START]         DATETIME         NULL,
    [D6_END]           DATETIME         NULL,
    [D6_PAUSE]         DATETIME         NULL,
    [D7_START]         DATETIME         NULL,
    [D7_END]           DATETIME         NULL,
    [D7_PAUSE]         DATETIME         NULL,
    [WEEKN]            INT              NOT NULL,
    [S_S]              INT              NOT NULL,
    [CD1_START]        DATETIME         NULL,
    [CD1_END]          DATETIME         NULL,
    [CD1_PAUSE]        DATETIME         NULL,
    [CD2_START]        DATETIME         NULL,
    [CD2_END]          DATETIME         NULL,
    [CD2_PAUSE]        DATETIME         NULL,
    [CD3_START]        DATETIME         NULL,
    [CD3_END]          DATETIME         NULL,
    [CD3_PAUSE]        DATETIME         NULL,
    [CD4_START]        DATETIME         NULL,
    [CD4_END]          DATETIME         NULL,
    [CD4_PAUSE]        DATETIME         NULL,
    [CD5_START]        DATETIME         NULL,
    [CD5_END]          DATETIME         NULL,
    [CD5_PAUSE]        DATETIME         NULL,
    [CD6_START]        DATETIME         NULL,
    [CD6_END]          DATETIME         NULL,
    [CD6_PAUSE]        DATETIME         NULL,
    [CD7_START]        DATETIME         NULL,
    [CD7_END]          DATETIME         NULL,
    [CD7_PAUSE]        DATETIME         NULL,
    [REJECTIONREMARK]  NTEXT            NULL,
    [CD1_VAC]          INT              NULL,
    [CD2_VAC]          INT              NULL,
    [CD3_VAC]          INT              NULL,
    [CD4_VAC]          INT              NULL,
    [CD5_VAC]          INT              NULL,
    [CD6_VAC]          INT              NULL,
    [CD7_VAC]          INT              NULL,
    [MONTH_END]        INT              NULL,
    [DAYS_2_MONTH_END] INT              NULL,
    [MONTH_END_DATE]   DATE             NULL,
    [D1_DISABLE]       INT              NULL,
    [D2_DISABLE]       INT              NULL,
    [D3_DISABLE]       INT              NULL,
    [D4_DISABLE]       INT              NULL,
    [D5_DISABLE]       INT              NULL,
    [D6_DISABLE]       INT              NULL,
    [D7_DISABLE]       INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_COM_ZEITARBEITREPORT_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_COM_ZEITARBEITREPORT_WEEKDD]
    ON [dbo].[COM_ZEITARBEITREPORT]([WEEKDD] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COM_ZEITARBEITREPORT_EMPLIDWEEKN]
    ON [dbo].[COM_ZEITARBEITREPORT]([EMPLID] ASC, [WEEKN] ASC, [MONTH_END] ASC);

