CREATE TABLE [dbo].[CS_HPLASER_SUB_PERM_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [CUSTID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CS_HPLASER_SUB_PERM_T_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_CS_HPLASER_SUB_PERM_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[CS_HPLASER_SUB_PERM] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CS_HPLASER_SUB_PERM_T_2]
    ON [dbo].[CS_HPLASER_SUB_PERM_T]([VNESHID] ASC, [CUSTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_CS_HPLASER_SUB_PERM_T]
    ON [dbo].[CS_HPLASER_SUB_PERM_T]([VNESHID] ASC);

