CREATE TABLE [dbo].[CS_HPLASER_SUB_PERM_ITEMS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [DEVICEID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CS_HPLASER_SUB_PERM_ITEMS_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_CS_HPLASER_SUB_PERM_ITEMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[CS_HPLASER_SUB_PERM] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_CS_HPLASER_SUB_PERM_ITEMS_DEVICEID]
    ON [dbo].[CS_HPLASER_SUB_PERM_ITEMS]([DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_CS_HPLASER_SUB_PERM_ITEMS]
    ON [dbo].[CS_HPLASER_SUB_PERM_ITEMS]([VNESHID] ASC);

