CREATE TABLE [dbo].[CS_KITCONSUME_COMP] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [BOMID]   INT              NOT NULL,
    [SN]      NVARCHAR (50)    NOT NULL,
    [BATCHN]  NVARCHAR (100)   NULL,
    [QTY]     DECIMAL (20, 10) NOT NULL,
    [MODELID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CS_KITCONSUME_COMP_BOMID] FOREIGN KEY ([BOMID]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_CS_KITCONSUME_COMP_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[CS_KITCONSUME] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_CS_KITCONSUME_COMP]
    ON [dbo].[CS_KITCONSUME_COMP]([VNESHID] ASC);

