CREATE TABLE [dbo].[CS_KITCONSUME_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [CODE]    NVARCHAR (50)    NOT NULL,
    [BATCHN]  NVARCHAR (100)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CS_KITCONSUME_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[CS_KITCONSUME] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_CS_KITCONSUME_T]
    ON [dbo].[CS_KITCONSUME_T]([VNESHID] ASC);

