CREATE TABLE [dbo].[CS_SRV_PACKAGE_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [PARAMID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CS_SRV_PACKAGE_T_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_CS_SRV_PACKAGE_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[CS_SRV_PACKAGE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_CS_SRV_PACKAGE_T]
    ON [dbo].[CS_SRV_PACKAGE_T]([VNESHID] ASC);

