CREATE TABLE [dbo].[CS_SRV_PACKAGE_B] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [BOMID]   INT              NOT NULL,
    [PARAMID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CS_SRV_PACKAGE_B_BOMID] FOREIGN KEY ([BOMID]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_CS_SRV_PACKAGE_B_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_CS_SRV_PACKAGE_B_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[CS_SRV_PACKAGE] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [IX_CS_SRV_PACKAGE_B_1] UNIQUE NONCLUSTERED ([BOMID] ASC, [PARAMID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_CS_SRV_PACKAGE_B]
    ON [dbo].[CS_SRV_PACKAGE_B]([VNESHID] ASC);

