CREATE TABLE [dbo].[DA_CONCESSION_FINAL_NOTIFY] (
    [ID]      INT      IDENTITY (1, 1) NOT NULL,
    [S_CR]    INT      NOT NULL,
    [S_CDT]   DATETIME NOT NULL,
    [S_MR]    INT      NULL,
    [S_MDT]   DATETIME NULL,
    [ARC]     INT      NULL,
    [VNESHID] INT      NOT NULL,
    [EMPLID]  INT      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DA_CONCESSION_FINAL_NOTIFY_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_FINAL_NOTIFY_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[DA_CONCESSION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_DA_CONCESSION_FINAL_NOTIFY]
    ON [dbo].[DA_CONCESSION_FINAL_NOTIFY]([VNESHID] ASC);

