CREATE TABLE [dbo].[DA_CONCESSION_APPROVE_EMPL_DEPUTY] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NULL,
    [NOTIFY]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DA_CONCESSION_APPROVE_EMPL_DEPUTY_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_APPROVE_EMPL_DEPUTY_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[DA_CONCESSION_APPROVE_EMPL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_DA_CONCESSION_APPROVE_EMPL_DEPUTY]
    ON [dbo].[DA_CONCESSION_APPROVE_EMPL_DEPUTY]([VNESHID] ASC);

