CREATE TABLE [dbo].[DA_CONCESSION] (
    [ID]                      INT              IDENTITY (1, 1) NOT NULL,
    [GID]                     UNIQUEIDENTIFIER NOT NULL,
    [S_S]                     INT              NOT NULL,
    [S_CR]                    INT              NOT NULL,
    [S_CDT]                   DATETIME         NOT NULL,
    [S_MR]                    INT              NULL,
    [S_MDT]                   DATETIME         NULL,
    [ARC]                     INT              NULL,
    [NUMBER]                  NVARCHAR (20)    NULL,
    [DOCTYPE]                 INT              NOT NULL,
    [DEPID]                   INT              NULL,
    [REVID]                   INT              NULL,
    [CRETE_DATE]              DATETIME         NULL,
    [APPROVE_DATE]            DATETIME         NULL,
    [REJECT_DATE]             DATETIME         NULL,
    [PERM_VALID_TIME_PERIOD]  INT              NULL,
    [START_DATE]              DATE             NULL,
    [FINISH_DATE]             DATE             NULL,
    [PERM_VALID_LOT_QTY]      INT              NULL,
    [LOT_NUM]                 NTEXT            NULL,
    [TOTAL_QTY]               DECIMAL (18, 2)  NULL,
    [APPLICATION]             NTEXT            NULL,
    [STD_CONC_SER_PROD]       INT              NULL,
    [LTD_CONC_PROD_TEST_ONLY] INT              NULL,
    [ISSUEDID]                INT              NULL,
    [CHECKEDID]               INT              NULL,
    [RELEASEDID]              INT              NULL,
    [APPROVEDID]              INT              NULL,
    [MODELID]                 INT              NOT NULL,
    [REJECTREMARK]            NVARCHAR (250)   NULL,
    [MTYPENAME]               INT              NULL,
    [CHECKED_DT]              DATETIME         NULL,
    [RELEASED_DT]             DATETIME         NULL,
    [APPROVED_DT]             DATETIME         NULL,
    [REJECT_CANCEL_EMPLID]    INT              NULL,
    [REAL_CHECKEDID]          INT              NULL,
    [REAL_RELEASEDID]         INT              NULL,
    [REAL_APPROVEDID]         INT              NULL,
    [RESTARTED_COUNT]         INT              NULL,
    CONSTRAINT [PK__DA_CONCE__3214EC27A2CC5FC9] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DA_CONCESSION_APPROVEDID] FOREIGN KEY ([APPROVEDID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_CHECKEDID] FOREIGN KEY ([CHECKEDID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_ISSUEDID] FOREIGN KEY ([ISSUEDID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_REAL_APPROVEDID] FOREIGN KEY ([REAL_APPROVEDID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_REAL_CHECKEDID] FOREIGN KEY ([REAL_CHECKEDID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_REAL_RELEASEDID] FOREIGN KEY ([REAL_RELEASEDID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_REJECT_CANCEL_EMPLID] FOREIGN KEY ([REJECT_CANCEL_EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_RELEASEDID] FOREIGN KEY ([RELEASEDID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_DA_CONCESSION_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID])
);

