CREATE TABLE [dbo].[DEF_ASSEMBLY_FILES_BETA] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [ASSEMBLYOID] INT              NOT NULL,
    [FILENAME]    NVARCHAR (250)   NOT NULL,
    [FILEDATE]    DATETIME         NOT NULL,
    [FILESIZE]    INT              NULL,
    [FILEBLOB]    IMAGE            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_ASSEMBLY_FILES_BETA_DEF_ASSEMBLY_BETA] FOREIGN KEY ([ASSEMBLYOID]) REFERENCES [dbo].[DEF_ASSEMBLY_BETA] ([OID])
);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_ASSEMBLY_FILES_BETA]
    ON [dbo].[DEF_ASSEMBLY_FILES_BETA]([ASSEMBLYOID] ASC);

