CREATE TABLE [dbo].[DEF_SYSCONST] (
    [ID]       INT             IDENTITY (1, 1) NOT NULL,
    [LABEL]    NVARCHAR (100)  NOT NULL,
    [NAME]     NVARCHAR (200)  NOT NULL,
    [VALUESTR] NVARCHAR (200)  NULL,
    [VALUEINT] INT             NULL,
    [VALUEDEC] DECIMAL (18, 1) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_SYSCONST]
    ON [dbo].[DEF_SYSCONST]([LABEL] ASC);

