CREATE TABLE [dbo].[DEF_SETTINGS] (
    [ID]     INT            IDENTITY (1, 1) NOT NULL,
    [USERID] INT            NOT NULL,
    [LABEL]  NVARCHAR (256) NOT NULL,
    [VALUE]  SQL_VARIANT    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_SETTINGS]
    ON [dbo].[DEF_SETTINGS]([USERID] ASC, [LABEL] ASC);

