CREATE TABLE [dbo].[DEF_MODULES] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [OID]    INT              NOT NULL,
    [LABEL]  NVARCHAR (40)    NOT NULL,
    [NAME]   NVARCHAR (100)   NOT NULL,
    [REMARK] NTEXT            NULL,
    [GID]    UNIQUEIDENTIFIER NULL,
    [S_CR]   INT              NULL,
    [S_MR]   INT              NULL,
    [S_CDT]  DATETIME         NULL,
    [S_MDT]  DATETIME         NULL,
    CONSTRAINT [PK__DEF_MODU__3214EC277F60ED59] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_MODULES_1]
    ON [dbo].[DEF_MODULES]([LABEL] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_MODULES]
    ON [dbo].[DEF_MODULES]([OID] ASC);

