CREATE TABLE [dbo].[DEF_CLASS_METHODS] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [OID]                INT              NOT NULL,
    [CLASSOID]           INT              NOT NULL,
    [LABEL]              NVARCHAR (50)    NOT NULL,
    [NAME]               NVARCHAR (300)   NOT NULL,
    [S_FROM]             INT              NOT NULL,
    [S_TO]               INT              NULL,
    [SORTORDER]          INT              NULL,
    [GID]                UNIQUEIDENTIFIER NULL,
    [S_CR]               INT              NULL,
    [S_MR]               INT              NULL,
    [S_CDT]              DATETIME         NULL,
    [S_MDT]              DATETIME         NULL,
    [BACKICON]           INT              NULL,
    [MFORM]              INT              NULL,
    [VISIBLETYPE]        INT              NULL,
    [OPENDOCFROMLIST]    INT              NULL,
    [HILITEMETHOD]       INT              NULL,
    [GROUPMETHOD]        INT              NULL,
    [ADDCONFIRM]         INT              NULL,
    [REMARK]             NTEXT            NULL,
    [MOPTION]            NVARCHAR (100)   NULL,
    [DISABLED]           INT              NULL,
    [FAMARK]             NVARCHAR (50)    NULL,
    [PARENTOID]          INT              NULL,
    [PRN_FIELD]          NVARCHAR (50)    NULL,
    [PRN_VALUE]          NVARCHAR (20)    NULL,
    [MCOLOR]             INT              NULL,
    [ASKREMARK]          INT              NULL,
    [OPEROIDAFTER]       INT              NULL,
    [ONLYGROUP]          INT              NULL,
    [DISABLEADM]         INT              NULL,
    [ARC]                INT              NULL,
    [CUSTOMCONFIRM]      INT              NULL,
    [CUSTOMCONFIRMQUERY] INT              NULL,
    [MENUHK]             INT              NULL,
    [ASKCRE]             INT              NULL,
    [USERCHREQUIRED]     INT              NULL,
    [CUSTOMCANEXEC]      INT              NULL,
    [CUSTOMDNYEXEC]      INT              NULL,
    CONSTRAINT [PK_DEF_CLASS_METHODS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_CLASS_METHODS_CLASSOID] FOREIGN KEY ([CLASSOID]) REFERENCES [dbo].[DEF_CLASSES] ([OID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_DEF_CLASS_METHODS_CUSTOMCANEXEC] FOREIGN KEY ([CUSTOMCANEXEC]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_METHODS_CUSTOMCONFIRM] FOREIGN KEY ([CUSTOMCONFIRM]) REFERENCES [dbo].[DEF_OPERATION] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_METHODS_CUSTOMCONFIRMQUERY] FOREIGN KEY ([CUSTOMCONFIRMQUERY]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_METHODS_CUSTOMDNYEXEC] FOREIGN KEY ([CUSTOMDNYEXEC]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_METHODS_MFORM] FOREIGN KEY ([MFORM]) REFERENCES [dbo].[DEF_FORM] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_METHODS_ONLYGROUP] FOREIGN KEY ([ONLYGROUP]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_DEF_CLASS_METHODS_OPEROIDAFTER] FOREIGN KEY ([OPEROIDAFTER]) REFERENCES [dbo].[DEF_OPERATION] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_CLASS_METHODS]
    ON [dbo].[DEF_CLASS_METHODS]([OID] ASC) WITH (FILLFACTOR = 90);

