CREATE TABLE [dbo].[DEF_LASTVER_REPORTED] (
    [USERID] INT      NOT NULL,
    [VERID]  INT      NOT NULL,
    [RDATE]  DATETIME NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_LASTVER_REPORTED]
    ON [dbo].[DEF_LASTVER_REPORTED]([USERID] ASC);

