CREATE TABLE [dbo].[DEF_INTERFACE_T] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [INTERFACEOID]   INT              NOT NULL,
    [OID]            INT              NOT NULL,
    [PARENTOID]      INT              NULL,
    [CAPTION]        NVARCHAR (100)   NULL,
    [COMMAND]        NVARCHAR (400)   NULL,
    [POSORDER]       INT              NULL,
    [GID]            UNIQUEIDENTIFIER NULL,
    [S_CR]           INT              NULL,
    [S_MR]           INT              NULL,
    [S_CDT]          DATETIME         NULL,
    [S_MDT]          DATETIME         NULL,
    [WORKSPACEGROUP] NVARCHAR (100)   NULL,
    [WORKSPACECOUNT] INT              NULL,
    [ARC]            INT              NULL,
    [ONLY4GROUP]     INT              NULL,
    [ONLYIFQUERY]    INT              NULL,
    [CLASSOID]       INT              NULL,
    [REPORTOID]      INT              NULL,
    [OPEROID]        INT              NULL,
    [OPTIONS]        NVARCHAR (400)   NULL,
    [VIEWOID]        INT              NULL,
    [SHORTCUT]       NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_INTERFACE_T_CLASSOID] FOREIGN KEY ([CLASSOID]) REFERENCES [dbo].[DEF_CLASSES] ([OID]),
    CONSTRAINT [FK_DEF_INTERFACE_T_INTERFACEOID] FOREIGN KEY ([INTERFACEOID]) REFERENCES [dbo].[DEF_INTERFACE] ([OID]) ON DELETE CASCADE,
    CONSTRAINT [FK_DEF_INTERFACE_T_ONLYIFQUERY] FOREIGN KEY ([ONLYIFQUERY]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_INTERFACE_T_OPEROID] FOREIGN KEY ([OPEROID]) REFERENCES [dbo].[DEF_OPERATION] ([OID]),
    CONSTRAINT [FK_DEF_INTERFACE_T_REPORTOID] FOREIGN KEY ([REPORTOID]) REFERENCES [dbo].[DEF_REPORTS] ([OID]),
    CONSTRAINT [FK_DEF_INTERFACE_T_VIEWOID] FOREIGN KEY ([VIEWOID]) REFERENCES [dbo].[DEF_VIEWS] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_INTERFACE_T]
    ON [dbo].[DEF_INTERFACE_T]([OID] ASC) WITH (FILLFACTOR = 90);

