CREATE TABLE [dbo].[DEF_CLASS_ENVS] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [OID]              INT              NOT NULL,
    [CLASSOID]         INT              NOT NULL,
    [ONLYSTATE]        INT              NULL,
    [ENVTYPE]          INT              NOT NULL,
    [TOCLASSOID]       INT              NULL,
    [TOREPORTOID]      INT              NULL,
    [TOVIEWOID]        INT              NULL,
    [ENVOPTION]        NVARCHAR (150)   NULL,
    [NAME]             NVARCHAR (150)   NOT NULL,
    [SORTORDER]        INT              NULL,
    [VISIBLETYPE]      INT              NOT NULL,
    [TOOPERATIONOID]   INT              NULL,
    [TOUNITOID]        INT              NULL,
    [GID]              UNIQUEIDENTIFIER NULL,
    [S_CR]             INT              NULL,
    [S_MR]             INT              NULL,
    [S_CDT]            DATETIME         NULL,
    [S_MDT]            DATETIME         NULL,
    [TOSQLOID]         INT              NULL,
    [TOFORMOID]        INT              NULL,
    [ARC]              INT              NULL,
    [ONLYGROUP]        INT              NULL,
    [FAMARK]           NVARCHAR (50)    NULL,
    [EXCEPTGROUP]      INT              NULL,
    [ONLYIFQUERYOID]   INT              NULL,
    [DISABLED]         INT              NULL,
    [ONLYIFEXPRESSION] NVARCHAR (250)   NULL,
    CONSTRAINT [PK_DEF_CLASS_ENV] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_CLASS_ENVS_CLASSOID] FOREIGN KEY ([CLASSOID]) REFERENCES [dbo].[DEF_CLASSES] ([OID]) ON DELETE CASCADE,
    CONSTRAINT [FK_DEF_CLASS_ENVS_EXCEPTGROUP] FOREIGN KEY ([EXCEPTGROUP]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_ONLYGROUP] FOREIGN KEY ([ONLYGROUP]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_ONLYIFQUERYOID] FOREIGN KEY ([ONLYIFQUERYOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_TOCLASSOID] FOREIGN KEY ([TOCLASSOID]) REFERENCES [dbo].[DEF_CLASSES] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_TOFORMOID] FOREIGN KEY ([TOFORMOID]) REFERENCES [dbo].[DEF_FORM] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_TOOPERATIONOID] FOREIGN KEY ([TOOPERATIONOID]) REFERENCES [dbo].[DEF_OPERATION] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_TOREPORTOID] FOREIGN KEY ([TOREPORTOID]) REFERENCES [dbo].[DEF_REPORTS] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_TOSQLOID] FOREIGN KEY ([TOSQLOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_TOUNITOID] FOREIGN KEY ([TOUNITOID]) REFERENCES [dbo].[DEF_UNIT] ([OID]),
    CONSTRAINT [FK_DEF_CLASS_ENVS_TOVIEWOID] FOREIGN KEY ([TOVIEWOID]) REFERENCES [dbo].[DEF_VIEWS] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_CLASS_ENVS_OID]
    ON [dbo].[DEF_CLASS_ENVS]([OID] ASC);

