CREATE TABLE [dbo].[DEF_PLUGIN_FILES] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [PLUGINID] INT              NOT NULL,
    [FILENAME] NVARCHAR (250)   NOT NULL,
    [FILEDATE] DATETIME         NOT NULL,
    [FILESIZE] INT              NULL,
    [FILEBLOB] IMAGE            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_PLUGIN_FILES_PLUGINID] FOREIGN KEY ([PLUGINID]) REFERENCES [dbo].[DEF_PLUGINS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_PLUGIN_FILES]
    ON [dbo].[DEF_PLUGIN_FILES]([PLUGINID] ASC);

