CREATE TABLE [dbo].[DEF_ENUMERATION] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [OID]       INT              NOT NULL,
    [LABEL]     NVARCHAR (40)    NOT NULL,
    [MODULEOID] INT              NOT NULL,
    [NAME]      NVARCHAR (100)   NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NULL,
    [S_MR]      INT              NULL,
    [S_CDT]     DATETIME         NULL,
    [S_MDT]     DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_DEF_ENUMERATION_MODULEOID] FOREIGN KEY ([MODULEOID]) REFERENCES [dbo].[DEF_MODULES] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_ENUMERATION_1]
    ON [dbo].[DEF_ENUMERATION]([LABEL] ASC) WITH (FILLFACTOR = 90);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_ENUMERATION]
    ON [dbo].[DEF_ENUMERATION]([OID] ASC) WITH (FILLFACTOR = 90);

