CREATE TABLE [dbo].[DEF_USERSTOGROUP] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [USERID]  INT              NOT NULL,
    [GROUPID] INT              NOT NULL,
    [DCLS]    DATE             NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NULL,
    [S_MR]    INT              NULL,
    [S_CDT]   DATETIME         NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [REMARK]  NVARCHAR (500)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_USERSTOGROUP_GROUPID] FOREIGN KEY ([GROUPID]) REFERENCES [dbo].[DEF_USERS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_USERSTOGROUP3]
    ON [dbo].[DEF_USERSTOGROUP]([USERID] ASC, [GROUPID] ASC, [DCLS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_USERSTOGROUP2]
    ON [dbo].[DEF_USERSTOGROUP]([GROUPID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_USERSTOGROUP]
    ON [dbo].[DEF_USERSTOGROUP]([USERID] ASC, [DCLS] ASC) WITH (FILLFACTOR = 90);

