CREATE TABLE [dbo].[DEF_CONSTRMESS] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [OID]          INT              NOT NULL,
    [MODULEOID]    INT              NOT NULL,
    [LABEL]        NVARCHAR (50)    NOT NULL,
    [NAME]         NVARCHAR (100)   NOT NULL,
    [TEXT]         NVARCHAR (200)   NOT NULL,
    [ERRFIELD]     NVARCHAR (50)    NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NULL,
    [S_MR]         INT              NULL,
    [S_CDT]        DATETIME         NULL,
    [S_MDT]        DATETIME         NULL,
    [DECODEKEYS]   NVARCHAR (200)   NULL,
    [EXPLTEXTQOID] INT              NULL,
    CONSTRAINT [PK_DEF_CONSTRMESS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_CONSTRMESS_EXPLTEXTQOID] FOREIGN KEY ([EXPLTEXTQOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_CONSTRMESS_MODULEOID] FOREIGN KEY ([MODULEOID]) REFERENCES [dbo].[DEF_MODULES] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_CONSTRMESS_2]
    ON [dbo].[DEF_CONSTRMESS]([NAME] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_CONSTRMESS_1]
    ON [dbo].[DEF_CONSTRMESS]([LABEL] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_CONSTRMESS]
    ON [dbo].[DEF_CONSTRMESS]([OID] ASC);

