CREATE TABLE [dbo].[DEF_UPDATES_SYNC] (
    [USERID]   INT      NOT NULL,
    [UPDATEID] INT      NOT NULL,
    [DD]       DATETIME NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_UPDATES_SYNC]
    ON [dbo].[DEF_UPDATES_SYNC]([USERID] ASC, [UPDATEID] ASC, [DD] ASC);

