CREATE TABLE [dbo].[DEF_QRY_CUSTOM_COLUMN] (
    [ID]                BIGINT IDENTITY (1, 1) NOT NULL,
    [QUERY]             INT    NOT NULL,
    [USERID]            INT    NOT NULL,
    [PAGE]              INT    NOT NULL,
    [MODELTYPEPARAM]    INT    NULL,
    [MODELTYPEBOM]      INT    NULL,
    [MODELTYPEOPTGROUP] INT    NULL,
    [CLASS]             INT    NULL,
    [VIEW]              INT    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_QRY_CUSTOM_COLUMN_MDLTYPEBOM] FOREIGN KEY ([MODELTYPEBOM]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_DEF_QRY_CUSTOM_COLUMN_MDLTYPEOPTGROUP] FOREIGN KEY ([MODELTYPEOPTGROUP]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_DEF_QRY_CUSTOM_COLUMN_MDLTYPEPARAM] FOREIGN KEY ([MODELTYPEPARAM]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_DEF_QRY_CUSTOM_COLUMN_QUERY] FOREIGN KEY ([QUERY]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_QRY_CUSTOM_COLUMN_USERID] FOREIGN KEY ([USERID]) REFERENCES [dbo].[DEF_USERS] ([ID])
);

