CREATE TABLE [dbo].[DEF_USERSTOINTERFACE] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [USERID]       INT              NOT NULL,
    [INTERFACEOID] INT              NOT NULL,
    [DEND]         DATETIME         NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NULL,
    [S_MR]         INT              NULL,
    [S_CDT]        DATETIME         NULL,
    [S_MDT]        DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_USERSTOINTERFACE_INTERFACEOID] FOREIGN KEY ([INTERFACEOID]) REFERENCES [dbo].[DEF_INTERFACE] ([OID]),
    CONSTRAINT [FK_DEF_USERSTOINTERFACE_USERID] FOREIGN KEY ([USERID]) REFERENCES [dbo].[DEF_USERS] ([ID]) ON DELETE CASCADE
);

