CREATE TABLE [dbo].[DEF_VARS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [OID]       INT              NOT NULL,
    [LABEL]     NVARCHAR (50)    NOT NULL,
    [MODULEOID] INT              NOT NULL,
    [NAME]      NVARCHAR (150)   NOT NULL,
    [VARTYPE]   INT              NOT NULL,
    [STORETYPE] INT              NOT NULL,
    [ENUMOID]   INT              NULL,
    [CLASSOID]  INT              NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NULL,
    [S_MR]      INT              NULL,
    [S_CDT]     DATETIME         NULL,
    [S_MDT]     DATETIME         NULL,
    CONSTRAINT [PK_DEF_VARS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_VARS_CLASSOID] FOREIGN KEY ([CLASSOID]) REFERENCES [dbo].[DEF_CLASSES] ([OID]),
    CONSTRAINT [FK_DEF_VARS_ENUMOID] FOREIGN KEY ([ENUMOID]) REFERENCES [dbo].[DEF_ENUMERATION] ([OID]),
    CONSTRAINT [FK_DEF_VARS_MODULEOID] FOREIGN KEY ([MODULEOID]) REFERENCES [dbo].[DEF_MODULES] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_VARS_OID]
    ON [dbo].[DEF_VARS]([OID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_VARS_LABEL]
    ON [dbo].[DEF_VARS]([LABEL] ASC);

