CREATE TABLE [dbo].[DEF_VIEWS] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [OID]              INT              NOT NULL,
    [LABEL]            NVARCHAR (256)   NOT NULL,
    [MODULEOID]        INT              NOT NULL,
    [NAME]             NVARCHAR (2048)  NOT NULL,
    [GID]              UNIQUEIDENTIFIER NULL,
    [S_CR]             INT              NULL,
    [S_MR]             INT              NULL,
    [S_CDT]            DATETIME         NULL,
    [S_MDT]            DATETIME         NULL,
    [GROUPBYFIELDS]    NVARCHAR (100)   NULL,
    [SQLFILTER]        NVARCHAR (500)   NULL,
    [CHPERIOD]         INT              NULL,
    [ARC]              INT              NULL,
    [ORDBYFIELDS]      NVARCHAR (500)   NULL,
    [CHPERIODFIELD]    NVARCHAR (100)   NULL,
    [REAMARK]          NTEXT            NULL,
    [PREVIEWFIELD]     NVARCHAR (100)   NULL,
    [TAGSFIELD]        NVARCHAR (50)    NULL,
    [SQLTEXT]          NTEXT            NULL,
    [HIDEFIELDS]       NVARCHAR (400)   NULL,
    [SHOWFIELDS]       NVARCHAR (400)   NULL,
    [INITFIND]         NVARCHAR (50)    NULL,
    [INITFINDDBALIAS]  NVARCHAR (50)    NULL,
    [CLASSOID]         INT              NULL,
    [DISABLESORT]      INT              NULL,
    [DISABLESORTQOID]  INT              NULL,
    [ADDCOLUMNSQOID]   INT              NULL,
    [OPTIONS]          NVARCHAR (500)   NULL,
    [LISTREDCOLUMNS]   NVARCHAR (200)   NULL,
    [LISTSUMMARY]      NVARCHAR (200)   NULL,
    [FOLDERSQOID]      INT              NULL,
    [RCLASSSQLFILTER]  NVARCHAR (2048)  NULL,
    [ONLY4GROUP]       INT              NULL,
    [INITFINDADDQOID]  INT              NULL,
    [COLUMNSHINTSQOID] INT              NULL,
    [RENTITYSQLFILTER] NVARCHAR (2048)  NULL,
    [CHPERIODCUSTOM]   INT              NULL,
    [REPLACEFINDQOID]  INT              NULL,
    [SQLCLAUSEOPTION]  NVARCHAR (512)   NULL,
    CONSTRAINT [PK_DEF_VIEWS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_VIEWS_ADDCOLUMNSQUERYOID] FOREIGN KEY ([ADDCOLUMNSQOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_VIEWS_CLASSOID] FOREIGN KEY ([CLASSOID]) REFERENCES [dbo].[DEF_CLASSES] ([OID]),
    CONSTRAINT [FK_DEF_VIEWS_COLUMNSHINTSQOID] FOREIGN KEY ([COLUMNSHINTSQOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_VIEWS_DISABLESORTQOID] FOREIGN KEY ([DISABLESORTQOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_VIEWS_INITFINDADDQOID] FOREIGN KEY ([INITFINDADDQOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_DEF_VIEWS_MODULEOID] FOREIGN KEY ([MODULEOID]) REFERENCES [dbo].[DEF_MODULES] ([OID]),
    CONSTRAINT [FK_DEF_VIEWS_ONLY4GROUP] FOREIGN KEY ([ONLY4GROUP]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_DEF_VIEWS_REPLACEFINDQOID] FOREIGN KEY ([REPLACEFINDQOID]) REFERENCES [dbo].[DEF_SQL] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_VIEWS_1]
    ON [dbo].[DEF_VIEWS]([LABEL] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_VIEWS]
    ON [dbo].[DEF_VIEWS]([OID] ASC);

