CREATE TABLE [dbo].[DEF_INTERFACE_W] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [INTERFACEOID] INT              NOT NULL,
    [OPTIONS]      NVARCHAR (400)   NULL,
    [WIDGETOID]    INT              NOT NULL,
    [POSORDER]     INT              NULL,
    [OID]          INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_INTERFACE_W_INTERFACEOID] FOREIGN KEY ([INTERFACEOID]) REFERENCES [dbo].[DEF_INTERFACE] ([OID]) ON DELETE CASCADE,
    CONSTRAINT [FK_DEF_INTERFACE_W_WIDGETOID] FOREIGN KEY ([WIDGETOID]) REFERENCES [dbo].[DEF_WIDGETS] ([OID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_INTERFACE_W_OID]
    ON [dbo].[DEF_INTERFACE_W]([OID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_INTERFACE_W]
    ON [dbo].[DEF_INTERFACE_W]([INTERFACEOID] ASC);

