CREATE TABLE [dbo].[DEF_ENUMERATION_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [ENUMOID]  INT              NOT NULL,
    [CODE]     INT              NOT NULL,
    [NAME]     NVARCHAR (350)   NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NULL,
    [S_MR]     INT              NULL,
    [S_CDT]    DATETIME         NULL,
    [S_MDT]    DATETIME         NULL,
    [ENUMPICT] IMAGE            NULL,
    [ARC]      INT              NULL,
    [OID]      INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DEF_ENUMERATION_T_ENUMOID] FOREIGN KEY ([ENUMOID]) REFERENCES [dbo].[DEF_ENUMERATION] ([OID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEF_ENUMERATION_T_OID]
    ON [dbo].[DEF_ENUMERATION_T]([OID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DEF_ENUMERATION_T]
    ON [dbo].[DEF_ENUMERATION_T]([ENUMOID] ASC);

