CREATE TABLE [dbo].[EQ_ADD_MTID_LINKS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [DEPID]    INT              NOT NULL,
    [EQTYPEID] INT              NOT NULL,
    [MTID]     INT              NOT NULL,
    [REMARK]   NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_ADD_MTID_LINKS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_EQ_ADD_MTID_LINKS_EQTYPEID] FOREIGN KEY ([EQTYPEID]) REFERENCES [dbo].[EQ_TYPES] ([ID]),
    CONSTRAINT [FK_EQ_ADD_MTID_LINKS_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_ADD_MTID_LINKS_UNIQ1]
    ON [dbo].[EQ_ADD_MTID_LINKS]([EQTYPEID] ASC, [MTID] ASC);

