CREATE TABLE [dbo].[EQ_CHANGEDEP_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EQID]    INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_CHANGEDEP_T_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_EQ_CHANGEDEP_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[EQ_CHANGEDEP] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_CHANGEDEP_T]
    ON [dbo].[EQ_CHANGEDEP_T]([VNESHID] ASC);

