CREATE TABLE [dbo].[EQ_DEP_SHARED_EQUIPMENT_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [DEPEQID] INT              NOT NULL,
    [EQID]    INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_DEP_SHARED_EQUIPMENT_T_DEPEQID] FOREIGN KEY ([DEPEQID]) REFERENCES [dbo].[EQ_DEP_SHARED_EQUIPMENT] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_EQ_DEP_SHARED_EQUIPMENT_T_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_DEP_SHARED_EQUIPMENT_T_1]
    ON [dbo].[EQ_DEP_SHARED_EQUIPMENT_T]([DEPEQID] ASC, [EQID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_DEP_SHARED_EQUIPMENT_T]
    ON [dbo].[EQ_DEP_SHARED_EQUIPMENT_T]([DEPEQID] ASC);

