CREATE TABLE [dbo].[EQ_DEP_SHARED_EQUIPMENT] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NOT NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [DEPID_FROM] INT              NULL,
    [DEPID_TO]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_DEP_SHARED_EQUIPMENT_DEPID_FROM] FOREIGN KEY ([DEPID_FROM]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_EQ_DEP_SHARED_EQUIPMENT_DEPID_TO] FOREIGN KEY ([DEPID_TO]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_DEP_SHARED_EQUIPMENT]
    ON [dbo].[EQ_DEP_SHARED_EQUIPMENT]([DEPID_FROM] ASC, [DEPID_TO] ASC);

