CREATE TABLE [dbo].[EQ_EQUIPMENT] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_S]           INT              NOT NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [DEPID]         INT              NOT NULL,
    [SN]            NVARCHAR (100)   NOT NULL,
    [EQMODELID]     INT              NOT NULL,
    [PDATE]         DATETIME         NULL,
    [WEND]          DATETIME         NULL,
    [REMARK]        NTEXT            NULL,
    [RESP_EMPLID]   INT              NULL,
    [TAGN]          NVARCHAR (100)   NULL,
    [SHAREMODE]     INT              NULL,
    [WROFF_DATE]    DATETIME         NULL,
    [WROFF_REMARK]  NTEXT            NULL,
    [REFSAMPLE]     INT              NULL,
    [WORKINKPLACE]  NVARCHAR (50)    NULL,
    [PONUMBER]      NVARCHAR (20)    NULL,
    [VENDORID]      INT              NULL,
    [VDE07010702]   NVARCHAR (100)   NULL,
    [SIZE_RANGE]    DECIMAL (18, 4)  NULL,
    [NOUNIQUECHECK] INT              NULL,
    [KB3146_RANGE]  NVARCHAR (150)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_EQUIPMENT_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_EQ_EQUIPMENT_EQMODELID2] FOREIGN KEY ([EQMODELID]) REFERENCES [dbo].[EQ_MODELS] ([ID]),
    CONSTRAINT [FK_EQ_EQUIPMENT_RESP_EMPLID] FOREIGN KEY ([RESP_EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_EQ_EQUIPMENT_VENDORID] FOREIGN KEY ([VENDORID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_EQUIPMENT_MODEL_SN_UNIQUE2]
    ON [dbo].[EQ_EQUIPMENT]([EQMODELID] ASC, [SN] ASC, [NOUNIQUECHECK] ASC) WHERE ([SN]<>'N/A');


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_EQUIPMENT_MODEL_SN_UNIQUE]
    ON [dbo].[EQ_EQUIPMENT]([EQMODELID] ASC, [SN] ASC) WHERE ([ID]>(3584));


GO
CREATE NONCLUSTERED INDEX [IX_EQ_EQUIPMENT_MODEL_SN]
    ON [dbo].[EQ_EQUIPMENT]([EQMODELID] ASC, [SN] ASC);

