CREATE TABLE [dbo].[EQ_EQUIPMENT_LINKED] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [LINKED_EQID] INT              NOT NULL,
    [LINKDBEG]    DATE             NULL,
    [LINKDEND]    DATE             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_EQUIPMENT_LINKED_LINKED_EQID] FOREIGN KEY ([LINKED_EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_EQ_EQUIPMENT_LINKED_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_EQUIPMENT_LINKED]
    ON [dbo].[EQ_EQUIPMENT_LINKED]([VNESHID] ASC);

