CREATE TABLE [dbo].[EQ_EQUIPMENT_LIKS_HISTORY] (
    [ID]      INT      IDENTITY (1, 1) NOT NULL,
    [DD]      DATETIME NOT NULL,
    [USERID]  INT      NOT NULL,
    [EQID]    INT      NOT NULL,
    [LACTION] INT      NOT NULL,
    [TO_EQID] INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_EQUIPMENT_LIKS_HISTORY_2]
    ON [dbo].[EQ_EQUIPMENT_LIKS_HISTORY]([TO_EQID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_EQUIPMENT_LIKS_HISTORY_1]
    ON [dbo].[EQ_EQUIPMENT_LIKS_HISTORY]([EQID] ASC);

