CREATE TABLE [dbo].[EQ_LOGEVENTS] (
    [ID]    INT              IDENTITY (1, 1) NOT NULL,
    [GID]   UNIQUEIDENTIFIER NULL,
    [S_CR]  INT              NOT NULL,
    [S_CDT] DATETIME         NOT NULL,
    [S_MR]  INT              NULL,
    [S_MDT] DATETIME         NULL,
    [EQID]  INT              NOT NULL,
    [DD]    DATETIME         NOT NULL,
    [NAME]  NVARCHAR (250)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_LOGEVENTS_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_LOGEVENTS]
    ON [dbo].[EQ_LOGEVENTS]([EQID] ASC);

