CREATE TABLE [dbo].[EQ_MODELS] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [CODE]         NVARCHAR (100)   NOT NULL,
    [MANUFACTURER] INT              NOT NULL,
    [REMARK]       NTEXT            NULL,
    [EQTYPEID]     INT              NOT NULL,
    [EQPICT]       IMAGE            NULL,
    [DEPID]        INT              NOT NULL,
    [NAVCODE]      NVARCHAR (16)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_MODELS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_EQ_MODELS_EQTYPEID2] FOREIGN KEY ([EQTYPEID]) REFERENCES [dbo].[EQ_TYPES] ([ID]),
    CONSTRAINT [FK_EQ_MODELS_MANUFACTURER2] FOREIGN KEY ([MANUFACTURER]) REFERENCES [dbo].[EQ_MANUFACTURER] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_MODELS_NAVCODE]
    ON [dbo].[EQ_MODELS]([NAVCODE] ASC) WHERE ([NAVCODE] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_MODELS_CODE]
    ON [dbo].[EQ_MODELS]([DEPID] ASC, [CODE] ASC);

