CREATE TABLE [dbo].[EQ_MODEL_PARAMS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [PARAMID] INT              NOT NULL,
    [PVALUE]  SQL_VARIANT      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_MODEL_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_EQ_MODEL_PARAMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[EQ_MODELS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_MODEL_PARAMS_VNESHID_PARAMID]
    ON [dbo].[EQ_MODEL_PARAMS]([VNESHID] ASC, [PARAMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_MODEL_PARAMS]
    ON [dbo].[EQ_MODEL_PARAMS]([VNESHID] ASC);

