CREATE TABLE [dbo].[EQ_OPERATION_PARAMS] (
    [ID]      INT         IDENTITY (1, 1) NOT NULL,
    [S_CR]    INT         NULL,
    [S_CDT]   DATETIME    NULL,
    [S_MR]    INT         NULL,
    [S_MDT]   DATETIME    NULL,
    [EQID]    INT         NOT NULL,
    [OPERID]  INT         NOT NULL,
    [PARAMID] INT         NOT NULL,
    [PVALUE]  SQL_VARIANT NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_EQ_OPERATION_PARAMS_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_EQ_OPERATION_PARAMS_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_EQ_OPERATION_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_OPERATION_PARAMS_PARAMID]
    ON [dbo].[EQ_OPERATION_PARAMS]([PARAMID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_EQ_OPERATION_PARAMS_OPERID_EQID_PARAMID]
    ON [dbo].[EQ_OPERATION_PARAMS]([EQID] ASC, [OPERID] ASC, [PARAMID] ASC)
    INCLUDE([PVALUE]);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_OPERATION_PARAMS_OPERID]
    ON [dbo].[EQ_OPERATION_PARAMS]([OPERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_EQ_OPERATION_PARAMS_EQID]
    ON [dbo].[EQ_OPERATION_PARAMS]([EQID] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Operation Equipment Parameters', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'EQ_OPERATION_PARAMS';

