CREATE TABLE [dbo].[FC_8D_REPORT] (
    [ID]                      INT              IDENTITY (1, 1) NOT NULL,
    [GID]                     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]                    INT              NOT NULL,
    [S_CDT]                   DATETIME         NOT NULL,
    [S_MR]                    INT              NULL,
    [S_MDT]                   DATETIME         NULL,
    [ARC]                     INT              NULL,
    [FRID]                    INT              NULL,
    [COMPLAINTNUM]            NVARCHAR (250)   NULL,
    [DEPARTMENT]              NVARCHAR (250)   NULL,
    [FAILED_PART]             NVARCHAR (250)   NULL,
    [PART_NUMBER]             NVARCHAR (250)   NULL,
    [PART_SN]                 NVARCHAR (250)   NULL,
    [TEAMLEADER]              INT              NULL,
    [NN]                      NVARCHAR (50)    NULL,
    [IMPL_DATE]               NVARCHAR (100)   NULL,
    [PERC_IN_PROBLEM]         NVARCHAR (100)   NULL,
    [FIRST_OCC_DEFECT]        INT              NULL,
    [REPET_DEFECT]            INT              NULL,
    [VERIF_CHECK]             NVARCHAR (100)   NULL,
    [IMPL_CORR_DATE]          NVARCHAR (100)   NULL,
    [PREV_RECURRENCE_DATE]    NVARCHAR (100)   NULL,
    [CLOSING_DATE]            DATE             NULL,
    [S_S]                     INT              NOT NULL,
    [SIGN_AUTHOR]             INT              NULL,
    [FAILURE_DESCRIPTION]     NTEXT            NULL,
    [CONTAINMENT_ACTIONS]     NTEXT            NULL,
    [ROOT_CAUSES]             NTEXT            NULL,
    [CHOSEN_CORR_ACTIONS]     NTEXT            NULL,
    [IMPL_CORR_ACTIONS]       NTEXT            NULL,
    [PREV_RECURRENCE_ACTIONS] NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_8D_REPORT_SIGN_AUTHOR] FOREIGN KEY ([SIGN_AUTHOR]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_FC_8D_REPORT_TEAMLEADER] FOREIGN KEY ([TEAMLEADER]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);

