CREATE TABLE [dbo].[FC_CLOSE_FAR] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [DEPID]      INT              NOT NULL,
    [NOANALYSIS] INT              NOT NULL,
    [PARAMDEPID] INT              NULL,
    [PARAMMTID]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_CLOSE_FAR_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_CLOSE_FAR_PARAMDEPID] FOREIGN KEY ([PARAMDEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_CLOSE_FAR_PARAMMTID] FOREIGN KEY ([PARAMMTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_CLOSE_FAR]
    ON [dbo].[FC_CLOSE_FAR]([DEPID] ASC, [NOANALYSIS] ASC);

