CREATE TABLE [dbo].[FC_CORRACTIONS_TEAM] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [EMPLID]   INT              NOT NULL,
    [TEAMROLE] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_CORRACTIONS_TEAM_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_FC_CORRACTIONS_TEAM_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_CORRACTIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_CORRACTIONS_TEAM]
    ON [dbo].[FC_CORRACTIONS_TEAM]([VNESHID] ASC);

