CREATE TABLE [dbo].[FC_DEPSHARING_MODELS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [MODELID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_DEPSHARING_MODELS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_DEPSHARING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_DEPSHARING_MODELS]
    ON [dbo].[FC_DEPSHARING_MODELS]([VNESHID] ASC);

