CREATE TABLE [dbo].[FC_DEPSHARING] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [DEPID]        INT              NOT NULL,
    [ALLOW2DEPID]  INT              NOT NULL,
    [PRINTDEP]     INT              NULL,
    [ONLYMTID]     INT              NULL,
    [ALLOW2EMPLID] INT              NULL,
    [REMARK]       NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_DEPSHARING_ALLOW2DEPID] FOREIGN KEY ([ALLOW2DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_DEPSHARING_ALLOW2EMPLID] FOREIGN KEY ([ALLOW2EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_FC_DEPSHARING_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_DEPSHARING_ONLYMTID] FOREIGN KEY ([ONLYMTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_DEPSHARING]
    ON [dbo].[FC_DEPSHARING]([ALLOW2DEPID] ASC)
    INCLUDE([DEPID], [ALLOW2EMPLID]);

