CREATE TABLE [dbo].[FC_EXT_FAR_ACCESS_OPTIONS] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NOT NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [ACCESSID]      INT              NOT NULL,
    [EMPLOYEEID]    INT              NOT NULL,
    [ACCESS_OPTION] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_EXT_FAR_ACCESS_OPTIONS_ACCESSID] FOREIGN KEY ([ACCESSID]) REFERENCES [dbo].[FC_EXT_FAR_ACCESS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_FC_EXT_FAR_ACCESS_OPTIONS_EMPLOYEEID] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_EXT_FAR_ACCESS_OPTIONS]
    ON [dbo].[FC_EXT_FAR_ACCESS_OPTIONS]([ACCESSID] ASC);

