CREATE TABLE [dbo].[FC_FA_APPROVE_SUBSCRIPTION_D] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [VNESHID]      INT              NOT NULL,
    [DEPARTMENTID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FA_APPROVE_SUBSCRIPTION_D_DEPARTMENTID] FOREIGN KEY ([DEPARTMENTID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_FA_APPROVE_SUBSCRIPTION_D_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_FA_APPROVE_SUBSCRIPTION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [IX_FC_FA_APPROVE_SUBSCRIPTION_D_1] UNIQUE NONCLUSTERED ([VNESHID] ASC, [DEPARTMENTID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FA_APPROVE_SUBSCRIPTION_D]
    ON [dbo].[FC_FA_APPROVE_SUBSCRIPTION_D]([VNESHID] ASC);

