CREATE TABLE [dbo].[FC_FAILUREPARAMS_SHARING] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [DEPID]   INT              NOT NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FAILUREPARAMS_SHARING_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_FAILUREPARAMS_SHARING_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_FAILUREPARAMS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_FAILUREPARAMS_SHARING_UNIQ]
    ON [dbo].[FC_FAILUREPARAMS_SHARING]([DEPID] ASC, [VNESHID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FAILUREPARAMS_SHARING]
    ON [dbo].[FC_FAILUREPARAMS_SHARING]([VNESHID] ASC);

