CREATE TABLE [dbo].[FC_FAILURERATES_FARS_MT] (
    [FYEAR]              INT             NOT NULL,
    [FMONTH]             INT             NOT NULL,
    [MTID]               INT             NOT NULL,
    [FACODE]             INT             NULL,
    [FCOUNT]             DECIMAL (14, 4) NULL,
    [FRATE]              DECIMAL (14, 2) NULL,
    [PRODUCED_COUNT]     DECIMAL (14, 4) NULL,
    [ALLFCOUNT]          DECIMAL (14, 4) NULL,
    [FRATE_2ALLFAILURES] DECIMAL (14, 2) NULL,
    [FCOUNT_INT]         DECIMAL (14, 4) NULL,
    [FCOUNT_EXT]         DECIMAL (14, 4) NULL,
    [ID]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FAILURERATES_FARS_MT_2_FACODE] FOREIGN KEY ([FACODE]) REFERENCES [dbo].[FC_FAILUREANALYSISCODES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FAILURERATES_FARS_MT_2]
    ON [dbo].[FC_FAILURERATES_FARS_MT]([FYEAR] ASC, [FMONTH] ASC)
    INCLUDE([FACODE], [FCOUNT], [PRODUCED_COUNT], [ALLFCOUNT], [FCOUNT_INT], [FCOUNT_EXT]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_FAILURERATES_FARS_MT]
    ON [dbo].[FC_FAILURERATES_FARS_MT]([FYEAR] ASC, [FMONTH] ASC, [MTID] ASC, [FACODE] ASC);

