CREATE TABLE [dbo].[FC_FAILUREANALYSISCODES_MT] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GID]    UNIQUEIDENTIFIER NOT NULL,
    [S_CR]   INT              NOT NULL,
    [S_CDT]  DATETIME         NOT NULL,
    [S_MR]   INT              NULL,
    [S_MDT]  DATETIME         NULL,
    [ARC]    INT              NULL,
    [CODEID] INT              NOT NULL,
    [MTID]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FAILUREANALYSISCODES_MT_CODEID] FOREIGN KEY ([CODEID]) REFERENCES [dbo].[FC_FAILUREANALYSISCODES] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_FC_FAILUREANALYSISCODES_MT_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FAILUREANALYSISCODES_MT]
    ON [dbo].[FC_FAILUREANALYSISCODES_MT]([CODEID] ASC);

