CREATE TABLE [dbo].[FC_FAILURERATES_RECALCDATES] (
    [YY] INT NOT NULL,
    [MM] INT NOT NULL,
    [DD] INT NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_FAILURERATES_RECALCDATES]
    ON [dbo].[FC_FAILURERATES_RECALCDATES]([YY] ASC, [MM] ASC, [DD] ASC);

