CREATE TABLE [dbo].[FC_FA_APPROVE_SUBSCRIPTION_P] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [VNESHID]    INT              NOT NULL,
    [EMPLOYEEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FA_APPROVE_SUBSCRIPTION_P_EMPLOYEEID] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_FC_FA_APPROVE_SUBSCRIPTION_P_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_FA_APPROVE_SUBSCRIPTION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [IX_FC_FA_APPROVE_SUBSCRIPTION_P_1] UNIQUE NONCLUSTERED ([VNESHID] ASC, [EMPLOYEEID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FA_APPROVE_SUBSCRIPTION_P]
    ON [dbo].[FC_FA_APPROVE_SUBSCRIPTION_P]([VNESHID] ASC);

