CREATE TABLE [dbo].[FC_FAILUREANALYSISCODES_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [CUSTID]   INT              NOT NULL,
    [EXT_NAME] NVARCHAR (200)   NOT NULL,
    [REMARK]   NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FAILUREANALYSISCODES_T_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_FC_FAILUREANALYSISCODES_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_FAILUREANALYSISCODES] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_FAILUREANALYSISCODES_T_CUSTID_VNESHID]
    ON [dbo].[FC_FAILUREANALYSISCODES_T]([VNESHID] ASC, [CUSTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FAILUREANALYSISCODES_T]
    ON [dbo].[FC_FAILUREANALYSISCODES_T]([VNESHID] ASC);

