CREATE TABLE [dbo].[FC_FAILURERATES2_FARS] (
    [FYEAR]          INT             NOT NULL,
    [FMONTH]         INT             NOT NULL,
    [MTID]           INT             NOT NULL,
    [MODELID]        INT             NOT NULL,
    [FCODE]          INT             NULL,
    [FACODE]         INT             NOT NULL,
    [FCOUNT]         DECIMAL (14, 4) NULL,
    [FRATE]          DECIMAL (14, 2) NULL,
    [PRODUCED_COUNT] DECIMAL (14, 4) NULL,
    [FCOUNT_INT]     DECIMAL (14, 4) NULL,
    [FCOUNT_EXT]     DECIMAL (14, 4) NULL,
    CONSTRAINT [FK_FC_FAILURERATES2_FARS_2_FACODE] FOREIGN KEY ([FACODE]) REFERENCES [dbo].[FC_FAILUREANALYSISCODES] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_FC_FAILURERATES2_FARS_2_FCODE] FOREIGN KEY ([FCODE]) REFERENCES [dbo].[FC_FAILURECODES] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_FAILURERATES2_FARS]
    ON [dbo].[FC_FAILURERATES2_FARS]([FYEAR] ASC, [FMONTH] ASC, [MODELID] ASC, [FACODE] ASC, [FCODE] ASC);

