CREATE TABLE [dbo].[FC_FA_SUBSCRIBE_T] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [VNESHID]      INT              NOT NULL,
    [DEPARTMENTID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FA_SUBSCRIBE_T_DEPARTMENTID] FOREIGN KEY ([DEPARTMENTID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_FA_SUBSCRIBE_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_FA_SUBSCRIBE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FA_SUBSCRIBE_T]
    ON [dbo].[FC_FA_SUBSCRIBE_T]([VNESHID] ASC);

