CREATE TABLE [dbo].[FC_FAILURERATES_FARS_FACODE] (
    [ID]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [FYEAR]              INT             NOT NULL,
    [FMONTH]             INT             NOT NULL,
    [FACODE]             INT             NULL,
    [FCOUNT]             DECIMAL (14, 4) NULL,
    [FRATE]              DECIMAL (14, 2) NULL,
    [PRODUCED_COUNT]     DECIMAL (14, 4) NULL,
    [ALLFCOUNT]          DECIMAL (14, 4) NULL,
    [FRATE_2ALLFAILURES] DECIMAL (14, 2) NULL,
    [FCOUNT_INT]         DECIMAL (14, 4) NULL,
    [FCOUNT_EXT]         DECIMAL (14, 4) NULL,
    [FYEARMONTH]         INT             NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FAILURERATES_FARS_FACODE] FOREIGN KEY ([FACODE]) REFERENCES [dbo].[FC_FAILUREANALYSISCODES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FAILURERATES_FARS_FACODE_2]
    ON [dbo].[FC_FAILURERATES_FARS_FACODE]([FYEAR] ASC, [FMONTH] ASC)
    INCLUDE([FCOUNT], [PRODUCED_COUNT], [ALLFCOUNT]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_FAILURERATES_FARS_FACODE]
    ON [dbo].[FC_FAILURERATES_FARS_FACODE]([FYEAR] ASC, [FMONTH] ASC, [FACODE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FC_FAILURERATES_FARS_FACODE_FYEARMONTH]
    ON [dbo].[FC_FAILURERATES_FARS_FACODE]([FACODE] ASC, [FYEARMONTH] ASC)
    INCLUDE([FYEAR], [FMONTH], [FRATE], [FRATE_2ALLFAILURES]);

