CREATE TABLE [dbo].[FC_FA_APPROVE_SUBSCRIPTION_EXT_MAIL] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMAIL]   NVARCHAR (200)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FA_APPROVE_SUBSCRIPTION_EXT_MAIL_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_FA_APPROVE_SUBSCRIPTION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FA_APPROVE_SUBSCRIPTION_EXT_MAIL]
    ON [dbo].[FC_FA_APPROVE_SUBSCRIPTION_EXT_MAIL]([VNESHID] ASC);

