CREATE TABLE [dbo].[FC_FAILURERATES_PRODUCED] (
    [ID]      INT             IDENTITY (1, 1) NOT NULL,
    [FYEAR]   INT             NOT NULL,
    [FMONTH]  INT             NOT NULL,
    [MTID]    INT             NOT NULL,
    [MODELID] INT             NOT NULL,
    [PCOUNT]  DECIMAL (14, 4) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FAILURERATES_PRODUCED]
    ON [dbo].[FC_FAILURERATES_PRODUCED]([FYEAR] ASC, [FMONTH] ASC);

