CREATE TABLE [dbo].[FC_FAILUREANALYSISCODE_GROUPS_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [GROUPID]  INT              NOT NULL,
    [FACODEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_FAILUREANALYSISCODE_GROUPS_T_FACODEID] FOREIGN KEY ([FACODEID]) REFERENCES [dbo].[FC_FAILUREANALYSISCODES] ([ID]),
    CONSTRAINT [FK_FC_FAILUREANALYSISCODE_GROUPS_T_GROUPID] FOREIGN KEY ([GROUPID]) REFERENCES [dbo].[FC_FAILUREANALYSISCODE_GROUPS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_FAILUREANALYSISCODE_GROUPS_T]
    ON [dbo].[FC_FAILUREANALYSISCODE_GROUPS_T]([GROUPID] ASC);

