CREATE TABLE [dbo].[FC_NOTIFICATIONS] (
    [NOTIFTYPE] INT      NULL,
    [NOTIFDD]   DATETIME NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_NOTIFICATIONS]
    ON [dbo].[FC_NOTIFICATIONS]([NOTIFTYPE] ASC, [NOTIFDD] ASC);

