CREATE TABLE [dbo].[FC_NOTIFICATION_SETTINGS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [DEPID]    INT              NOT NULL,
    [NTYPE]    INT              NOT NULL,
    [TOEMPLID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_NOTIFICATION_SETTINGS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_NOTIFICATION_SETTINGS_TOEMPLID] FOREIGN KEY ([TOEMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_NOTIFICATION_SETTINGS_1]
    ON [dbo].[FC_NOTIFICATION_SETTINGS]([DEPID] ASC, [NTYPE] ASC, [TOEMPLID] ASC);

