CREATE TABLE [dbo].[FC_QA_FAILURECODES_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [FCID]    INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_QA_FAILURECODES_T_FCID] FOREIGN KEY ([FCID]) REFERENCES [dbo].[FC_FAILURECODES] ([ID]),
    CONSTRAINT [FK_FC_QA_FAILURECODES_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_QA_FAILURECODES] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_QA_FAILURECODES_T_FCID]
    ON [dbo].[FC_QA_FAILURECODES_T]([FCID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FC_QA_FAILURECODES_T]
    ON [dbo].[FC_QA_FAILURECODES_T]([VNESHID] ASC);

