CREATE TABLE [dbo].[FC_REPORT_ANALYSIS_CODES_T2] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [HREPORTID] INT              NOT NULL,
    [HECODEID]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_REPORT_ANALYSIS_CODES_T2_HREPORTID] FOREIGN KEY ([HREPORTID]) REFERENCES [dbo].[FC_HUMANERROR] ([ID]),
    CONSTRAINT [FK_FC_REPORT_ANALYSIS_CODES_T2_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_REPORT_ANALYSIS_CODES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_REPORT_ANALYSIS_CODES_T2]
    ON [dbo].[FC_REPORT_ANALYSIS_CODES_T2]([VNESHID] ASC);

