CREATE TABLE [dbo].[FC_REPORT_ANALYSIS_CODES_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [REPORTID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_FC_REPORT_ANALYSIS_CODES_T_REPORTID] FOREIGN KEY ([REPORTID]) REFERENCES [dbo].[FC_REPORT] ([ID]),
    CONSTRAINT [FK_FC_REPORT_ANALYSIS_CODES_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_REPORT_ANALYSIS_CODES] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_REPORT_ANALYSIS_CODES_T_1]
    ON [dbo].[FC_REPORT_ANALYSIS_CODES_T]([REPORTID] ASC, [VNESHID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_FC_REPORT_ANALYSIS_CODES_T]
    ON [dbo].[FC_REPORT_ANALYSIS_CODES_T]([VNESHID] ASC) WITH (FILLFACTOR = 90);

