CREATE TABLE [dbo].[FC_REPORT_PARAMS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [FRID]    INT              NOT NULL,
    [PARAMID] INT              NOT NULL,
    [PVALUE]  SQL_VARIANT      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_REPORT_PARAMS_FRID] FOREIGN KEY ([FRID]) REFERENCES [dbo].[FC_REPORT] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_FC_REPORT_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[FC_FAILUREPARAMS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_REPORT_PARAMS_FRID_PARAMID]
    ON [dbo].[FC_REPORT_PARAMS]([FRID] ASC, [PARAMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FC_REPORT_PARAMS]
    ON [dbo].[FC_REPORT_PARAMS]([FRID] ASC);

