CREATE TABLE [dbo].[FC_REPORT_ANALYSIS_CODES] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [GID]            UNIQUEIDENTIFIER NULL,
    [S_CR]           INT              NOT NULL,
    [S_CDT]          DATETIME         NOT NULL,
    [S_MR]           INT              NULL,
    [S_MDT]          DATETIME         NULL,
    [ARC]            INT              NULL,
    [VNESHID]        INT              NOT NULL,
    [ANALYSISCODEID] INT              NOT NULL,
    [OPTS]           INT              NULL,
    [FCODE]          INT              NULL,
    [INITI]          INT              NULL,
    [TEMP_OLDCODEID] INT              NULL,
    [TEMP_NEWCODEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_REPORT_ANALYSIS_CODES_ANALYSISCODEID] FOREIGN KEY ([ANALYSISCODEID]) REFERENCES [dbo].[FC_FAILUREANALYSISCODES] ([ID]),
    CONSTRAINT [FK_FC_REPORT_ANALYSIS_CODES_FCODE] FOREIGN KEY ([FCODE]) REFERENCES [dbo].[FC_REPORT_CODES] ([ID]),
    CONSTRAINT [FK_FC_REPORT_ANALYSIS_CODES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_REPORT] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_REPORT_ANALYSIS_CODES1]
    ON [dbo].[FC_REPORT_ANALYSIS_CODES]([ANALYSISCODEID] ASC, [FCODE] ASC, [VNESHID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FC_REPORT_ANALYSIS_CODES]
    ON [dbo].[FC_REPORT_ANALYSIS_CODES]([VNESHID] ASC);

