CREATE TABLE [dbo].[FC_REPORT_CODES] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [GID]            UNIQUEIDENTIFIER NULL,
    [S_CR]           INT              NOT NULL,
    [S_CDT]          DATETIME         NOT NULL,
    [S_MR]           INT              NULL,
    [S_MDT]          DATETIME         NULL,
    [ARC]            INT              NULL,
    [VNESHID]        INT              NOT NULL,
    [REPCODEID]      INT              NOT NULL,
    [DISCOVERED]     INT              NULL,
    [TEMP_OLDCODEID] INT              NULL,
    [TEMP_NEWCODEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_FC_REPORT_CODES_REPCODEID] FOREIGN KEY ([REPCODEID]) REFERENCES [dbo].[FC_FAILURECODES] ([ID]),
    CONSTRAINT [FK_FC_REPORT_CODES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[FC_REPORT] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_REPORT_CODES1]
    ON [dbo].[FC_REPORT_CODES]([REPCODEID] ASC, [VNESHID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_FC_REPORT_CODES]
    ON [dbo].[FC_REPORT_CODES]([VNESHID] ASC) WITH (FILLFACTOR = 90);

