CREATE TABLE [dbo].[FC_RETURN_DEPARTMENTS] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [DEPID]         INT              NOT NULL,
    [MTID]          INT              NOT NULL,
    [RETURNTO]      INT              NOT NULL,
    [RETURNTODEPID] INT              NULL,
    [REMARK]        NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_RETURN_DEPARTMENTS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_RETURN_DEPARTMENTS_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_FC_RETURN_DEPARTMENTS_RETURNTODEPID] FOREIGN KEY ([RETURNTODEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FC_RETURN_DEPARTMENTS]
    ON [dbo].[FC_RETURN_DEPARTMENTS]([DEPID] ASC, [MTID] ASC)
    INCLUDE([RETURNTO], [RETURNTODEPID]);

