CREATE TABLE [dbo].[FC_TRANSIT_DEP] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [DEPID]     INT              NOT NULL,
    [FOR_DEPID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FC_TRANSIT_DEP_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_FC_TRANSIT_DEP_FOR_DEPID] FOREIGN KEY ([FOR_DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FC_TRANSIT_DEP]
    ON [dbo].[FC_TRANSIT_DEP]([DEPID] ASC, [FOR_DEPID] ASC);

