CREATE TABLE [dbo].[HR_CH_EMP_BALANCE_HISTORY] (
    [ID]               INT      IDENTITY (1, 1) NOT NULL,
    [S_CR]             INT      NOT NULL,
    [S_CDT]            DATETIME NOT NULL,
    [S_MR]             INT      NULL,
    [S_MDT]            DATETIME NULL,
    [EMPID]            INT      NULL,
    [DATE]             DATE     NULL,
    [BALANCE_OVERTIME] INT      NULL,
    [BALANCE_SHRT_ABS] INT      NULL,
    [BALANCE_DELTA]    INT      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_HR_CH_EMP_BALANCE_HISTORY_EMPID] FOREIGN KEY ([EMPID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_HR_CH_EMP_BALANCE_HISTORY_EMPID_DATE]
    ON [dbo].[HR_CH_EMP_BALANCE_HISTORY]([EMPID] ASC, [DATE] ASC);

