CREATE TABLE [dbo].[IE_ITEMPOSITIONS_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [MTID]    INT              NOT NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IE_ITEMPOSITIONS_T_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_IE_ITEMPOSITIONS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IE_ITEMPOSITIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IE_ITEMPOSITIONS_T]
    ON [dbo].[IE_ITEMPOSITIONS_T]([VNESHID] ASC);

