CREATE TABLE [dbo].[IE_IEITEMS] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NOT NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [VNESHID]      INT              NOT NULL,
    [ITTYPE]       INT              NOT NULL,
    [DEVICEID]     INT              NULL,
    [SN]           NVARCHAR (50)    NULL,
    [MODELNAME]    NVARCHAR (100)   NULL,
    [PRODUCER]     NVARCHAR (200)   NULL,
    [DESCSTR]      NTEXT            NULL,
    [IEPOSITIONID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IE_IEITEMS_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_IE_IEITEMS_IEPOSITIONID] FOREIGN KEY ([IEPOSITIONID]) REFERENCES [dbo].[IE_ITEMPOSITIONS] ([ID]),
    CONSTRAINT [FK_IE_IEITEMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IE_IE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IE_IEITEMS_SN]
    ON [dbo].[IE_IEITEMS]([SN] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IE_IEITEMS_DEVICEID]
    ON [dbo].[IE_IEITEMS]([DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IE_IEITEMS]
    ON [dbo].[IE_IEITEMS]([VNESHID] ASC);

