CREATE TABLE [dbo].[IMS_TRAINING_FILES] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [FILENAME] NVARCHAR (255)   NOT NULL,
    [FILEDATE] DATETIME         NOT NULL,
    [FILESIZE] INT              NULL,
    [FILEBLOB] IMAGE            NULL,
    [FILEDESC] NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IMS_TRAINING_FILES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IMS_TRAINING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IMS_TRAINING_FILES]
    ON [dbo].[IMS_TRAINING_FILES]([VNESHID] ASC);

