CREATE TABLE [dbo].[IMS_DEP_SCHEDULE_NOTIFY] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IMS_DEP_SCHEDULE_NOTIFY_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_IMS_DEP_SCHEDULE_NOTIFY_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IMS_DEP_SCHEDULE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IMS_DEP_SCHEDULE_NOTIFY]
    ON [dbo].[IMS_DEP_SCHEDULE_NOTIFY]([VNESHID] ASC);

