CREATE TABLE [dbo].[IMS_TRAINING] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [GID]              UNIQUEIDENTIFIER NOT NULL,
    [S_S]              INT              NOT NULL,
    [S_CR]             INT              NOT NULL,
    [S_CDT]            DATETIME         NOT NULL,
    [S_MR]             INT              NULL,
    [S_MDT]            DATETIME         NULL,
    [ARC]              INT              NULL,
    [EMPLID]           INT              NOT NULL,
    [SCHEDULEDATEID]   INT              NOT NULL,
    [SCHEDULEID]       INT              NOT NULL,
    [TRAININGTYPEID]   INT              NOT NULL,
    [TRAININGPLANID]   INT              NOT NULL,
    [COMPLETED_D]      DATETIME         NULL,
    [CERTIFIED_D]      DATE             NULL,
    [NOTIFIED_7]       DATETIME         NULL,
    [NOTIFIED_1]       DATETIME         NULL,
    [NOTCMPL_NOTIFIED] DATE             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IMS_TRAINING_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_IMS_TRAINING_SCHEDULEDATEID] FOREIGN KEY ([SCHEDULEDATEID]) REFERENCES [dbo].[IMS_TRAINING_SCHEDULE_DATES] ([ID]),
    CONSTRAINT [FK_IMS_TRAINING_SCHEDULEID] FOREIGN KEY ([SCHEDULEID]) REFERENCES [dbo].[IMS_TRAINING_SCHEDULE] ([ID]),
    CONSTRAINT [FK_IMS_TRAINING_TRAININGPLANID] FOREIGN KEY ([TRAININGPLANID]) REFERENCES [dbo].[IMS_TRAINING_PLAN] ([ID]),
    CONSTRAINT [FK_IMS_TRAINING_TRAININGTYPEID] FOREIGN KEY ([TRAININGTYPEID]) REFERENCES [dbo].[IMS_TRAINING_TYPE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IMS_TRAINING_S_S]
    ON [dbo].[IMS_TRAINING]([S_S] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IMS_TRAINING_CERTIFIED_D]
    ON [dbo].[IMS_TRAINING]([CERTIFIED_D] ASC);

