CREATE TABLE [dbo].[IMS_TRAINING_SCHEDULE_DATES] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NOT NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [VNESHID]    INT              NOT NULL,
    [DD]         DATETIME         NOT NULL,
    [TRLOCATION] NVARCHAR (250)   NULL,
    [MAXPERSONS] INT              NOT NULL,
    [REMARK]     NTEXT            NULL,
    [DD_END]     DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IMS_TRAINING_SCHEDULE_DATES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IMS_TRAINING_SCHEDULE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IMS_TRAINING_SCHEDULE_DATES]
    ON [dbo].[IMS_TRAINING_SCHEDULE_DATES]([VNESHID] ASC);

