CREATE TABLE [dbo].[IMS_DEP_SCHEDULE_T] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [GID]            UNIQUEIDENTIFIER NOT NULL,
    [S_CR]           INT              NOT NULL,
    [S_CDT]          DATETIME         NOT NULL,
    [S_MR]           INT              NULL,
    [S_MDT]          DATETIME         NULL,
    [ARC]            INT              NULL,
    [VNESHID]        INT              NOT NULL,
    [EMPLID]         INT              NOT NULL,
    [SCHEDULEDATEID] INT              NULL,
    [NODATE]         INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IMS_DEP_SCHEDULE_T_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_IMS_DEP_SCHEDULE_T_SCHEDULEDATEID] FOREIGN KEY ([SCHEDULEDATEID]) REFERENCES [dbo].[IMS_TRAINING_SCHEDULE_DATES] ([ID]),
    CONSTRAINT [FK_IMS_DEP_SCHEDULE_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IMS_DEP_SCHEDULE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IMS_DEP_SCHEDULE_T]
    ON [dbo].[IMS_DEP_SCHEDULE_T]([VNESHID] ASC);

