CREATE TABLE [dbo].[IOE_KB3043_NOTIFICATION] (
    [DEPID]    INT  NOT NULL,
    [LASTSEND] DATE NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IOE_KB3043_NOTIFICATION_DEPID]
    ON [dbo].[IOE_KB3043_NOTIFICATION]([DEPID] ASC);

