CREATE TABLE [dbo].[IOE_NOTI_COURSES] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [COURSEID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IOE_NOTI_COURSES_COURSEID] FOREIGN KEY ([COURSEID]) REFERENCES [dbo].[IOE_TOPICS] ([ID]),
    CONSTRAINT [FK_IOE_NOTI_COURSES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IOE_NOTIFICATIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IOE_NOTI_COURSES_COURSEID]
    ON [dbo].[IOE_NOTI_COURSES]([VNESHID] ASC, [COURSEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IOE_NOTI_COURSES]
    ON [dbo].[IOE_NOTI_COURSES]([VNESHID] ASC);

