CREATE TABLE [dbo].[IOE_TOPIC_DEPS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [DEPID]   INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IOE_TOPIC_DEPS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_IOE_TOPIC_DEPS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IOE_TOPICS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IOE_TOPIC_DEPS]
    ON [dbo].[IOE_TOPIC_DEPS]([VNESHID] ASC);

