CREATE TABLE [dbo].[IOE_TOPIC_INSTRUCTORS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IOE_TOPIC_INSTRUCTORS_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_IOE_TOPIC_INSTRUCTORS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IOE_TOPICS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IOE_TOPIC_INSTRUCTORS]
    ON [dbo].[IOE_TOPIC_INSTRUCTORS]([VNESHID] ASC);

