CREATE TABLE [dbo].[IOE_NOTI_RECIPIENTS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IOE_NOTI_RECIPIENTS_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_IOE_NOTI_RECIPIENTS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IOE_NOTIFICATIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IOE_NOTI_RECIPIENTS_EMPLID]
    ON [dbo].[IOE_NOTI_RECIPIENTS]([VNESHID] ASC, [EMPLID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IOE_NOTI_RECIPIENTS]
    ON [dbo].[IOE_NOTI_RECIPIENTS]([VNESHID] ASC);

