CREATE TABLE [dbo].[IOE_CHAPTER_QUESTIONS] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NOT NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [VNESHID]      INT              NOT NULL,
    [QUESTIONTEXT] NTEXT            NOT NULL,
    [ANSWERTYPES]  INT              NOT NULL,
    [QUESTIONTYPE] INT              NOT NULL,
    [REMARK]       NTEXT            NULL,
    [WRANSWTEXT]   NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IOE_CHAPTER_QUESTIONS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IOE_CHAPTER] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IOE_CHAPTER_QUESTIONS_GID]
    ON [dbo].[IOE_CHAPTER_QUESTIONS]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IOE_CHAPTER_QUESTIONS]
    ON [dbo].[IOE_CHAPTER_QUESTIONS]([VNESHID] ASC);

