CREATE TABLE [dbo].[IT_A2CPACKET_FILES] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [FILENAME] NVARCHAR (255)   NOT NULL,
    [FILEDATE] DATETIME         NOT NULL,
    [FILESIZE] INT              NULL,
    [FILEBLOB] IMAGE            NULL,
    [FILEDESC] NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IT_A2CPACKET_FILES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IT_A2CPACKETS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IT_A2CPACKET_FILES]
    ON [dbo].[IT_A2CPACKET_FILES]([VNESHID] ASC);

