CREATE TABLE [dbo].[IT_KB_NOTIFICATIONS_S] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [NOTIFID] INT              NOT NULL,
    [STATEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IT_KB_NOTIFICATIONS_S_NOTIFID] FOREIGN KEY ([NOTIFID]) REFERENCES [dbo].[IT_KB_NOTIFICATIONS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_IT_KB_NOTIFICATIONS_S_STATEID] FOREIGN KEY ([STATEID]) REFERENCES [dbo].[DEF_CLASS_STATES] ([OID])
);


GO
CREATE NONCLUSTERED INDEX [IX_IT_KB_NOTIFICATIONS_S]
    ON [dbo].[IT_KB_NOTIFICATIONS_S]([NOTIFID] ASC);

