CREATE TABLE [dbo].[IT_PROJECT_MEMBERS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [EMPLID]  INT              NOT NULL,
    [VNESHID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IT_PROJECT_MEMBERS_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_IT_PROJECT_MEMBERS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IT_PROJECT] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IT_PROJECT_MEMBERS]
    ON [dbo].[IT_PROJECT_MEMBERS]([VNESHID] ASC);

