CREATE TABLE [dbo].[IT_PPT_CMPL] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [SUBJ]    NVARCHAR (1024)  NOT NULL,
    [DEPCODE] NVARCHAR (50)    NULL,
    [TASKID]  INT              NULL,
    [SUBJRU]  NVARCHAR (1024)  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IT_PPT_CMPL_TASKID] FOREIGN KEY ([TASKID]) REFERENCES [dbo].[IT_TASKS] ([ID]),
    CONSTRAINT [FK_IT_PPT_CMPL_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[IT_PPT] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_IT_PPT_CMPL]
    ON [dbo].[IT_PPT_CMPL]([VNESHID] ASC);

