CREATE TABLE [dbo].[IT_TASKS] (
    [ID]                INT              IDENTITY (1, 1) NOT NULL,
    [GID]               UNIQUEIDENTIFIER NULL,
    [S_CR]              INT              NOT NULL,
    [S_CDT]             DATETIME         NOT NULL,
    [S_MR]              INT              NULL,
    [S_MDT]             DATETIME         NULL,
    [ARC]               INT              NULL,
    [DD]                DATETIME         NOT NULL,
    [PROJID]            INT              NOT NULL,
    [FROMDEPID]         INT              NOT NULL,
    [FROMEMPLID]        INT              NULL,
    [SUBJ]              NVARCHAR (512)   NOT NULL,
    [BODY]              NTEXT            NULL,
    [PRIORITY]          INT              NULL,
    [PLAN_INCL]         INT              NULL,
    [PLAN_TEXT]         NTEXT            NULL,
    [PLAN_TEXT_EN]      NTEXT            NULL,
    [PLAN_WEEK]         INT              NULL,
    [PLAN_WEEK_D]       INT              NULL,
    [PLAN_COMMENT]      NVARCHAR (300)   NULL,
    [S_S]               INT              NOT NULL,
    [TICKETN]           NVARCHAR (50)    NULL,
    [RETREMARK]         NTEXT            NULL,
    [DHAPPROVED]        INT              NULL,
    [NEEDSPECIFY]       INT              NULL,
    [SHELVED]           INT              NULL,
    [DEPLOY_STATE]      INT              NULL,
    [ASSIGNEE]          INT              NULL,
    [TYPE]              INT              NULL,
    [DONEINVERSION]     NVARCHAR (50)    NULL,
    [PLAN_ANALYSIS]     INT              NULL,
    [FCCONTROL]         INT              NULL,
    [DEV_NOTIFICATION]  DATETIME         NULL,
    [TAGS]              NVARCHAR (300)   NULL,
    [TS]                ROWVERSION       NULL,
    [DONE_DT]           DATETIME         NULL,
    [STACKRANK]         DECIMAL (18, 2)  NULL,
    [NOTPASSTECHREVIEW] INT              NULL,
    [AZURE_WI]          INT              NULL,
    [AZURE_SY]          INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IT_TASKS_ASSIGNEE] FOREIGN KEY ([ASSIGNEE]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_IT_TASKS_FROMDEPID] FOREIGN KEY ([FROMDEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_IT_TASKS_FROMEMPLID] FOREIGN KEY ([FROMEMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_IT_TASKS_PROJID] FOREIGN KEY ([PROJID]) REFERENCES [dbo].[IT_PROJECT] ([ID])
);

