CREATE TABLE [dbo].[IT_TASK_COMMENT_READ] (
    [ID]            INT      IDENTITY (1, 1) NOT NULL,
    [TASKCOMMENTID] INT      NOT NULL,
    [USERID]        INT      NOT NULL,
    [DATEREAD]      DATETIME CONSTRAINT [DF_IT_TASK_COMMENT_READ_DATEREAD] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_IT_TASK_COMMENT_READ] PRIMARY KEY CLUSTERED ([ID] ASC)
);

