CREATE TABLE [dbo].[LN_ORDER_POSITIONS] (
    [ID]        INT IDENTITY (1, 1) NOT NULL,
    [VNESHID]   INT NOT NULL,
    [VARIANTID] INT NOT NULL,
    [DAY]       INT NOT NULL,
    [RATE]      INT NULL,
    [QUANTITY]  INT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_LN_ORDER_POSITIONS_VARIANTID] FOREIGN KEY ([VARIANTID]) REFERENCES [dbo].[LN_WEEK_VARIANT] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_LN_ORDER_POSITIONS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[LN_ORDER] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_LN_ORDER_POSITIONS_2]
    ON [dbo].[LN_ORDER_POSITIONS]([VNESHID] ASC, [DAY] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_LN_ORDER_POSITIONS]
    ON [dbo].[LN_ORDER_POSITIONS]([VNESHID] ASC);

