CREATE TABLE [dbo].[LN_SKIPPING_CARDS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [CARDID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_LN_SKIPPING_CARDS_CARDID] FOREIGN KEY ([CARDID]) REFERENCES [dbo].[LN_CARDS] ([ID]),
    CONSTRAINT [FK_LN_SKIPPING_CARDS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[LN_SKIPPING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_LN_SKIPPING_CARDS]
    ON [dbo].[LN_SKIPPING_CARDS]([VNESHID] ASC);

