CREATE TABLE [dbo].[MAIL_SETTINGS_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [CODE]    NVARCHAR (10)    NOT NULL,
    [EMAIL]   NVARCHAR (100)   NOT NULL,
    [CAPTION] NVARCHAR (100)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MAIL_SETTINGS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MAIL_SETTINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MAIL_SETTINGS_T_CODE]
    ON [dbo].[MAIL_SETTINGS_T]([VNESHID] ASC, [CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MAIL_SETTINGS_T]
    ON [dbo].[MAIL_SETTINGS_T]([VNESHID] ASC);

