CREATE TABLE [dbo].[MNT_PLAN_EQ_PARAMS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [PARAMID] INT              NOT NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MNT_PLAN_EQ_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_MNT_PLAN_EQ_PARAMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MNT_PLAN] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MNT_PLAN_EQ_PARAMS]
    ON [dbo].[MNT_PLAN_EQ_PARAMS]([VNESHID] ASC);

