CREATE TABLE [dbo].[MNT_PLAN_NOTYRCV] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MNT_PLAN_NOTYRCV_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_MNT_PLAN_NOTYRCV_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MNT_PLAN] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MNT_PLAN_NOTYRCV]
    ON [dbo].[MNT_PLAN_NOTYRCV]([VNESHID] ASC);

