CREATE TABLE [dbo].[MNT_PLAN_EQ_LINKED_EQ] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EQID]    INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MNT_PLAN_EQ_LINKED_EQ_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_MNT_PLAN_EQ_LINKED_EQ_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MNT_PLAN_EQ] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MNT_PLAN_EQ_LINKED_EQ]
    ON [dbo].[MNT_PLAN_EQ_LINKED_EQ]([VNESHID] ASC);

