CREATE TABLE [dbo].[MSG_PLANNED_DATES_CHANGES] (
    [ID]       INT      IDENTITY (1, 1) NOT NULL,
    [DEVICEID] INT      NULL,
    [OLDDATE]  DATETIME NULL,
    [NEWDATE]  DATETIME NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

