CREATE TABLE [dbo].[MSG_IN_ATTACHEMENTS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [FILENAME]  NVARCHAR (250)   NOT NULL,
    [FILEDATE]  DATETIME         NOT NULL,
    [FILESIZE]  INT              NULL,
    [FILEBLOB]  IMAGE            NULL,
    [ATTID]     NVARCHAR (100)   NULL,
    [CONTENTID] NVARCHAR (250)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MSG_IN_ATTACHEMENTS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MSG_INBOX] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MSG_IN_ATTACHEMENTS_ATTID]
    ON [dbo].[MSG_IN_ATTACHEMENTS]([ATTID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_IN_ATTACHEMENTS]
    ON [dbo].[MSG_IN_ATTACHEMENTS]([VNESHID] ASC) WITH (FILLFACTOR = 90);

