CREATE TABLE [dbo].[MSG_LAST_DELIVERY_DATES] (
    [DELIVERYTYPE] INT  NOT NULL,
    [DEPID]        INT  NOT NULL,
    [DD]           DATE NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MSG_LAST_DELIVERY_DATES]
    ON [dbo].[MSG_LAST_DELIVERY_DATES]([DELIVERYTYPE] ASC, [DEPID] ASC, [DD] ASC);

