CREATE TABLE [dbo].[MSG_LAST_NOTIFICATIONS] (
    [DELIVERYTYPE] INT  NOT NULL,
    [DD]           DATE NOT NULL,
    [PART]         INT  NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MSG_LAST_NOTIFICATIONS]
    ON [dbo].[MSG_LAST_NOTIFICATIONS]([DELIVERYTYPE] ASC);

