CREATE TABLE [dbo].[MSG_DELIVERYLIST_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    [EMPCOPY] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MSG_DELIVERYLIST_T_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_MSG_DELIVERYLIST_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MSG_DELIVERYLIST] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_DELIVERYLIST_T]
    ON [dbo].[MSG_DELIVERYLIST_T]([VNESHID] ASC);

