CREATE TABLE [dbo].[MSG_TASK_EXECUTIONS] (
    [ID]        INT            IDENTITY (1, 1) NOT NULL,
    [LABEL]     NVARCHAR (40)  NOT NULL,
    [REMARK]    NVARCHAR (500) NOT NULL,
    [LAST_EXEC] DATETIME       NULL,
    CONSTRAINT [PK_MSG_TASK_EXECUTIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

