CREATE TABLE [dbo].[MSG_FILENOTIFICATION_T] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [VNESHID]      INT              NOT NULL,
    [PARAMID]      INT              NOT NULL,
    [FILEREQUIRED] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MSG_FILENOTIFICATION_T_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_MSG_FILENOTIFICATION_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MSG_FILENOTIFICATIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_FILENOTIFICATION_T]
    ON [dbo].[MSG_FILENOTIFICATION_T]([VNESHID] ASC);

