CREATE TABLE [dbo].[MSG_FAILURE_WASNOTIFIED] (
    [OPERID] INT NOT NULL,
    [USERID] INT NOT NULL
);


GO
CREATE CLUSTERED INDEX [IX_MSG_FAILURE_WASNOTIFIED]
    ON [dbo].[MSG_FAILURE_WASNOTIFIED]([OPERID] ASC, [USERID] ASC) WITH (FILLFACTOR = 90);

