CREATE TABLE [dbo].[MSG_FILENOTIFICATIONS_OUT] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_S]         INT              NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [SBSCID]      INT              NOT NULL,
    [DEVICEID]    INT              NOT NULL,
    [CRDATE]      DATETIME         NOT NULL,
    [SENTDATE]    DATETIME         NULL,
    [MSGID]       INT              NULL,
    [READYDT]     DATETIME         NULL,
    [READYNAVMSG] NTEXT            NULL,
    [TICKETID]    INT              NULL,
    [CUSTOMERID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_OUT_CUSTOMERID] FOREIGN KEY ([CUSTOMERID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_OUT_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_OUT_MSGID] FOREIGN KEY ([MSGID]) REFERENCES [dbo].[MSG_OUTGOING] ([ID]),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_OUT_SBSCID] FOREIGN KEY ([SBSCID]) REFERENCES [dbo].[MSG_FILENOTIFICATIONS] ([ID]),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_OUT_TICKETID] FOREIGN KEY ([TICKETID]) REFERENCES [dbo].[CP_TICKETS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_FILENOTIFICATIONS_OUT_TICKET]
    ON [dbo].[MSG_FILENOTIFICATIONS_OUT]([TICKETID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_FILENOTIFICATIONS_OUT_S_S]
    ON [dbo].[MSG_FILENOTIFICATIONS_OUT]([S_S] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_FILENOTIFICATIONS_OUT_DEVICEID]
    ON [dbo].[MSG_FILENOTIFICATIONS_OUT]([DEVICEID] ASC);

