CREATE TABLE [dbo].[MSG_OUT_ATTACHEMENTS] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [VNESHID]     INT              NOT NULL,
    [FILENAME]    NVARCHAR (250)   NOT NULL,
    [FILEDATE]    DATETIME         NOT NULL,
    [FILESIZE]    INT              NULL,
    [FILEBLOB]    IMAGE            NULL,
    [CONTENTID]   NVARCHAR (100)   NULL,
    [CONTENTTYPE] NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_MSG_OUT_ATTACHEMENTS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MSG_OUTGOING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_OUT_ATTACHEMENTS]
    ON [dbo].[MSG_OUT_ATTACHEMENTS]([VNESHID] ASC) WITH (FILLFACTOR = 90);

