CREATE TABLE [dbo].[MSG_REPORTS_RULES] (
    [ID]              INT              IDENTITY (1, 1) NOT NULL,
    [GID]             UNIQUEIDENTIFIER NULL,
    [S_S]             INT              NOT NULL,
    [S_CR]            INT              NOT NULL,
    [S_CDT]           DATETIME         NOT NULL,
    [S_MR]            INT              NULL,
    [S_MDT]           DATETIME         NULL,
    [ARC]             INT              NULL,
    [MSGSUBJ]         NVARCHAR (300)   NOT NULL,
    [MSGTO]           NVARCHAR (500)   NOT NULL,
    [MSGCC]           NVARCHAR (500)   NULL,
    [REPORTOID]       INT              NOT NULL,
    [MSGBODY]         NTEXT            NULL,
    [PERIODTYPE]      INT              NULL,
    [CONTEXTID]       INT              NULL,
    [LASTSENT]        DATETIME         NULL,
    [DESCRIPTION]     NTEXT            NULL,
    [LASTERROR]       NTEXT            NULL,
    [MSGIMP]          INT              NULL,
    [EXPFORMAT]       INT              NULL,
    [CONDITIONOID]    INT              NULL,
    [SHORTPERIODTYPE] INT              NULL,
    [SENDAT]          DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MSG_REPORTS_RULES_CONDITIONOID] FOREIGN KEY ([CONDITIONOID]) REFERENCES [dbo].[DEF_SQL] ([OID]),
    CONSTRAINT [FK_MSG_REPORTS_RULES_REPORTOID] FOREIGN KEY ([REPORTOID]) REFERENCES [dbo].[DEF_REPORTS] ([OID])
);

