CREATE TABLE [dbo].[MSG_FILENOTIFICATIONS_MODELS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [MODELID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_MODELS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_MODELS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MSG_FILENOTIFICATIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_FILENOTIFICATIONS_MODELS]
    ON [dbo].[MSG_FILENOTIFICATIONS_MODELS]([VNESHID] ASC);

