CREATE TABLE [dbo].[MSG_NAV_DEADLOCKS] (
    [ID]     INT      IDENTITY (1, 1) NOT NULL,
    [DD]     DATETIME NOT NULL,
    [DCOUNT] INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MSG_NAV_DEADLOCKS]
    ON [dbo].[MSG_NAV_DEADLOCKS]([DD] ASC);

