CREATE TABLE [dbo].[MSG_WAIT_METHODS] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [VNESHID]       INT            NOT NULL,
    [METHODOID]     INT            NOT NULL,
    [METHODTEMPGID] NVARCHAR (200) NOT NULL,
    [METHODSUBJ]    NVARCHAR (100) NULL,
    [METHODCLR]     NVARCHAR (10)  NULL,
    CONSTRAINT [FK_MSG_WAIT_METHODS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MSG_WAIT_DOCS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_MSG_WAIT_METHODS_TEMPGID]
    ON [dbo].[MSG_WAIT_METHODS]([METHODTEMPGID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_WAIT_METHODS]
    ON [dbo].[MSG_WAIT_METHODS]([VNESHID] ASC);

