CREATE TABLE [dbo].[MSG_FILENOTIFICATIONS_CONTACTS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [CONTACTID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_CONTACTS_CONTACTID] FOREIGN KEY ([CONTACTID]) REFERENCES [dbo].[COM_CUST_CONTACTS] ([ID]),
    CONSTRAINT [FK_MSG_FILENOTIFICATIONS_CONTACTS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[MSG_FILENOTIFICATIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_MSG_FILENOTIFICATIONS_CONTACTS]
    ON [dbo].[MSG_FILENOTIFICATIONS_CONTACTS]([VNESHID] ASC);

