CREATE TABLE [dbo].[OLAP_JOB_STATUS] (
    [JOBID]    UNIQUEIDENTIFIER NOT NULL,
    [LASTDATE] DATETIME         NULL,
    [NEXTDATE] DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([JOBID] ASC)
);

