CREATE TABLE [dbo].[PM_KB3824_NOTIFICATION_DATES] (
    [NTYPE]  INT  NULL,
    [LASTDD] DATE NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PM_KB3824_NOTIFICATION_DATES]
    ON [dbo].[PM_KB3824_NOTIFICATION_DATES]([NTYPE] ASC);

