CREATE TABLE [dbo].[PM_TASK_EMP_FILE_BUNDLE] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GID]    UNIQUEIDENTIFIER NOT NULL,
    [S_CR]   INT              NOT NULL,
    [S_CDT]  DATETIME         NOT NULL,
    [S_MR]   INT              NULL,
    [S_MDT]  DATETIME         NULL,
    [ARC]    INT              NULL,
    [TASKID] INT              NULL,
    [EMPID]  INT              NULL,
    [DESCR]  NVARCHAR (200)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PM_TASK_EMP_FILE_BUNDLE_EMPID] FOREIGN KEY ([EMPID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PM_TASK_EMP_FILE_BUNDLE_TASKID] FOREIGN KEY ([TASKID]) REFERENCES [dbo].[PM_TASK] ([ID])
);

