CREATE TABLE [dbo].[PM_TT_NOTIFY_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PM_TT_NOTIFY_T_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PM_TT_NOTIFY_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PM_TT_NOTIFY] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PM_TT_NOTIFY_T]
    ON [dbo].[PM_TT_NOTIFY_T]([VNESHID] ASC);

