CREATE TABLE [dbo].[PM_TASK_TIME] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [EMPLID]  INT              NOT NULL,
    [TASKID]  INT              NOT NULL,
    [DD]      DATE             NOT NULL,
    [MHOUR]   DECIMAL (10, 2)  NULL,
    [REMARK]  NTEXT            NULL,
    [JIRA_ID] INT              NULL,
    [MINUTES] DECIMAL (10, 2)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PM_TASK_TIME_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PM_TASK_TIME_TASKID] FOREIGN KEY ([TASKID]) REFERENCES [dbo].[PM_TASK] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PM_TASK_TIME_TASKID]
    ON [dbo].[PM_TASK_TIME]([TASKID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PM_TASK_TIME_JIRA_ID]
    ON [dbo].[PM_TASK_TIME]([JIRA_ID] ASC) WHERE ([JIRA_ID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PM_TASK_TIME_EMPLID_DD]
    ON [dbo].[PM_TASK_TIME]([EMPLID] ASC, [DD] ASC)
    INCLUDE([TASKID], [MHOUR]);


GO
CREATE NONCLUSTERED INDEX [IX_PM_TASK_TIME_DD]
    ON [dbo].[PM_TASK_TIME]([DD] ASC)
    INCLUDE([EMPLID], [TASKID], [MHOUR]);


GO
CREATE NONCLUSTERED INDEX [IX_PM_TASK_TIME]
    ON [dbo].[PM_TASK_TIME]([DD] ASC, [EMPLID] ASC);

