CREATE TABLE [dbo].[PM_TASK_PLAN_HISTORY] (
    [TASKID]    INT             NOT NULL,
    [DD]        DATETIME        NOT NULL,
    [PLANID]    INT             NOT NULL,
    [LABOR_EST] DECIMAL (10, 2) NULL,
    [DBEG]      DATETIME        NULL,
    [DEND]      DATETIME        NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_PM_TASK_PLAN_HISTORY_DD]
    ON [dbo].[PM_TASK_PLAN_HISTORY]([TASKID] ASC, [DD] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PM_TASK_PLAN_HISTORY]
    ON [dbo].[PM_TASK_PLAN_HISTORY]([TASKID] ASC, [PLANID] ASC);

