CREATE TABLE [dbo].[PR_ACTIVECONTROLS_R] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GID]    UNIQUEIDENTIFIER NOT NULL,
    [S_CR]   INT              NOT NULL,
    [S_CDT]  DATETIME         NOT NULL,
    [S_MR]   INT              NULL,
    [S_MDT]  DATETIME         NULL,
    [ARC]    INT              NULL,
    [ACID]   INT              NOT NULL,
    [REMARK] NTEXT            NULL,
    [EMPLID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_ACTIVECONTROLS_R_ACID] FOREIGN KEY ([ACID]) REFERENCES [dbo].[PR_ACTIVECONTROLS] ([ID]),
    CONSTRAINT [FK_PR_ACTIVECONTROLS_R_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_ACTIVECONTROLS_R_EMPLID_ACID]
    ON [dbo].[PR_ACTIVECONTROLS_R]([EMPLID] ASC, [ACID] ASC);

