CREATE TABLE [dbo].[PR_AC_INHERIT_SETT_PRMS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [PARAMID]  INT              NOT NULL,
    [ACTIONID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_AC_INHERIT_SETT_PRMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_AC_INHERIT_SETT_PRMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_AC_INHERIT_SETT] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_AC_INHERIT_SETT_PRMS_VNESHID_PARAMID]
    ON [dbo].[PR_AC_INHERIT_SETT_PRMS]([VNESHID] ASC, [PARAMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_AC_INHERIT_SETT_PRMS_PARAMID]
    ON [dbo].[PR_AC_INHERIT_SETT_PRMS]([PARAMID] ASC) WHERE ([PARAMID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_AC_INHERIT_SETT_PRMS]
    ON [dbo].[PR_AC_INHERIT_SETT_PRMS]([VNESHID] ASC);

