CREATE TABLE [dbo].[PR_AC_INHERIT_SETT_MODELS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [MODELID]  INT              NOT NULL,
    [NEWPMAP]  INT              NULL,
    [REVISION] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_AC_INHERIT_SETT_MODELS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_AC_INHERIT_SETT_MODELS_NEWPMAP] FOREIGN KEY ([NEWPMAP]) REFERENCES [dbo].[PR_MAP] ([ID]),
    CONSTRAINT [FK_PR_AC_INHERIT_SETT_MODELS_REVISION] FOREIGN KEY ([REVISION]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_PR_AC_INHERIT_SETT_MODELS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_AC_INHERIT_SETT] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_AC_INHERIT_SETT_MODELS_VNESHID_MODELID]
    ON [dbo].[PR_AC_INHERIT_SETT_MODELS]([VNESHID] ASC, [MODELID] ASC, [REVISION] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_AC_INHERIT_SETT_MODELS]
    ON [dbo].[PR_AC_INHERIT_SETT_MODELS]([VNESHID] ASC);

