CREATE TABLE [dbo].[PR_COMP_RECALL_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [DEVICEID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_COMP_RECALL_T_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_COMP_RECALL_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_COMP_RECALL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_COMP_RECALL_T_DEVICEID]
    ON [dbo].[PR_COMP_RECALL_T]([DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_COMP_RECALL_T]
    ON [dbo].[PR_COMP_RECALL_T]([VNESHID] ASC);

