CREATE TABLE [dbo].[PR_COMPONENT_TEST_ITEM] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [SN]       NVARCHAR (50)    NOT NULL,
    [DEVICEID] INT              NULL,
    [APPROVED] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_COMPONENT_TEST_ITEM_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_COMPONENT_TEST_ITEM_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_COMPONENT_TEST] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_COMPONENT_TEST_ITEM_DEVICEID]
    ON [dbo].[PR_COMPONENT_TEST_ITEM]([DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_COMPONENT_TEST_ITEM]
    ON [dbo].[PR_COMPONENT_TEST_ITEM]([VNESHID] ASC);

