CREATE TABLE [dbo].[PR_DEVICE_SKIPPED_OP] (
    [DEVICEID]  INT NOT NULL,
    [ORDERID]   INT NOT NULL,
    [OPLEVEL]   INT NOT NULL,
    [REVOPERID] INT NOT NULL,
    [TRMAP_N]   INT NULL,
    [PARENTID]  INT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_SKIPPED_OP]
    ON [dbo].[PR_DEVICE_SKIPPED_OP]([DEVICEID] ASC, [ORDERID] ASC, [OPLEVEL] ASC, [REVOPERID] ASC, [TRMAP_N] ASC);

