CREATE TABLE [dbo].[PR_DEVICE_PROD_SUPP] (
    [ID]            INT             IDENTITY (1, 1) NOT NULL,
    [DEVICEID]      INT             NOT NULL,
    [QUALIFICATION] INT             NOT NULL,
    [ELAPSED]       DECIMAL (12, 2) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_DEVICE_PROD_SUPP_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_PROD_SUPP]
    ON [dbo].[PR_DEVICE_PROD_SUPP]([DEVICEID] ASC) WITH (FILLFACTOR = 90);

