CREATE TABLE [dbo].[PR_DEVICE_SEARCH] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [GID]                UNIQUEIDENTIFIER NULL,
    [S_S]                INT              NOT NULL,
    [S_CR]               INT              NOT NULL,
    [S_CDT]              DATETIME         NOT NULL,
    [S_MR]               INT              NULL,
    [S_MDT]              DATETIME         NULL,
    [ARC]                INT              NULL,
    [MODELTYPEID]        INT              NULL,
    [FILTER]             NTEXT            NULL,
    [PARAMETERS]         NTEXT            NULL,
    [SEARCHFORM]         NTEXT            NULL,
    [NAME]               NVARCHAR (150)   NULL,
    [WHERECLAUSE]        NTEXT            NULL,
    [ORDERBYCLAUSE]      NTEXT            NULL,
    [ORDERBY]            NTEXT            NULL,
    [SHOWSEARCHFORM]     INT              NULL,
    [ADDEDCOLUMNS]       NTEXT            NULL,
    [SHOWCOLUMNSELECTOR] INT              NULL,
    [DEPID]              INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_SEARCH_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_SEARCH_MODELTYPEID] FOREIGN KEY ([MODELTYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);

