CREATE TABLE [dbo].[PR_DOC_SETTINGS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [SWGROUP] INT              NOT NULL,
    [PARAMID] INT              NULL,
    [REMARK]  NTEXT            NULL,
    [DEPID]   INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DOC_SETTINGS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_DOC_SETTINGS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_DOC_SETTINGS_SWGROUP] FOREIGN KEY ([SWGROUP]) REFERENCES [dbo].[SW_TOOL_GROUPS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DOC_SETTINGS_2]
    ON [dbo].[PR_DOC_SETTINGS]([PARAMID] ASC, [SWGROUP] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DOC_SETTINGS_1]
    ON [dbo].[PR_DOC_SETTINGS]([PARAMID] ASC);

