CREATE TABLE [dbo].[PR_DEVICE_MODEL_CHANGINGS_T] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [VNESHID]    INT              NOT NULL,
    [DEVICEID]   INT              NOT NULL,
    [NEWMODELID] INT              NOT NULL,
    [NEWREVID]   INT              NULL,
    [OLDMODELID] INT              NULL,
    [OLDREVID]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_MODEL_CHANGINGS_T_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_MODEL_CHANGINGS_T_NEWMODELID] FOREIGN KEY ([NEWMODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_MODEL_CHANGINGS_T_NEWREVID] FOREIGN KEY ([NEWREVID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_MODEL_CHANGINGS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_DEVICE_MODEL_CHANGINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_MODEL_CHANGINGS_T_DEVICEID]
    ON [dbo].[PR_DEVICE_MODEL_CHANGINGS_T]([DEVICEID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_MODEL_CHANGINGS_T_1]
    ON [dbo].[PR_DEVICE_MODEL_CHANGINGS_T]([VNESHID] ASC, [DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_MODEL_CHANGINGS_T]
    ON [dbo].[PR_DEVICE_MODEL_CHANGINGS_T]([VNESHID] ASC);

