CREATE TABLE [dbo].[PR_DEVICE_SEARCH_DEPARTMENTS] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [GID]            UNIQUEIDENTIFIER NULL,
    [S_CR]           INT              NOT NULL,
    [S_CDT]          DATETIME         NOT NULL,
    [S_MR]           INT              NULL,
    [S_MDT]          DATETIME         NULL,
    [ARC]            INT              NULL,
    [DEVICESEARCHID] INT              NOT NULL,
    [DEPID]          INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_SEARCH_DEPARTMENTS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_SEARCH_DEPARTMENTS_DEVICESEARCHID] FOREIGN KEY ([DEVICESEARCHID]) REFERENCES [dbo].[PR_DEVICE_SEARCH] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SEARCH_DEPARTMENTS]
    ON [dbo].[PR_DEVICE_SEARCH_DEPARTMENTS]([DEVICESEARCHID] ASC);

