CREATE TABLE [dbo].[PR_DEVICE_CHANGINGS_O_DEL] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [DEVCHID] INT              NOT NULL,
    [OPTID]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_CHANGINGS_O_DEL_DEVCHID] FOREIGN KEY ([DEVCHID]) REFERENCES [dbo].[PR_DEVICE_CHANGINGS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_DEVICE_CHANGINGS_O_DEL_OPTID] FOREIGN KEY ([OPTID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_CHANGINGS_O_DEL_1]
    ON [dbo].[PR_DEVICE_CHANGINGS_O_DEL]([DEVCHID] ASC, [OPTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_CHANGINGS_O_DEL]
    ON [dbo].[PR_DEVICE_CHANGINGS_O_DEL]([DEVCHID] ASC);

