CREATE TABLE [dbo].[PR_DEVICE_SW] (
    [ID]          INT      IDENTITY (1, 1) NOT NULL,
    [DEVICEID]    INT      NOT NULL,
    [SWID]        INT      NOT NULL,
    [SWVERSIONID] INT      NOT NULL,
    [OPERID]      INT      NULL,
    [LASTUPDATED] DATETIME NULL,
    [AUTOADDED]   INT      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_SW_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_DEVICE_SW_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_DEVICE_SW_SWVERSIONID] FOREIGN KEY ([SWVERSIONID]) REFERENCES [dbo].[SW_TOOL_VERSIONS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SW_VERID]
    ON [dbo].[PR_DEVICE_SW]([SWVERSIONID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SW_OPERID]
    ON [dbo].[PR_DEVICE_SW]([OPERID] ASC) WHERE ([OPERID] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_SW_2]
    ON [dbo].[PR_DEVICE_SW]([DEVICEID] ASC, [SWID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SW]
    ON [dbo].[PR_DEVICE_SW]([DEVICEID] ASC) WITH (FILLFACTOR = 90);

