CREATE TABLE [dbo].[PR_DEVICE_OPT] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [DEVICEID] INT              NOT NULL,
    [OPTID]    INT              NOT NULL,
    [ARC]      INT              NULL,
    [OPTSN]    NVARCHAR (50)    NULL,
    [QUANTITY] INT              NULL,
    [BOMID]    INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_OPT_BOMID] FOREIGN KEY ([BOMID]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_OPT_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_DEVICE_OPT_OPTID] FOREIGN KEY ([OPTID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_OPT_OPTID]
    ON [dbo].[PR_DEVICE_OPT]([OPTID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_OPT_1]
    ON [dbo].[PR_DEVICE_OPT]([DEVICEID] ASC, [OPTID] ASC, [BOMID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_OPT]
    ON [dbo].[PR_DEVICE_OPT]([DEVICEID] ASC) WITH (FILLFACTOR = 90);

