CREATE TABLE [dbo].[PR_DEVICE_IN_VALUES] (
    [ID]        INT            IDENTITY (1, 1) NOT NULL,
    [DEVICEID]  INT            NOT NULL,
    [PARAMID]   INT            NOT NULL,
    [PACKETID]  INT            NULL,
    [PVALUE]    SQL_VARIANT    NULL,
    [INDEX_STR] NVARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_IN_VALUES_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_DEVICE_IN_VALUES_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_IN_VALUES_PARAMID]
    ON [dbo].[PR_DEVICE_IN_VALUES]([PARAMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_IN_VALUES_PACKETID]
    ON [dbo].[PR_DEVICE_IN_VALUES]([PACKETID] ASC) WHERE ([PACKETID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_IN_VALUES_INDEX_STR]
    ON [dbo].[PR_DEVICE_IN_VALUES]([PARAMID] ASC, [INDEX_STR] ASC) WHERE ([INDEX_STR] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_IN_VALUES]
    ON [dbo].[PR_DEVICE_IN_VALUES]([DEVICEID] ASC, [PARAMID] ASC) WITH (FILLFACTOR = 90);

