CREATE TABLE [dbo].[PR_DOC_BYOPERATIONS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [OPERID]  INT              NOT NULL,
    [PARAMID] INT              NOT NULL,
    [CODE]    NVARCHAR (20)    NOT NULL,
    [FILEID]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DOC_BYOPERATIONS_OPERID_PARAMID]
    ON [dbo].[PR_DOC_BYOPERATIONS]([OPERID] ASC, [PARAMID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DOC_BYOPERATIONS_CODE]
    ON [dbo].[PR_DOC_BYOPERATIONS]([CODE] ASC);

