CREATE TABLE [dbo].[PR_DEVICE_PRIVAT_VALUES] (
    [DEVICEID] INT         NULL,
    [PARAMID]  INT         NULL,
    [PVALUE]   SQL_VARIANT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_PRIVAT_VALUES]
    ON [dbo].[PR_DEVICE_PRIVAT_VALUES]([DEVICEID] ASC, [PARAMID] ASC);

