CREATE TABLE [dbo].[PR_DEVICE_CHANGINGS_DEV] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [DEVCHID]  INT              NOT NULL,
    [DEVICEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_CHANGINGS_DEV_DEVCHID] FOREIGN KEY ([DEVCHID]) REFERENCES [dbo].[PR_DEVICE_CHANGINGS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_DEVICE_CHANGINGS_DEV_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_CHANGINGS_DEV_1]
    ON [dbo].[PR_DEVICE_CHANGINGS_DEV]([DEVCHID] ASC, [DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_CHANGINGS_DEV]
    ON [dbo].[PR_DEVICE_CHANGINGS_DEV]([DEVCHID] ASC);

