CREATE TABLE [dbo].[PR_DEVICE_PROD_SUPP_H] (
    [ID]            BIGINT          IDENTITY (1, 1) NOT NULL,
    [DEVICEID]      INT             NOT NULL,
    [MAPOPERID]     INT             NOT NULL,
    [QUALIFICATION] INT             NOT NULL,
    [ELAPSED]       DECIMAL (12, 2) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_PROD_SUPP_H]
    ON [dbo].[PR_DEVICE_PROD_SUPP_H]([DEVICEID] ASC, [MAPOPERID] ASC);

