CREATE TABLE [dbo].[PR_DEVICE_CHANGINGS_O_RPL] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [DEVCHID] INT              NOT NULL,
    [OPTID1]  INT              NULL,
    [OPTID2]  INT              NULL,
    [QTY]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_DEVICE_CHANGINGS_O_RPL_DEVCHID] FOREIGN KEY ([DEVCHID]) REFERENCES [dbo].[PR_DEVICE_CHANGINGS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_DEVICE_CHANGINGS_O_RPL_OPTID1] FOREIGN KEY ([OPTID1]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_CHANGINGS_O_RPL_OPTID2] FOREIGN KEY ([OPTID2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_CHANGINGS_O_RPL_1]
    ON [dbo].[PR_DEVICE_CHANGINGS_O_RPL]([DEVCHID] ASC, [OPTID1] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_CHANGINGS_O_RPL]
    ON [dbo].[PR_DEVICE_CHANGINGS_O_RPL]([DEVCHID] ASC);

