CREATE TABLE [dbo].[PR_DEVICE] (
    [ID]                      INT              IDENTITY (1, 1) NOT NULL,
    [GID]                     UNIQUEIDENTIFIER NULL,
    [S_CR]                    INT              NULL,
    [S_CDT]                   DATETIME         NULL,
    [S_MR]                    INT              NULL,
    [S_MDT]                   DATETIME         NULL,
    [S_S]                     INT              NULL,
    [SN]                      NVARCHAR (50)    NOT NULL,
    [MODELID]                 INT              NOT NULL,
    [ORDERID]                 INT              NULL,
    [REVID]                   INT              NULL,
    [ORDERROWID]              INT              NULL,
    [ARC]                     INT              NULL,
    [SNC]                     NVARCHAR (50)    NULL,
    [SNN]                     INT              NULL,
    [AUTOGENRID]              INT              NULL,
    [COMPLETED_DT]            DATETIME         NULL,
    [URGENCY]                 INT              NULL,
    [TEMPID]                  INT              NULL,
    [IMPPACKID]               INT              NULL,
    [IMPID]                   INT              NULL,
    [SORDERID]                INT              NULL,
    [IMPPACKDEP]              INT              NULL,
    [SCOMPLETED_DT]           DATETIME         NULL,
    [SHIPPED_DT]              DATETIME         NULL,
    [CREATEDTOORDERID]        INT              NULL,
    [REMARK]                  NTEXT            NULL,
    [FAILED_DT]               DATETIME         NULL,
    [ORDQUANTITY]             INT              NULL,
    [MAPID]                   INT              NULL,
    [SNC2]                    NVARCHAR (50)    NULL,
    [SNN2]                    INT              NULL,
    [OLDSN]                   NVARCHAR (50)    NULL,
    [PRRESTTIME]              DECIMAL (10, 1)  NULL,
    [DECLAREDREADY]           INT              NULL,
    [SHIPPEDBEFORECMPL_DT]    DATETIME         NULL,
    [PARENTID]                INT              NULL,
    [Q_SUFF]                  INT              NULL,
    [Q_PARENT]                INT              NULL,
    [Q_OPERID]                INT              NULL,
    [RESQUANTITY]             INT              NULL,
    [Q_TOPPARENT]             INT              NULL,
    [PRFULLTIME]              DECIMAL (10, 1)  NULL,
    [LASTSRVORDID]            INT              NULL,
    [Q_CREATEDBYOPERSTART]    INT              NULL,
    [CREATEDTOINSTALLROWID]   INT              NULL,
    [STOREDREADINESS]         DECIMAL (10, 1)  NULL,
    [SHIPPINGSTOCK]           NVARCHAR (50)    NULL,
    [SHIPPED_FIRSTTIME]       DATETIME         NULL,
    [SHIPPED_FIRSTTIME_DOCID] INT              NULL,
    [COSTAPPROVAL_START]      DATETIME         NULL,
    [COSTAPPROVAL_SUM]        INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CC_PR_DEVICE_CHECKSN2] CHECK ([dbo].[PR_CHECK_SN2]([SN],[ID],[MODELID])=(0)),
    CONSTRAINT [FK_PR_DEVICE_MAPID] FOREIGN KEY ([MAPID]) REFERENCES [dbo].[PR_MAP] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_ORDERID] FOREIGN KEY ([ORDERID]) REFERENCES [dbo].[PR_PRORDER] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_PR_DEVICE_SORDERID] FOREIGN KEY ([SORDERID]) REFERENCES [dbo].[PR_SUPPLY] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_S_S_ORDERID]
    ON [dbo].[PR_DEVICE]([S_S] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_S_S_COMPL_DT]
    ON [dbo].[PR_DEVICE]([COMPLETED_DT] ASC, [S_S] ASC)
    INCLUDE([ORDERID], [SORDERID], [MAPID]) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SORDERID]
    ON [dbo].[PR_DEVICE]([SORDERID] ASC) WHERE ([SORDERID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SNC_SNN]
    ON [dbo].[PR_DEVICE]([SNC] ASC, [SNN] ASC) WHERE ([SNC] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SNCNN]
    ON [dbo].[PR_DEVICE]([SNC] ASC)
    INCLUDE([MODELID], [SNN]) WHERE ([SNC] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SNC2_SNN2]
    ON [dbo].[PR_DEVICE]([SNC2] ASC, [SNN2] ASC) WHERE ([SNC2] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SN]
    ON [dbo].[PR_DEVICE]([SN] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_SHIPPINGSTOCK]
    ON [dbo].[PR_DEVICE]([SHIPPINGSTOCK] ASC) WHERE ([SHIPPINGSTOCK] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_REVID]
    ON [dbo].[PR_DEVICE]([REVID] ASC) WHERE ([REVID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_Q_CREATEDBYOPERSTART]
    ON [dbo].[PR_DEVICE]([Q_CREATEDBYOPERSTART] ASC) WHERE ([Q_CREATEDBYOPERSTART] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_PARENTID]
    ON [dbo].[PR_DEVICE]([PARENTID] ASC) WHERE ([PARENTID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_ORDERID_COMPLETED_DT]
    ON [dbo].[PR_DEVICE]([ORDERID] ASC, [COMPLETED_DT] ASC)
    INCLUDE([MODELID], [RESQUANTITY]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_ORDERID2]
    ON [dbo].[PR_DEVICE]([ORDERID] ASC)
    INCLUDE([MODELID], [COMPLETED_DT], [FAILED_DT]) WHERE ([ORDERID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_ORDERID]
    ON [dbo].[PR_DEVICE]([ORDERID] ASC) WHERE ([ORDERID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_MODELID_S_S_FAILED_DT]
    ON [dbo].[PR_DEVICE]([MODELID] ASC, [S_S] ASC, [FAILED_DT] ASC)
    INCLUDE([ID], [GID], [S_CR], [S_CDT], [S_MR], [S_MDT], [SN], [ORDERID], [REVID], [COMPLETED_DT], [URGENCY], [IMPPACKID], [SORDERID], [SCOMPLETED_DT], [SHIPPED_DT], [MAPID], [OLDSN], [PRRESTTIME], [DECLAREDREADY], [RESQUANTITY], [PRFULLTIME], [LASTSRVORDID], [STOREDREADINESS], [SHIPPINGSTOCK]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_IMPPACKDEP]
    ON [dbo].[PR_DEVICE]([IMPPACKDEP] ASC) WHERE ([IMPPACKDEP] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_DEVICE_IMP]
    ON [dbo].[PR_DEVICE]([IMPPACKID] ASC, [IMPID] ASC) WHERE ([IMPPACKID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE_ID_MAPID_REVID]
    ON [dbo].[PR_DEVICE]([ID] DESC)
    INCLUDE([MAPID], [REVID]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_DEVICE]
    ON [dbo].[PR_DEVICE]([MODELID] ASC, [SN] ASC) WITH (FILLFACTOR = 90);

