CREATE TABLE [dbo].[PR_EMPL_TO_OPERGR] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [EMPLOYEEID] INT              NOT NULL,
    [GROUPID]    INT              NOT NULL,
    [DBEG]       DATETIME         NULL,
    [DEND]       DATETIME         NULL,
    [DEPID]      INT              NOT NULL,
    [ORDTYPE]    INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_EMPL_TO_OPERGR_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_EMPL_TO_OPERGR_EMPLOYEEID] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PR_EMPL_TO_OPERGR_GROUPID] FOREIGN KEY ([GROUPID]) REFERENCES [dbo].[PR_OPERATIONS_GR] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_EMPL_TO_OPERGR_DEPID_EMPLOYEEID_GROUPID_DBEG_DEND]
    ON [dbo].[PR_EMPL_TO_OPERGR]([DEPID] ASC)
    INCLUDE([EMPLOYEEID], [GROUPID], [DBEG], [DEND]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_EMPL_TO_OPERGR]
    ON [dbo].[PR_EMPL_TO_OPERGR]([EMPLOYEEID] ASC, [DEPID] ASC, [GROUPID] ASC)
    INCLUDE([DBEG], [DEND]) WITH (FILLFACTOR = 90);

