CREATE TABLE [dbo].[PR_FP_PLANNING_SETTINGS_T] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NOT NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [PARAMID]   INT              NOT NULL,
    [ORDERPOS]  INT              NULL,
    [SHCAPTION] NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_FP_PLANNING_SETTINGS_T_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_FP_PLANNING_SETTINGS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_FP_PLANNING_SETTINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_FP_PLANNING_SETTINGS_T1]
    ON [dbo].[PR_FP_PLANNING_SETTINGS_T]([VNESHID] ASC, [PARAMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_FP_PLANNING_SETTINGS_T]
    ON [dbo].[PR_FP_PLANNING_SETTINGS_T]([VNESHID] ASC);

