CREATE TABLE [dbo].[PR_FP_PLANNING_SETTINGS_ST] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NOT NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [VNESHID]       INT              NOT NULL,
    [POSORDER]      INT              NOT NULL,
    [OPERID]        INT              NOT NULL,
    [OPERSTATE]     INT              NOT NULL,
    [VISIBLEINLIST] INT              NOT NULL,
    [STCOLOR]       INT              NOT NULL,
    [NAME]          NVARCHAR (50)    NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_FP_PLANNING_SETTINGS_ST_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_FP_PLANNING_SETTINGS_ST_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_FP_PLANNING_SETTINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_FP_PLANNING_SETTINGS_ST1]
    ON [dbo].[PR_FP_PLANNING_SETTINGS_ST]([VNESHID] ASC, [OPERID] ASC, [OPERSTATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_FP_PLANNING_SETTINGS_ST]
    ON [dbo].[PR_FP_PLANNING_SETTINGS_ST]([VNESHID] ASC);

