CREATE TABLE [dbo].[PR_FP_PLANNING_SETTINGS] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NOT NULL,
    [S_S]           INT              NOT NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [OPERTASKID]    INT              NULL,
    [OPERDRAWID]    INT              NULL,
    [OPERPREPAREID] INT              NULL,
    [MTID]          INT              NULL,
    [NEWSETTINGS]   INT              NULL,
    [ALLOPEN_OP]    INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_FP_PLANNING_SETTINGS_OPERDRAWID] FOREIGN KEY ([OPERDRAWID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_FP_PLANNING_SETTINGS_OPERPREPAREID] FOREIGN KEY ([OPERPREPAREID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_FP_PLANNING_SETTINGS_OPERTASKID] FOREIGN KEY ([OPERTASKID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_FP_PLANNING_SETTINGS_MTID]
    ON [dbo].[PR_FP_PLANNING_SETTINGS]([MTID] ASC);

