CREATE TABLE [dbo].[PR_IMP_PACKET_T] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [VNESHID]         INT            NOT NULL,
    [DEVICEID]        INT            NULL,
    [IMPSN]           NVARCHAR (100) NULL,
    [IMPMODEL]        NVARCHAR (250) NULL,
    [IMPSTATE]        INT            NULL,
    [IMPERROR]        NVARCHAR (512) NULL,
    [TEMPID]          INT            NULL,
    [TEMPMODELID]     INT            NULL,
    [IMPCODE]         NVARCHAR (50)  NULL,
    [IMPREV]          NVARCHAR (200) NULL,
    [TEMPREVID]       INT            NULL,
    [UNIQSNMODELTYPE] INT            NULL,
    [IMPCOMPLETED_DT] DATETIME       NULL,
    [RESQUANTITY]     INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_IMP_PACKET_T_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_IMP_PACKET_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_IMP_PACKET] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_IMP_PACKET_T_DEVICEID]
    ON [dbo].[PR_IMP_PACKET_T]([DEVICEID] ASC) WHERE ([DEVICEID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_IMP_PACKET_T]
    ON [dbo].[PR_IMP_PACKET_T]([VNESHID] ASC, [TEMPID] ASC) WITH (FILLFACTOR = 90);

