CREATE TABLE [dbo].[PR_INHERIT_PARAMS_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [PARAMID]  INT              NULL,
    [ACTIONID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_INHERIT_PARAMS_T_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_INHERIT_PARAMS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_INHERIT_PARAMS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_INHERIT_PARAMS_T_PARAMID2]
    ON [dbo].[PR_INHERIT_PARAMS_T]([PARAMID] ASC) WHERE ([PARAMID] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_INHERIT_PARAMS_T_PARAMID]
    ON [dbo].[PR_INHERIT_PARAMS_T]([VNESHID] ASC, [PARAMID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_INHERIT_PARAMS_T]
    ON [dbo].[PR_INHERIT_PARAMS_T]([VNESHID] ASC) WITH (FILLFACTOR = 90);

