CREATE TABLE [dbo].[PR_IMP_TRANS_PRE] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [TAGNAME]     NVARCHAR (200)   NOT NULL,
    [TAGOLDVALUE] NVARCHAR (200)   NOT NULL,
    [TAGNEWVALUE] NVARCHAR (200)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_IMP_TRANS_PRE_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_IMP_TRANS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_IMP_TRANS_PRE]
    ON [dbo].[PR_IMP_TRANS_PRE]([VNESHID] ASC);

