CREATE TABLE [dbo].[PR_IMP_TRANS_COL] (
    [ID]         INT            IDENTITY (1, 1) NOT NULL,
    [VNESHID]    INT            NOT NULL,
    [COLUMNNAME] NVARCHAR (100) NOT NULL,
    [PARAMID]    INT            NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_IMP_TRANS_COL_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_IMP_TRANS_COL_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_IMP_TRANS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_IMP_TRANS_COL]
    ON [dbo].[PR_IMP_TRANS_COL]([VNESHID] ASC);

