CREATE TABLE [dbo].[PR_IMP_TRANS_ADDT] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [VNESHID] INT              NOT NULL,
    [MTID]    INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_IMP_TRANS_ADDT_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_PR_IMP_TRANS_ADDT_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_IMP_TRANS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_IMP_TRANS_ADDT]
    ON [dbo].[PR_IMP_TRANS_ADDT]([VNESHID] ASC);

