CREATE TABLE [dbo].[PR_IMP_TRANS_SYN] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [VNESHID]   INT              NOT NULL,
    [MODELNAME] NVARCHAR (100)   NOT NULL,
    [MODELID]   INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_IMP_TRANS_SYN_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_IMP_TRANS_SYN_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_IMP_TRANS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_IMP_TRANS_SYN_3]
    ON [dbo].[PR_IMP_TRANS_SYN]([MODELNAME] ASC, [VNESHID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_IMP_TRANS_SYN]
    ON [dbo].[PR_IMP_TRANS_SYN]([VNESHID] ASC);

