CREATE TABLE [dbo].[PR_LIST_PARAMS_CACHE] (
    [DEVICEID] INT         NOT NULL,
    [PARAMID]  INT         NOT NULL,
    [PVALUE]   SQL_VARIANT NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_PR_LIST_PARAMS_CACHE_DEVICEID_PARAMID]
    ON [dbo].[PR_LIST_PARAMS_CACHE]([DEVICEID] ASC, [PARAMID] ASC) WITH (FILLFACTOR = 90);

