CREATE TABLE [dbo].[PR_MODELTYPE_SHARING_COUNTRIES_EXCEPT_CUST] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [GID]                UNIQUEIDENTIFIER NOT NULL,
    [S_CR]               INT              NOT NULL,
    [S_CDT]              DATETIME         NOT NULL,
    [S_MR]               INT              NULL,
    [S_MDT]              DATETIME         NULL,
    [ARC]                INT              NULL,
    [MTSHARINGCOUNTRYID] INT              NOT NULL,
    [CUSTID]             INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_SHARING_COUNTRIES_EXCEPT_CUST_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_SHARING_COUNTRIES_EXCEPT_CUST_MTSHARINGCOUNTRYID] FOREIGN KEY ([MTSHARINGCOUNTRYID]) REFERENCES [dbo].[PR_MODELTYPE_SHARING_COUNTRIES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_SHARING_COUNTRIES_EXCEPT_CUST]
    ON [dbo].[PR_MODELTYPE_SHARING_COUNTRIES_EXCEPT_CUST]([MTSHARINGCOUNTRYID] ASC);

