CREATE TABLE [dbo].[PR_MODELTYPE_PARAMS] (
    [ID]               INT              IDENTITY (1, 1) NOT NULL,
    [GID]              UNIQUEIDENTIFIER NULL,
    [S_CR]             INT              NULL,
    [S_CDT]            DATETIME         NULL,
    [S_MR]             INT              NULL,
    [S_MDT]            DATETIME         NULL,
    [TYPEID]           INT              NOT NULL,
    [NAME]             NVARCHAR (300)   NOT NULL,
    [DESCRIPTION]      NTEXT            NULL,
    [PARAMKIND]        INT              NOT NULL,
    [DATATYPE]         INT              NOT NULL,
    [SYMBOL]           NVARCHAR (100)   NULL,
    [UNITSTR]          NVARCHAR (50)    NULL,
    [SHAREPRM]         INT              NULL,
    [ARC]              INT              NULL,
    [OLDGR]            NVARCHAR (220)   NULL,
    [PGROUP]           INT              NOT NULL,
    [ENUMVALUES]       NVARCHAR (2000)  NULL,
    [USEINLIST]        INT              NULL,
    [LINKCODE]         NVARCHAR (50)    NULL,
    [onlyone_LINKCODE] AS               (case when [LINKCODE] IS NOT NULL then (-1) else [ID] end),
    [DENYIMPORT]       INT              NULL,
    [ALLOWEDIT]        INT              NULL,
    [USEINOPLIST]      INT              NULL,
    [SWGROUPTAG]       NVARCHAR (10)    NULL,
    [USEINRELIST]      INT              DEFAULT ((0)) NULL,
    [USEINEQLIST]      INT              DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_PARAMS_PGROUP] FOREIGN KEY ([PGROUP]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS_GR] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_PARAMS_TYPEID] FOREIGN KEY ([TYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_USEINOPLIST]
    ON [dbo].[PR_MODELTYPE_PARAMS]([TYPEID] ASC, [USEINOPLIST] ASC)
    INCLUDE([DATATYPE]) WHERE ([USEINOPLIST] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_USEINLIST]
    ON [dbo].[PR_MODELTYPE_PARAMS]([TYPEID] ASC, [USEINLIST] ASC)
    INCLUDE([DATATYPE]) WHERE ([USEINLIST] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_TYPEID_PGROUP_GID_NAME_DATATYPE_PARAMKIND_SHAREPRM]
    ON [dbo].[PR_MODELTYPE_PARAMS]([TYPEID] ASC)
    INCLUDE([PGROUP], [GID], [NAME], [DATATYPE], [PARAMKIND], [SHAREPRM]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_TYPEID_DATATYPE]
    ON [dbo].[PR_MODELTYPE_PARAMS]([TYPEID] ASC, [DATATYPE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_LC]
    ON [dbo].[PR_MODELTYPE_PARAMS]([TYPEID] ASC, [LINKCODE] ASC, [onlyone_LINKCODE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_GID]
    ON [dbo].[PR_MODELTYPE_PARAMS]([GID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_2]
    ON [dbo].[PR_MODELTYPE_PARAMS]([TYPEID] ASC, [NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS]
    ON [dbo].[PR_MODELTYPE_PARAMS]([TYPEID] ASC);

