CREATE TABLE [dbo].[PR_MODEL_SHARINGR] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [MODELID]      INT              NOT NULL,
    [DEPARTMENTID] INT              NOT NULL,
    [RULETYPE]     INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_SHARINGR_DEPARTMENTID] FOREIGN KEY ([DEPARTMENTID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_MODEL_SHARINGR_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_SHARINGR_RULETYPE]
    ON [dbo].[PR_MODEL_SHARINGR]([RULETYPE] ASC)
    INCLUDE([MODELID], [DEPARTMENTID]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODEL_SHARINGR_GID]
    ON [dbo].[PR_MODEL_SHARINGR]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_SHARINGR]
    ON [dbo].[PR_MODEL_SHARINGR]([MODELID] ASC);

