CREATE TABLE [dbo].[PR_MODELS_NOGC_ACCESS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NOT NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [MODELID]   INT              NOT NULL,
    [USERGROUP] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELS_NOGC_ACCESS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_MODELS_NOGC_ACCESS_USERGROUP] FOREIGN KEY ([USERGROUP]) REFERENCES [dbo].[DEF_USERS] ([ID])
);

