CREATE TABLE [dbo].[PR_MODELTYPE_COMMON_PARAMS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [TYPEID]   INT              NOT NULL,
    [PARAMID]  INT              NOT NULL,
    [OPTIONID] INT              NULL,
    [VALUE]    SQL_VARIANT      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_PARAMS_OPTIONID] FOREIGN KEY ([OPTIONID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_PARAMS_TYPEID] FOREIGN KEY ([TYPEID]) REFERENCES [dbo].[PR_MODELTYPE_COMMON] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_PARAMS_GID]
    ON [dbo].[PR_MODELTYPE_COMMON_PARAMS]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_PARAMS_2]
    ON [dbo].[PR_MODELTYPE_COMMON_PARAMS]([TYPEID] ASC, [PARAMID] ASC, [OPTIONID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_PARAMS]
    ON [dbo].[PR_MODELTYPE_COMMON_PARAMS]([TYPEID] ASC) WITH (FILLFACTOR = 90);

