CREATE TABLE [dbo].[PR_MPL_GROUP_ACCESSS_T] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NOT NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [GROUPID]   INT              NOT NULL,
    [COUNTRYID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MPL_GROUP_ACCESSS_T_COUNTRYID] FOREIGN KEY ([COUNTRYID]) REFERENCES [dbo].[COM_COUNTRIES] ([ID]),
    CONSTRAINT [FK_PR_MPL_GROUP_ACCESSS_T_GROUPID] FOREIGN KEY ([GROUPID]) REFERENCES [dbo].[PR_MPL_GROUP_ACCESSS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MPL_GROUP_ACCESSS_T]
    ON [dbo].[PR_MPL_GROUP_ACCESSS_T]([GROUPID] ASC);

