CREATE TABLE [dbo].[PR_MODELTYPE_OPTIONS_REQ] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [VNESHID]  INT              NOT NULL,
    [REQOPTID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_REQ_REQOPTID] FOREIGN KEY ([REQOPTID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_REQ_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_REQ]
    ON [dbo].[PR_MODELTYPE_OPTIONS_REQ]([VNESHID] ASC) WITH (FILLFACTOR = 90);

