CREATE TABLE [dbo].[PR_MODEL_COMPAT_WITH_OPT] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [OPTID]   INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_COMPAT_WITH_OPT_OPTID] FOREIGN KEY ([OPTID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODEL_COMPAT_WITH_OPT_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODEL_COMPAT] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_COMPAT_WITH_OPT]
    ON [dbo].[PR_MODEL_COMPAT_WITH_OPT]([VNESHID] ASC);

