CREATE TABLE [dbo].[PR_MODELTYPE_COMMON_EQ] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [MTID]        INT              NOT NULL,
    [EQID]        INT              NOT NULL,
    [EQTYPEID]    INT              NOT NULL,
    [ONLYOPTION]  INT              NULL,
    [EQMODELID]   INT              NULL,
    [ONLYOPTION2] INT              NULL,
    [ONLYOPTION3] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_EQ_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_EQ_EQMODELID] FOREIGN KEY ([EQMODELID]) REFERENCES [dbo].[EQ_MODELS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_EQ_EQTYPEID] FOREIGN KEY ([EQTYPEID]) REFERENCES [dbo].[EQ_TYPES] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_EQ_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE_COMMON] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_EQ_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_EQ_ONLYOPTION2] FOREIGN KEY ([ONLYOPTION2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_EQ_ONLYOPTION3] FOREIGN KEY ([ONLYOPTION3]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_EQ_OPTS]
    ON [dbo].[PR_MODELTYPE_COMMON_EQ]([MTID] ASC, [EQID] ASC, [ONLYOPTION] ASC, [ONLYOPTION2] ASC, [ONLYOPTION3] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_EQ_GID]
    ON [dbo].[PR_MODELTYPE_COMMON_EQ]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_EQ]
    ON [dbo].[PR_MODELTYPE_COMMON_EQ]([MTID] ASC);

