CREATE TABLE [dbo].[PR_MODEL_REQOPTIONGR] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [MODELID]     INT              NOT NULL,
    [OPTIONGRID]  INT              NOT NULL,
    [OPTIONGRID2] INT              NULL,
    [OPTIONGRID3] INT              NULL,
    [OPTIONGRID4] INT              NULL,
    [OPTIONGRID5] INT              NULL,
    [CRMGUID]     UNIQUEIDENTIFIER NULL,
    [TS]          ROWVERSION       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID] FOREIGN KEY ([OPTIONGRID]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID2] FOREIGN KEY ([OPTIONGRID2]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID3] FOREIGN KEY ([OPTIONGRID3]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID4] FOREIGN KEY ([OPTIONGRID4]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID5] FOREIGN KEY ([OPTIONGRID5]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_REQOPTIONGR]
    ON [dbo].[PR_MODEL_REQOPTIONGR]([MODELID] ASC) WITH (FILLFACTOR = 90);

