CREATE TABLE [dbo].[PR_MODEL_COMPAT_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [MODELID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_COMPAT_T_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_MODEL_COMPAT_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODEL_COMPAT] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODEL_COMPAT_T_UNIQUE]
    ON [dbo].[PR_MODEL_COMPAT_T]([VNESHID] ASC, [MODELID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_COMPAT_T_MODELID]
    ON [dbo].[PR_MODEL_COMPAT_T]([MODELID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_COMPAT_T]
    ON [dbo].[PR_MODEL_COMPAT_T]([VNESHID] ASC);

