CREATE TABLE [dbo].[PR_MODELTYPE_BOM] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [MTID]         INT              NOT NULL,
    [DESCRIPTION]  NTEXT            NULL,
    [NAME]         NVARCHAR (100)   NOT NULL,
    [BOMMTID]      INT              NOT NULL,
    [AORDER]       INT              NULL,
    [USEINLIST]    INT              NULL,
    [DBLINSTALL]   INT              NULL,
    [SPGROUP]      INT              NULL,
    [SHAREBOM]     INT              NULL,
    [MULTIPLY_QTY] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_BOM_BOMMTID] FOREIGN KEY ([BOMMTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_PR_MT_BOM_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MT_BOM]
    ON [dbo].[PR_MODELTYPE_BOM]([MTID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_BOM_USEINLIST]
    ON [dbo].[PR_MODELTYPE_BOM]([MTID] ASC, [USEINLIST] ASC) WHERE ([USEINLIST] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_BOM_GID]
    ON [dbo].[PR_MODELTYPE_BOM]([GID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_BOM]
    ON [dbo].[PR_MODELTYPE_BOM]([MTID] ASC, [NAME] ASC) WITH (FILLFACTOR = 90);

