CREATE TABLE [dbo].[PR_MODELS] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [GID]            UNIQUEIDENTIFIER NULL,
    [S_S]            INT              NULL,
    [S_CR]           INT              NULL,
    [S_CDT]          DATETIME         NULL,
    [S_MR]           INT              NULL,
    [S_MDT]          DATETIME         NULL,
    [NAME]           NVARCHAR (200)   NOT NULL,
    [TYPEID]         INT              NOT NULL,
    [SNMASK]         NVARCHAR (100)   NULL,
    [DESCRIPTION]    NTEXT            NULL,
    [CODE]           NVARCHAR (16)    NOT NULL,
    [ARC]            INT              NULL,
    [SHARETOALL]     INT              NULL,
    [DESCSTR]        NVARCHAR (300)   NULL,
    [NAVPOST]        INT              NULL,
    [CMODE]          INT              NULL,
    [FIRSTSNN]       INT              NULL,
    [MPICT]          IMAGE            NULL,
    [OLDCODE]        NVARCHAR (20)    NULL,
    [NEWCODE]        NVARCHAR (20)    NULL,
    [SNPMODE]        INT              NULL,
    [SNPMIN]         INT              NULL,
    [NONAVSNTRACK]   INT              NULL,
    [SNMASK2]        NVARCHAR (50)    NULL,
    [SNPMIN2]        INT              NULL,
    [SNPRM]          NVARCHAR (50)    NULL,
    [DEPID]          INT              NOT NULL,
    [MODELGROUP]     NVARCHAR (200)   NULL,
    [TAGS]           NVARCHAR (300)   NULL,
    [PRTYPE]         INT              NULL,
    [PARENTMODELID]  INT              NULL,
    [MODELGROUPID]   INT              NULL,
    [REPLACEX]       INT              NULL,
    [SPEC]           NVARCHAR (200)   NULL,
    [CUSTOM4GROUP]   INT              NULL,
    [CUSTOM4ID]      INT              NULL,
    [SNPMASK]        NVARCHAR (50)    NULL,
    [SNP4MODEL]      INT              NULL,
    [S_S2]           INT              NULL,
    [OPERCRMODE]     INT              NULL,
    [CRMGUID]        UNIQUEIDENTIFIER NULL,
    [TS]             ROWVERSION       NULL,
    [IN2FAILSTATREP] INT              NULL,
    [REMARK]         NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELS_CUSTOM4GROUP] FOREIGN KEY ([CUSTOM4GROUP]) REFERENCES [dbo].[COM_CUST_GROUP] ([ID]),
    CONSTRAINT [FK_PR_MODELS_CUSTOM4ID] FOREIGN KEY ([CUSTOM4ID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_PR_MODELS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_MODELS_MODELGROUPID] FOREIGN KEY ([MODELGROUPID]) REFERENCES [dbo].[PR_MODEL_GROUP] ([ID]),
    CONSTRAINT [FK_PR_MODELS_PARENTMODELID] FOREIGN KEY ([PARENTMODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_MODELS_TYPEID] FOREIGN KEY ([TYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELS_TYPEID]
    ON [dbo].[PR_MODELS]([TYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELS_SHARETOALL]
    ON [dbo].[PR_MODELS]([SHARETOALL] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELS_NAME]
    ON [dbo].[PR_MODELS]([NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELS_MODELGROUPID]
    ON [dbo].[PR_MODELS]([MODELGROUPID] ASC) WHERE ([MODELGROUPID] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELS_ID_SHARETOALL]
    ON [dbo].[PR_MODELS]([ID] DESC)
    INCLUDE([SHARETOALL]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELS_ID_MODELGROUPID]
    ON [dbo].[PR_MODELS]([ID] DESC)
    INCLUDE([MODELGROUPID]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELS_GID]
    ON [dbo].[PR_MODELS]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELS_DEPID]
    ON [dbo].[PR_MODELS]([DEPID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELS]
    ON [dbo].[PR_MODELS]([CODE] ASC);

