CREATE TABLE [dbo].[PR_MODELTYPE_OPTION_GR] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [TYPEID]    INT              NOT NULL,
    [NAME]      NVARCHAR (300)   NOT NULL,
    [CODE]      NVARCHAR (20)    NOT NULL,
    [SP_GROUP]  INT              NULL,
    [USEINLIST] INT              NULL,
    [CRMGUID]   UNIQUEIDENTIFIER NULL,
    [TS]        ROWVERSION       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_MODELTYPE_OPTION_GR_TYPEID] FOREIGN KEY ([TYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTION_GR]
    ON [dbo].[PR_MODELTYPE_OPTION_GR]([TYPEID] ASC) WITH (FILLFACTOR = 90);

