CREATE TABLE [dbo].[PR_MODEL_OPTIONS] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [GID]                UNIQUEIDENTIFIER NOT NULL,
    [S_CR]               INT              NOT NULL,
    [S_CDT]              DATETIME         NOT NULL,
    [S_MR]               INT              NULL,
    [S_MDT]              DATETIME         NULL,
    [ARC]                INT              NULL,
    [MODELID]            INT              NOT NULL,
    [OPTIONID]           INT              NOT NULL,
    [PREDEFINEDOPT]      INT              NULL,
    [OVERPTYPE]          INT              NULL,
    [CMP_OUT2]           NVARCHAR (200)   NULL,
    [CUSTOM4GROUP]       INT              NULL,
    [CUSTOM4ID]          INT              NULL,
    [PRTYPE]             INT              NULL,
    [CMP_REQ]            NVARCHAR (200)   NULL,
    [CMP_BLOCK]          NVARCHAR (200)   NULL,
    [CMP_OUT2_OVERRIDE]  INT              NULL,
    [CMP_REQ_OVERRIDE]   INT              NULL,
    [CMP_BLOCK_OVERRIDE] INT              NULL,
    [PRTYPE_OVERRIDE]    INT              NULL,
    [CRMGUID]            UNIQUEIDENTIFIER NULL,
    [TS]                 ROWVERSION       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_MODEL_OPTIONS_CUSTOM4GROUP] FOREIGN KEY ([CUSTOM4GROUP]) REFERENCES [dbo].[COM_CUST_GROUP] ([ID]),
    CONSTRAINT [FK_PR_MODEL_OPTIONS_CUSTOM4ID] FOREIGN KEY ([CUSTOM4ID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_PR_MODEL_OPTIONS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_MODEL_OPTIONS_OPTIONID] FOREIGN KEY ([OPTIONID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODEL_OPTIONS_UNI]
    ON [dbo].[PR_MODEL_OPTIONS]([MODELID] ASC, [OPTIONID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODEL_OPTIONS_GID]
    ON [dbo].[PR_MODEL_OPTIONS]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_OPTIONS]
    ON [dbo].[PR_MODEL_OPTIONS]([MODELID] ASC) WITH (FILLFACTOR = 90);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PR_MODEL_OPTIONS] TO [IPG-DOMAIN\IPGL_Integr_MSCRM]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[PR_MODEL_OPTIONS] TO [EMEA\DEPCS]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PR_MODEL_OPTIONS] TO [IPG-DOMAIN\IPGL_Integr_MSCRM]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[PR_MODEL_OPTIONS] TO [EMEA\DEPCS]
    AS [dbo];

