CREATE TABLE [dbo].[PR_MAP_STAGE] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [NAME]     NVARCHAR (255)   NOT NULL,
    [MAPID]    INT              NOT NULL,
    [SCHEME_Y] INT              NULL,
    [SCHEME_H] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MAP_STAGE_MAPID] FOREIGN KEY ([MAPID]) REFERENCES [dbo].[PR_MAP] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MAP_STAGE]
    ON [dbo].[PR_MAP_STAGE]([MAPID] ASC);


GO
CREATE TRIGGER [dbo].[TR_PR_MAP_STAGE_DEL]
    ON PR_MAP_STAGE FOR DELETE
AS
    UPDATE PR_MAP_OPER SET MAPSTAGEID = NULL WHERE MAPSTAGEID IN (SELECT ID FROM DELETED)