CREATE TABLE [dbo].[PR_MODELTYPE_OPTION_GR_T] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [VNESHID]   INT              NOT NULL,
    [BOMITEMID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_OPTION_GR_T_BOMITEMID] FOREIGN KEY ([BOMITEMID]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTION_GR_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTION_GR_T]
    ON [dbo].[PR_MODELTYPE_OPTION_GR_T]([VNESHID] ASC);

