CREATE TABLE [dbo].[PR_MH_ASSIGNMENT_T] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [VNESHID]      INT              NOT NULL,
    [REVID]        INT              NOT NULL,
    [MODELID]      INT              NOT NULL,
    [OPERATION]    INT              NOT NULL,
    [CURRENTVALUE] DECIMAL (10, 1)  NULL,
    [NEWVALUE]     DECIMAL (10, 1)  NULL,
    [REMARK]       NVARCHAR (200)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MH_ASSIGNMENT_T_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_MH_ASSIGNMENT_T_OPERATION] FOREIGN KEY ([OPERATION]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_MH_ASSIGNMENT_T_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_PR_MH_ASSIGNMENT_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MH_ASSIGNMENT] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MH_ASSIGNMENT_T_UNIQUE]
    ON [dbo].[PR_MH_ASSIGNMENT_T]([VNESHID] ASC, [MODELID] ASC, [REVID] ASC, [OPERATION] ASC) WHERE ([ID]>(593550));


GO
CREATE NONCLUSTERED INDEX [IX_PR_MH_ASSIGNMENT_T]
    ON [dbo].[PR_MH_ASSIGNMENT_T]([VNESHID] ASC) WITH (FILLFACTOR = 90);

