CREATE TABLE [dbo].[PR_MODELTYPE_COMMON] (
    [ID]    INT              IDENTITY (1, 1) NOT NULL,
    [GID]   UNIQUEIDENTIFIER NOT NULL,
    [S_CR]  INT              NOT NULL,
    [S_CDT] DATETIME         NOT NULL,
    [S_MR]  INT              NULL,
    [S_MDT] DATETIME         NULL,
    [ARC]   INT              NULL,
    [MTID]  INT              NOT NULL,
    [DEPID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_COMMON_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_MTID_ID]
    ON [dbo].[PR_MODELTYPE_COMMON]([MTID] ASC)
    INCLUDE([ID]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_MTID_DEPID]
    ON [dbo].[PR_MODELTYPE_COMMON]([MTID] ASC, [DEPID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_COMMON_GID]
    ON [dbo].[PR_MODELTYPE_COMMON]([GID] ASC);

