CREATE TABLE [dbo].[PR_MODELTYPE_BOM_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [VNESHID] INT              NOT NULL,
    [BOMMTID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_BOM_T_BOMMTID] FOREIGN KEY ([BOMMTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_BOM_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_BOM_T_GID]
    ON [dbo].[PR_MODELTYPE_BOM_T]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_BOM_T]
    ON [dbo].[PR_MODELTYPE_BOM_T]([VNESHID] ASC);

