CREATE TABLE [dbo].[PR_MODEL_GROUP] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GID]    UNIQUEIDENTIFIER NULL,
    [S_CR]   INT              NOT NULL,
    [S_CDT]  DATETIME         NOT NULL,
    [S_MR]   INT              NULL,
    [S_MDT]  DATETIME         NULL,
    [ARC]    INT              NULL,
    [DEPID]  INT              NOT NULL,
    [NAME]   NVARCHAR (200)   NOT NULL,
    [REMARK] NTEXT            NULL,
    [NITDR]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_GROUP_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODEL_GROUPS]
    ON [dbo].[PR_MODEL_GROUP]([DEPID] ASC, [NAME] ASC);

