CREATE TABLE [dbo].[PR_MODELTYPE_OPTIONS_REQM] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [VNESHID]    INT              NOT NULL,
    [REQMODELID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_REQM_REQMODELID] FOREIGN KEY ([REQMODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_REQM_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_REQM]
    ON [dbo].[PR_MODELTYPE_OPTIONS_REQM]([VNESHID] ASC);

