CREATE TABLE [dbo].[PR_MODELTYPE_SHARING_DEPS] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [MTSHARINGID] INT              NOT NULL,
    [DEPID]       INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_SHARING_DEPS_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_SHARING_DEPS_MTSHARINGID] FOREIGN KEY ([MTSHARINGID]) REFERENCES [dbo].[PR_MODELTYPE_SHARING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_SHARING_DEPS]
    ON [dbo].[PR_MODELTYPE_SHARING_DEPS]([MTSHARINGID] ASC);

