CREATE TABLE [dbo].[PR_MODEL_COMPAT_SETTINGS_MT] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [MTID]    INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_COMPAT_SETTINGS_MT_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_PR_MODEL_COMPAT_SETTINGS_MT_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODEL_COMPAT_SETTINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_COMPAT_SETTINGS_MT]
    ON [dbo].[PR_MODEL_COMPAT_SETTINGS_MT]([VNESHID] ASC);

