CREATE TABLE [dbo].[PR_MODELTYPE_PARAMS_GR] (
    [ID]     INT              IDENTITY (1, 1) NOT NULL,
    [GID]    UNIQUEIDENTIFIER NOT NULL,
    [S_CR]   INT              NOT NULL,
    [S_CDT]  DATETIME         NOT NULL,
    [S_MR]   INT              NULL,
    [S_MDT]  DATETIME         NULL,
    [ARC]    INT              NULL,
    [TYPEID] INT              NOT NULL,
    [NAME]   NVARCHAR (300)   NOT NULL,
    [DEPID]  INT              NOT NULL,
    [REMARK] NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_PARAMS_GR_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_PARAMS_GR_TYPEID] FOREIGN KEY ([TYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_GR_ID_DEPID_NAME]
    ON [dbo].[PR_MODELTYPE_PARAMS_GR]([ID] ASC)
    INCLUDE([DEPID], [NAME]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_GR_GID]
    ON [dbo].[PR_MODELTYPE_PARAMS_GR]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_GR]
    ON [dbo].[PR_MODELTYPE_PARAMS_GR]([TYPEID] ASC) WITH (FILLFACTOR = 90);

