CREATE TABLE [dbo].[PR_MT_CHANGE_NOTIFY_EMPL] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MT_CHANGE_NOTIFY_EMPL_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PR_MT_CHANGE_NOTIFY_EMPL_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MT_CHANGE_NOTIFY] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MT_CHANGE_NOTIFY_EMPL]
    ON [dbo].[PR_MT_CHANGE_NOTIFY_EMPL]([VNESHID] ASC);

