CREATE TABLE [dbo].[PR_MODELTYPE_SHARINGR] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NOT NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [VNESHID]      INT              NOT NULL,
    [DEPARTMENTID] INT              NOT NULL,
    [RULETYPE]     INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_SHARINGR_DEPARTMENTID] FOREIGN KEY ([DEPARTMENTID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_SHARINGR_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_SHARINGR_GID]
    ON [dbo].[PR_MODELTYPE_SHARINGR]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_SHARINGR_3]
    ON [dbo].[PR_MODELTYPE_SHARINGR]([DEPARTMENTID] ASC, [RULETYPE] ASC)
    INCLUDE([VNESHID]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_SHARINGR]
    ON [dbo].[PR_MODELTYPE_SHARINGR]([VNESHID] ASC);

