CREATE TABLE [dbo].[PR_MODELTYPE_SHARING_COUNTRIES] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [MTSHARINGID] INT              NOT NULL,
    [COUNTRYID]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_SHARING_COUNTRIES_COUNTRYID] FOREIGN KEY ([COUNTRYID]) REFERENCES [dbo].[COM_COUNTRIES] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_SHARING_COUNTRIES_MTSHARINGID] FOREIGN KEY ([MTSHARINGID]) REFERENCES [dbo].[PR_MODELTYPE_SHARING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_SHARING_COUNTRIES]
    ON [dbo].[PR_MODELTYPE_SHARING_COUNTRIES]([MTSHARINGID] ASC);

