CREATE TABLE [dbo].[PR_MODELTYPE_OPTIONS_FILES] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [OPTID]       INT              NOT NULL,
    [FILENAME]    NVARCHAR (255)   NOT NULL,
    [FILESIZE]    INT              NOT NULL,
    [FILEDESC]    NTEXT            NULL,
    [FILEDATE]    DATETIME         NOT NULL,
    [FILEBLOB]    IMAGE            NULL,
    [FILEGROUP]   INT              NULL,
    [SWID]        INT              NULL,
    [FILESHOWIN]  INT              NULL,
    [FILESHOWIN2] INT              NULL,
    [CRMGUID]     UNIQUEIDENTIFIER NULL,
    [TS]          ROWVERSION       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_FILES_OPTID] FOREIGN KEY ([OPTID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_FILES_SWID] FOREIGN KEY ([SWID]) REFERENCES [dbo].[SW_TOOLS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_FILES]
    ON [dbo].[PR_MODELTYPE_OPTIONS_FILES]([OPTID] ASC);

