CREATE TABLE [dbo].[PR_MODELTYPE_OPTIONS_BOM] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [TYPEID]    INT              NOT NULL,
    [BOMITEM]   INT              NOT NULL,
    [OPTIONID]  INT              NULL,
    [MODELID]   INT              NOT NULL,
    [OPTIONID2] INT              NULL,
    [OPTIONID3] INT              NULL,
    [QTY]       DECIMAL (10, 4)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_BOM_BOMITEM] FOREIGN KEY ([BOMITEM]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_BOM_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_BOM_OPTIONID] FOREIGN KEY ([OPTIONID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_BOM_OPTIONID2] FOREIGN KEY ([OPTIONID2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_BOM_OPTIONID3] FOREIGN KEY ([OPTIONID3]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_OPTIONS_BOM_TYPEID] FOREIGN KEY ([TYPEID]) REFERENCES [dbo].[PR_MODELTYPE_COMMON] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_BOM_TYPEID_MODELID]
    ON [dbo].[PR_MODELTYPE_OPTIONS_BOM]([TYPEID] ASC)
    INCLUDE([MODELID]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_BOM_OPTIONID3_TYPEID_BOMITEM_OPTIONID_MODELID_OPTIONID2_QTY]
    ON [dbo].[PR_MODELTYPE_OPTIONS_BOM]([OPTIONID3] ASC)
    INCLUDE([TYPEID], [BOMITEM], [OPTIONID], [MODELID], [OPTIONID2], [QTY]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_BOM_OPTIONID2_OPTIONID3_ID_TYPEID_BOMITEM_OPTIONID_MODELID_QTY]
    ON [dbo].[PR_MODELTYPE_OPTIONS_BOM]([OPTIONID2] ASC, [OPTIONID3] ASC)
    INCLUDE([ID], [TYPEID], [BOMITEM], [OPTIONID], [MODELID], [QTY]);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_BOM_GID]
    ON [dbo].[PR_MODELTYPE_OPTIONS_BOM]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_OPTIONS_BOM]
    ON [dbo].[PR_MODELTYPE_OPTIONS_BOM]([TYPEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_IX_PR_MODELTYPE_OPTIONS_BOM_2]
    ON [dbo].[PR_MODELTYPE_OPTIONS_BOM]([TYPEID] ASC, [BOMITEM] ASC)
    INCLUDE([OPTIONID], [OPTIONID2], [OPTIONID3]);

