CREATE TABLE [dbo].[PR_MAP_REV_STAT] (
    [ID]          INT             IDENTITY (1, 1) NOT NULL,
    [REVID]       INT             NOT NULL,
    [MAPOPERID]   INT             NOT NULL,
    [FORWARDTIME] DECIMAL (20, 2) NOT NULL,
    [BACKTIME]    DECIMAL (20, 2) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MAP_REV_STAT]
    ON [dbo].[PR_MAP_REV_STAT]([MAPOPERID] ASC, [REVID] ASC) WITH (FILLFACTOR = 90);

