CREATE TABLE [dbo].[PR_MODELTYPE_PDMU] (
    [ID]              INT              IDENTITY (1, 1) NOT NULL,
    [GID]             UNIQUEIDENTIFIER NULL,
    [S_CR]            INT              NOT NULL,
    [S_CDT]           DATETIME         NOT NULL,
    [S_MR]            INT              NULL,
    [S_MDT]           DATETIME         NULL,
    [ARC]             INT              NULL,
    [MTID]            INT              NOT NULL,
    [OPERID]          INT              NOT NULL,
    [QUANTITY]        DECIMAL (18, 6)  NOT NULL,
    [MID]             INT              NOT NULL,
    [NOADDQUANTITY]   INT              NULL,
    [USEINREPEATED]   INT              NULL,
    [ONLYOPTION]      INT              NULL,
    [USEOPTQTY]       INT              NULL,
    [QTYPEROPERATION] INT              NULL,
    [WITHOUTOPTION]   INT              NULL,
    [ASDEFECTIVE]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODELTYPE_PDMU_MID] FOREIGN KEY ([MID]) REFERENCES [dbo].[PR_NAV_PN_CACHE] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_PDMU_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE_COMMON] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_MODELTYPE_PDMU_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_PDMU_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_MODELTYPE_PDMU_WITHOUTOPTION] FOREIGN KEY ([WITHOUTOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PDMU]
    ON [dbo].[PR_MODELTYPE_PDMU]([MTID] ASC);

