CREATE TABLE [dbo].[PR_MAP_OPER_OPT_GROUPS] (
    [ID]             INT      IDENTITY (1, 1) NOT NULL,
    [S_CR]           INT      NOT NULL,
    [S_CDT]          DATETIME NOT NULL,
    [S_MR]           INT      NULL,
    [S_MDT]          DATETIME NULL,
    [ARC]            INT      NULL,
    [MAPOPERID]      INT      NOT NULL,
    [OPT_MDL_GRP_ID] INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MAP_OPER_OPT_GROUPS_MAPOPERID] FOREIGN KEY ([MAPOPERID]) REFERENCES [dbo].[PR_MAP_OPER] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_MAP_OPER_OPT_GROUPS_OPT_MDL_GRP_ID] FOREIGN KEY ([OPT_MDL_GRP_ID]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MAP_OPER_OPT_GROUPS]
    ON [dbo].[PR_MAP_OPER_OPT_GROUPS]([MAPOPERID] ASC);

