CREATE TABLE [dbo].[PR_MODEL_FILES] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NULL,
    [S_CDT]       DATETIME         NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [MODELID]     INT              NOT NULL,
    [FILENAME]    NVARCHAR (255)   NOT NULL,
    [FILESIZE]    INT              NOT NULL,
    [FILEDATE]    DATETIME         NOT NULL,
    [FILEBLOB]    IMAGE            NULL,
    [FILEDESC]    NTEXT            NULL,
    [FILEGROUP]   INT              NULL,
    [SWID]        INT              NULL,
    [FILESHOWIN]  INT              NULL,
    [FILESHOWIN2] INT              NULL,
    [CRMGUID]     UNIQUEIDENTIFIER NULL,
    [TS]          ROWVERSION       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_FILES_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_MODEL_FILES_SWID] FOREIGN KEY ([SWID]) REFERENCES [dbo].[SW_TOOLS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_FILES_SWID]
    ON [dbo].[PR_MODEL_FILES]([SWID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODEL_FILES_GID]
    ON [dbo].[PR_MODEL_FILES]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_FILES]
    ON [dbo].[PR_MODEL_FILES]([MODELID] ASC);

