CREATE TABLE [dbo].[PR_NOT_INST_MODELTYPE_T] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [MODELTYPEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_NOT_INST_MODELTYPE_T_MODELTYPEID] FOREIGN KEY ([MODELTYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_PR_NOT_INST_MODELTYPE_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_NOT_INST_MODELTYPE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NOT_INST_MODELTYPE_T]
    ON [dbo].[PR_NOT_INST_MODELTYPE_T]([VNESHID] ASC);

