CREATE TABLE [dbo].[PR_NAV_ALLOWED_CUSTOMERS_LASTUPDATE] (
    [USERID]     INT      NOT NULL,
    [LASTUPDATE] DATETIME NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_NAV_ALLOWED_CUSTOMERS_LASTUPDATE]
    ON [dbo].[PR_NAV_ALLOWED_CUSTOMERS_LASTUPDATE]([USERID] ASC);

