CREATE TABLE [dbo].[PR_NAV_PROMISED_DATES] (
    [USERID]  INT             NOT NULL,
    [ORDERNN] NVARCHAR (20)   NULL,
    [PN]      NVARCHAR (20)   NULL,
    [PDD]     DATETIME        NULL,
    [QTY]     DECIMAL (16, 5) NULL,
    [DEPCODE] NVARCHAR (50)   NULL,
    [QTYOSTD] DECIMAL (16, 5) NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_PROMISED_DATES_USERID_ORDERNN_PN_PDD_QTY_DEPCODE_QTYOSTD]
    ON [dbo].[PR_NAV_PROMISED_DATES]([USERID] ASC)
    INCLUDE([ORDERNN], [PN], [PDD], [QTY], [DEPCODE], [QTYOSTD]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_PROMISED_DATES_USERID]
    ON [dbo].[PR_NAV_PROMISED_DATES]([USERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_PROMISED_DATES_2]
    ON [dbo].[PR_NAV_PROMISED_DATES]([USERID] ASC, [ORDERNN] ASC, [PN] ASC)
    INCLUDE([PDD], [QTY]);

