CREATE TABLE [dbo].[PR_NAV_IDS] (
    [ID]         INT            IDENTITY (1, 1) NOT NULL,
    [OBJID]      INT            NOT NULL,
    [OBJNAME]    NVARCHAR (250) NOT NULL,
    [SEARCHNAME] NVARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_IDS3]
    ON [dbo].[PR_NAV_IDS]([SEARCHNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_IDS2]
    ON [dbo].[PR_NAV_IDS]([OBJNAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_IDS1]
    ON [dbo].[PR_NAV_IDS]([OBJID] ASC);

