CREATE TABLE [dbo].[PR_NAV_ALLOWED_CUSTOMERS] (
    [USERID] INT           NOT NULL,
    [CCODE]  NVARCHAR (50) NOT NULL,
    [CUSTID] INT           NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_ALLOWED_CUSTOMERS_CCODE]
    ON [dbo].[PR_NAV_ALLOWED_CUSTOMERS]([CCODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_ALLOWED_CUSTOMERS_2]
    ON [dbo].[PR_NAV_ALLOWED_CUSTOMERS]([CUSTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_NAV_ALLOWED_CUSTOMERS]
    ON [dbo].[PR_NAV_ALLOWED_CUSTOMERS]([USERID] ASC);

