CREATE TABLE [dbo].[PR_OPER_RULES] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [OPERID]     INT              NOT NULL,
    [ARG1]       INT              NULL,
    [RULEACTION] INT              NOT NULL,
    [ARG2]       INT              NULL,
    [ERRTEXT]    NVARCHAR (100)   NOT NULL,
    [ARG3]       INT              NULL,
    [ARG4]       INT              NULL,
    [ARG5]       INT              NULL,
    [FTEXT]      NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPER_RULES_ARG1] FOREIGN KEY ([ARG1]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_OPER_RULES_ARG2] FOREIGN KEY ([ARG2]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_OPER_RULES_ARG3] FOREIGN KEY ([ARG3]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_OPER_RULES_ARG4] FOREIGN KEY ([ARG4]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_OPER_RULES_ARG5] FOREIGN KEY ([ARG5]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_OPER_RULES_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPER_RULES]
    ON [dbo].[PR_OPER_RULES]([OPERID] ASC);

