CREATE TABLE [dbo].[PR_OPERATION_UNINSTALL] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [OPERID]       INT              NOT NULL,
    [INSTALLROWID] INT              NOT NULL,
    [UNITEMSTAT]   INT              NOT NULL,
    [UNITEMREMARK] NVARCHAR (250)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATION_UNINSTALL_INSTALLROWID] FOREIGN KEY ([INSTALLROWID]) REFERENCES [dbo].[PR_OPERATION_INSTALL] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_UNINSTALL_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_OPERATION_UNINSTALL_1]
    ON [dbo].[PR_OPERATION_UNINSTALL]([INSTALLROWID] ASC, [OPERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_UNINSTALL]
    ON [dbo].[PR_OPERATION_UNINSTALL]([OPERID] ASC);

