CREATE TABLE [dbo].[PR_OPER_ADD_MH] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [OPERID]   INT              NOT NULL,
    [MANHOUR2] DECIMAL (10, 4)  NOT NULL,
    [OPTID]    INT              NOT NULL,
    [REMARK]   NVARCHAR (200)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPER_ADD_MH_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_OPER_ADD_MH_OPTID] FOREIGN KEY ([OPTID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPER_ADD_MH]
    ON [dbo].[PR_OPER_ADD_MH]([OPERID] ASC);

