CREATE TABLE [dbo].[PR_OPERATION_PARAMS] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NULL,
    [S_CDT]      DATETIME         NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [OPERID]     INT              NOT NULL,
    [PARAMID]    INT              NOT NULL,
    [PVALUE]     SQL_VARIANT      NOT NULL,
    [PCOMMENT]   NTEXT            NULL,
    [CREATEFLAG] INT              NULL,
    [INDEX_STR]  NVARCHAR (250)   NULL,
    [EQID]       INT              NULL,
    [SWVERID]    INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_OPERATION_PARAMS_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_PARAMS_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_OPERATION_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_PARAMS_SWVERID]
    ON [dbo].[PR_OPERATION_PARAMS]([SWVERID] ASC) WHERE ([SWVERID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_PARAMS_INDEX_STR]
    ON [dbo].[PR_OPERATION_PARAMS]([PARAMID] ASC, [INDEX_STR] ASC) WHERE ([INDEX_STR] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_PARAMS_EQID]
    ON [dbo].[PR_OPERATION_PARAMS]([EQID] ASC) WHERE ([EQID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_PARAMS_3]
    ON [dbo].[PR_OPERATION_PARAMS]([PARAMID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_OPERATION_PARAMS_1]
    ON [dbo].[PR_OPERATION_PARAMS]([OPERID] ASC, [PARAMID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_PARAMS]
    ON [dbo].[PR_OPERATION_PARAMS]([OPERID] ASC) WITH (FILLFACTOR = 90);

