CREATE TABLE [dbo].[PR_OPERATION_TERMS_SUBSCRIPTION_T] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [VNESHID]    INT              NOT NULL,
    [EMPLOYEEID] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATION_TERMS_SUBSCRIPTION_T_EMPLOYEEID] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_TERMS_SUBSCRIPTION_T]
    ON [dbo].[PR_OPERATION_TERMS_SUBSCRIPTION_T]([VNESHID] ASC);

