CREATE TABLE [dbo].[PR_OPERATIONS_GRQ] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [VNESHID]       INT              NOT NULL,
    [OPERCODE]      NVARCHAR (20)    NOT NULL,
    [QUALIFICATION] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATIONS_GRQ_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_OPERATIONS_GR] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_OPERATIONS_GRQ_2]
    ON [dbo].[PR_OPERATIONS_GRQ]([VNESHID] ASC, [QUALIFICATION] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATIONS_GRQ]
    ON [dbo].[PR_OPERATIONS_GRQ]([VNESHID] ASC) WITH (FILLFACTOR = 90);

