CREATE TABLE [dbo].[PR_OPERATION_EQUIPMENT] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [GID]            UNIQUEIDENTIFIER NULL,
    [S_CR]           INT              NOT NULL,
    [S_CDT]          DATETIME         NOT NULL,
    [S_MR]           INT              NULL,
    [S_MDT]          DATETIME         NULL,
    [ARC]            INT              NULL,
    [OPERID]         INT              NOT NULL,
    [EQID]           INT              NOT NULL,
    [WASAUTOCREATED] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATION_EQUIPMENT_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_EQUIPMENT_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_EQUIPMENT_EQID]
    ON [dbo].[PR_OPERATION_EQUIPMENT]([EQID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_EQUIPMENT]
    ON [dbo].[PR_OPERATION_EQUIPMENT]([OPERID] ASC);

