CREATE TABLE [dbo].[PR_OPERATION_FILES] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NULL,
    [S_CDT]       DATETIME         NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [OPERATIONID] INT              NOT NULL,
    [FILENAME]    NVARCHAR (255)   NOT NULL,
    [FILESIZE]    INT              NOT NULL,
    [FILEDATE]    DATETIME         NULL,
    [FILEBLOB]    IMAGE            NULL,
    [FILEDESC]    NTEXT            NULL,
    [FILEPREVIEW] IMAGE            NULL,
    [PARAMID]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATION_FILES_OPERATIONID] FOREIGN KEY ([OPERATIONID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_FILES_2]
    ON [dbo].[PR_OPERATION_FILES]([OPERATIONID] ASC, [FILENAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_FILES]
    ON [dbo].[PR_OPERATION_FILES]([OPERATIONID] ASC);

