CREATE TABLE [dbo].[PR_OPERATION] (
    [ID]                   INT              IDENTITY (1, 1) NOT NULL,
    [GID]                  UNIQUEIDENTIFIER NULL,
    [S_S]                  INT              NULL,
    [S_CR]                 INT              NULL,
    [S_CDT]                DATETIME         NOT NULL,
    [S_MR]                 INT              NULL,
    [S_MDT]                DATETIME         NULL,
    [ORDERID]              INT              NULL,
    [DEVICEID]             INT              NULL,
    [OPERTYPEID]           INT              NOT NULL,
    [REMARKS]              NTEXT            NULL,
    [REPAIRREASON]         NVARCHAR (800)   NULL,
    [COMPLETED_DT]         DATETIME         NULL,
    [ARC]                  INT              NULL,
    [USERINPROGRESS]       INT              NULL,
    [CONTROLPOINTS]        NTEXT            NULL,
    [NOTALLCONTROLPOINTS]  INT              NULL,
    [TODOTEXT]             NTEXT            NULL,
    [PARENTID]             INT              NULL,
    [SPECIALTYPE]          INT              NULL,
    [TODOID]               INT              NULL,
    [RETURNTR]             INT              NULL,
    [REVOPERID]            INT              NULL,
    [DONEOPT]              INT              NULL,
    [TIMEPOSTED]           INT              NULL,
    [RETURNAFTERTROUBLEID] INT              NULL,
    [FORMULAS]             NTEXT            NULL,
    [LASTUSERINPROGRESS]   INT              NULL,
    [OPLEVEL]              INT              NULL,
    [DEVICEPOSTED]         INT              NULL,
    [RERUNALL]             INT              NULL,
    [DECNOWORKTIME]        INT              NULL,
    [OLD_REVOPERID]        INT              NULL,
    [PREP_RESULT]          INT              NULL,
    [TC_ACTION]            INT              NULL,
    [TC_MINUTE]            INT              NULL,
    [OPERGR]               INT              NULL,
    [Q_IN]                 INT              NULL,
    [Q_OUT]                INT              NULL,
    [Q_PARENT]             INT              NULL,
    [REPORTEDERRORUSER]    INT              NULL,
    [NEWMODELID]           INT              NULL,
    [OLDMODELID]           INT              NULL,
    [FAILUREREPORTID]      INT              NULL,
    [LASTCONDITIONS]       NTEXT            NULL,
    [IMPID]                INT              NULL,
    [FREETR]               INT              NULL,
    [TROUBLEEXIT]          INT              NULL,
    [MANHOUR]              DECIMAL (10, 1)  NULL,
    [OPERFORMHISTID]       INT              NULL,
    [EXTDEPID]             INT              NULL,
    [TRTYPE]               INT              NULL,
    [TRMAPID]              INT              NULL,
    [TRMAP_N]              INT              NULL,
    [LASTERRORS]           NTEXT            NULL,
    [AC_XML]               NTEXT            NULL,
    [MNT_PLANID]           INT              NULL,
    [HIGHPRDATE]           DATETIME         NULL,
    [URGENCY]              INT              NULL,
    [SUM_OPERATION_STAT_1] DECIMAL (12, 2)  NULL,
    [SUM_OPERATION_STAT_4] DECIMAL (12, 2)  NULL,
    [ISTMELDUNG]           INT              NULL,
    [DECLAREDREADY]        INT              NULL,
    [CREATEDBYOPERID]      INT              NULL,
    [HIDDEN]               INT              NULL,
    [HIDDENOTHER]          INT              NULL,
    [MAT_USAGE_X_QTY]      INT              NULL,
    [EQID]                 INT              NULL,
    [TEMP_SIGN]            INT              NULL,
    [MNT_PLAN_EQROW_ID]    INT              NULL,
    [FAILEDXML]            NTEXT            NULL,
    [ITEMFAILED]           INT              NULL,
    [USERINTRAINING]       INT              NULL,
    [WORKORDERID]          INT              NULL,
    [EQ_WORKCYCLES_FLAG]   INT              NULL,
    [TODOTEXT_SHOWMSG]     INT              NULL,
    [FORCEUSERINPROGRESS]  INT              NULL,
    CONSTRAINT [PK__PR_OPERA__3214EC270697FACD] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_OPERATION_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_EQID] FOREIGN KEY ([EQID]) REFERENCES [dbo].[EQ_EQUIPMENT] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_OPERATIONS] FOREIGN KEY ([OPERTYPEID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_OPERFORMHISTID] FOREIGN KEY ([OPERFORMHISTID]) REFERENCES [dbo].[PR_OPERATIONS_HISTORY] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_ORDERID] FOREIGN KEY ([ORDERID]) REFERENCES [dbo].[PR_PRORDER] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_REVOPERID] FOREIGN KEY ([REVOPERID]) REFERENCES [dbo].[PR_MAP_OPER] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_TRMAPID] FOREIGN KEY ([TRMAPID]) REFERENCES [dbo].[PR_MAP] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_USERINPROGRESS] FOREIGN KEY ([USERINPROGRESS]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_USERINTRAINING] FOREIGN KEY ([USERINTRAINING]) REFERENCES [dbo].[DEF_USERS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_S_CDT]
    ON [dbo].[PR_OPERATION]([S_CDT] ASC)
    INCLUDE([OPERTYPEID], [REPAIRREASON], [COMPLETED_DT], [ARC], [USERINPROGRESS], [NOTALLCONTROLPOINTS], [PARENTID], [SPECIALTYPE], [TODOID], [RETURNTR], [REVOPERID], [DONEOPT], [TIMEPOSTED], [RETURNAFTERTROUBLEID], [LASTUSERINPROGRESS], [OPLEVEL], [DEVICEPOSTED], [RERUNALL], [DECNOWORKTIME], [OLD_REVOPERID], [PREP_RESULT], [TC_ACTION], [TC_MINUTE], [OPERGR], [Q_IN], [Q_OUT], [Q_PARENT], [REPORTEDERRORUSER], [NEWMODELID], [OLDMODELID], [FAILUREREPORTID], [IMPID], [FREETR], [TROUBLEEXIT], [MANHOUR], [OPERFORMHISTID], [EXTDEPID], [TRTYPE], [TRMAPID], [TRMAP_N]) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_REVOPERID]
    ON [dbo].[PR_OPERATION]([REVOPERID] ASC) WHERE ([REVOPERID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_ORDERID_OPERTYPEID_DEVICEID_REVOPERID_COMPLETED_DT]
    ON [dbo].[PR_OPERATION]([ORDERID] ASC, [OPERTYPEID] ASC)
    INCLUDE([DEVICEID], [REVOPERID], [COMPLETED_DT]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_OPERTYPEID_ID_ORDERID_DEVICEID_COMPLETED_DT]
    ON [dbo].[PR_OPERATION]([OPERTYPEID] ASC)
    INCLUDE([ID], [ORDERID], [DEVICEID], [COMPLETED_DT]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_OPERTYPE]
    ON [dbo].[PR_OPERATION]([OPERTYPEID] ASC)
    INCLUDE([DEVICEID], [COMPLETED_DT], [PREP_RESULT]) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_MNT_PLANID]
    ON [dbo].[PR_OPERATION]([MNT_PLANID] ASC)
    INCLUDE([URGENCY], [S_S], [COMPLETED_DT]) WHERE ([MNT_PLANID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_MNT_PLAN_EQROW_ID]
    ON [dbo].[PR_OPERATION]([MNT_PLAN_EQROW_ID] ASC)
    INCLUDE([MNT_PLANID], [ID], [COMPLETED_DT]) WHERE ([MNT_PLAN_EQROW_ID] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_FAILUREREPORTID]
    ON [dbo].[PR_OPERATION]([FAILUREREPORTID] ASC)
    INCLUDE([OPERTYPEID]) WHERE ([FAILUREREPORTID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_EQID]
    ON [dbo].[PR_OPERATION]([EQID] ASC) WHERE ([EQID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_DEVICEID_ID]
    ON [dbo].[PR_OPERATION]([DEVICEID] ASC)
    INCLUDE([ID]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_DEVICE_ORDER]
    ON [dbo].[PR_OPERATION]([DEVICEID] ASC, [ORDERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_COMPLETED_DT_ID_ORDERID_DEVICEID_OPERTYPEID]
    ON [dbo].[PR_OPERATION]([COMPLETED_DT] ASC)
    INCLUDE([ID], [ORDERID], [DEVICEID], [OPERTYPEID]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_COMPLETED_DT]
    ON [dbo].[PR_OPERATION]([COMPLETED_DT] ASC)
    INCLUDE([ID], [ORDERID], [OPERTYPEID], [USERINPROGRESS]) WHERE ([COMPLETED_DT] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_CMP2]
    ON [dbo].[PR_OPERATION]([S_S] ASC, [COMPLETED_DT] ASC, [USERINPROGRESS] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_4]
    ON [dbo].[PR_OPERATION]([S_S] ASC)
    INCLUDE([OPERTYPEID]) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_33]
    ON [dbo].[PR_OPERATION]([USERINPROGRESS] ASC, [OPERGR] ASC)
    INCLUDE([ORDERID], [DEVICEID]) WHERE ([COMPLETED_DT] IS NULL AND [USERINPROGRESS] IS NOT NULL) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_2]
    ON [dbo].[PR_OPERATION]([ORDERID] ASC, [S_S] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_1]
    ON [dbo].[PR_OPERATION]([DEVICEID] ASC, [S_S] ASC) WITH (FILLFACTOR = 90);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Ссылка на изделие в рамках которого выполняется операция.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'PR_OPERATION', @level2type = N'COLUMN', @level2name = N'DEVICEID';

