CREATE TABLE [dbo].[PR_OPERATION_TERMS_SUBSCRIPTION] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_S]         INT              NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [MODELTYPEID] INT              NOT NULL,
    [MODELID]     INT              NULL,
    [OPERATIONID] INT              NOT NULL,
    [DAYS]        INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATION_TERMS_SUBSCRIPTION_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_TERMS_SUBSCRIPTION_MODELTYPEID] FOREIGN KEY ([MODELTYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_TERMS_SUBSCRIPTION_OPERATIONID] FOREIGN KEY ([OPERATIONID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID])
);

