CREATE TABLE [dbo].[PR_OPERATION_TERMS_NOTIFICATIONS] (
    [PRORDERID] INT      NOT NULL,
    [DD]        DATETIME NULL,
    CONSTRAINT [PK_PR_PRORDER_NOTIFICATIONS] PRIMARY KEY CLUSTERED ([PRORDERID] ASC)
);

