CREATE TABLE [dbo].[PR_OPERATIONS_HISTORY] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [FORMXML]    NTEXT            NULL,
    [SMFORMXML]  NTEXT            NULL,
    [CAPTION]    NVARCHAR (200)   NULL,
    [FORMID]     INT              NOT NULL,
    [FHASH]      NVARCHAR (50)    NULL,
    [OPERTYPE]   INT              NULL,
    [ISTMELDUNG] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATIONS_HISTORY_FORMID] FOREIGN KEY ([FORMID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_OPERATIONS_HISTORY_GID]
    ON [dbo].[PR_OPERATIONS_HISTORY]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATIONS_HISTORY]
    ON [dbo].[PR_OPERATIONS_HISTORY]([FORMID] ASC, [FHASH] ASC) WITH (FILLFACTOR = 90);

