CREATE TABLE [dbo].[PR_OPERATION_EXT_PARAMS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [OPERID]    INT              NOT NULL,
    [PARAMID]   INT              NOT NULL,
    [PVALUE]    SQL_VARIANT      NOT NULL,
    [PCOMMENT]  NTEXT            NULL,
    [DEVICEID]  INT              NULL,
    [BOMID]     INT              NULL,
    [BOMID2]    INT              NULL,
    [BOMID3]    INT              NULL,
    [INDEX_STR] NVARCHAR (250)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATION_EXT_PARAMS_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_OPERATION_EXT_PARAMS_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_OPERATION_EXT_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_EXT_PARAMS_INDEX_STR]
    ON [dbo].[PR_OPERATION_EXT_PARAMS]([PARAMID] ASC, [INDEX_STR] ASC) WHERE ([INDEX_STR] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_OPERATION_EXT_PARAMS_1]
    ON [dbo].[PR_OPERATION_EXT_PARAMS]([DEVICEID] ASC, [PARAMID] ASC, [OPERID] ASC) WHERE ([DEVICEID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_EXT_PARAMS]
    ON [dbo].[PR_OPERATION_EXT_PARAMS]([OPERID] ASC);

