CREATE TABLE [dbo].[PR_OPERATION_REQ_REPORTS] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [OPERTYPEID] INT              NOT NULL,
    [REPORTID]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_OPERATION_REQ_REPORTS_OPERTYPEID] FOREIGN KEY ([OPERTYPEID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_OPERATION_REQ_REPORTS_REPORTID] FOREIGN KEY ([REPORTID]) REFERENCES [dbo].[PR_REPORTS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_REQ_REPORTS]
    ON [dbo].[PR_OPERATION_REQ_REPORTS]([OPERTYPEID] ASC);

