CREATE TABLE [dbo].[PR_PRORDER_PLAN] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [ORDERID] INT              NOT NULL,
    [STAGEID] INT              NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_PRORDER_PLAN_ORDERID] FOREIGN KEY ([ORDERID]) REFERENCES [dbo].[PR_PRORDER] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_PRORDER_PLAN_STAGEID] FOREIGN KEY ([STAGEID]) REFERENCES [dbo].[PR_PRORD_STAGES] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PRORDER_PLAN]
    ON [dbo].[PR_PRORDER_PLAN]([ORDERID] ASC);

