CREATE TABLE [dbo].[PR_PREPARATORY] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_S]        INT              NOT NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [TYPEID]     INT              NOT NULL,
    [OPERID]     INT              NOT NULL,
    [MULTIPLIER] INT              NOT NULL,
    [DEPID]      INT              NOT NULL,
    [REMARK]     NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_PREPARATORY_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_PREPARATORY_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_PREPARATORY_TYPEID] FOREIGN KEY ([TYPEID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PREPARATORY_3]
    ON [dbo].[PR_PREPARATORY]([S_S] ASC, [OPERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PREPARATORY_2]
    ON [dbo].[PR_PREPARATORY]([S_S] ASC)
    INCLUDE([OPERID]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PREPARATORY]
    ON [dbo].[PR_PREPARATORY]([TYPEID] ASC);

