CREATE TABLE [dbo].[PR_PRORDER_SERVICE] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [GID]            UNIQUEIDENTIFIER NULL,
    [S_CR]           INT              NOT NULL,
    [S_CDT]          DATETIME         NOT NULL,
    [S_MR]           INT              NULL,
    [S_MDT]          DATETIME         NULL,
    [ARC]            INT              NULL,
    [ORDERID]        INT              NOT NULL,
    [DEVICEID]       INT              NOT NULL,
    [PROBLEM]        NTEXT            NULL,
    [OLDDEVICESTATE] INT              NULL,
    [FRID]           INT              NULL,
    [INC_DATE]       DATETIME         NULL,
    [QTY]            INT              NULL,
    [SCOMPLETED_DT]  DATETIME         NULL,
    [ROOTSN]         NVARCHAR (20)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_PRORDER_SERVICE_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_PRORDER_SERVICE_FRID] FOREIGN KEY ([FRID]) REFERENCES [dbo].[FC_REPORT] ([ID]),
    CONSTRAINT [FK_PR_PRORDER_SERVICE_ORDERID] FOREIGN KEY ([ORDERID]) REFERENCES [dbo].[PR_PRORDER] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_PRORDER_SERVICE_ORD_DEV]
    ON [dbo].[PR_PRORDER_SERVICE]([ORDERID] ASC, [DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PRORDER_SERVICE_FRID]
    ON [dbo].[PR_PRORDER_SERVICE]([FRID] ASC) WHERE ([FRID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PRORDER_SERVICE_DEVICEID]
    ON [dbo].[PR_PRORDER_SERVICE]([DEVICEID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PRORDER_SERVICE]
    ON [dbo].[PR_PRORDER_SERVICE]([ORDERID] ASC);

