CREATE TABLE [dbo].[PR_PARENT_OPERATION] (
    [DEVICEID]          INT NOT NULL,
    [OPERID]            INT NOT NULL,
    [DONTUSEPARAMETERS] INT NULL,
    CONSTRAINT [FK_PR_PARENT_OPERATION_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_PARENT_OPERATION_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PARENT_OPERATION_OPERID]
    ON [dbo].[PR_PARENT_OPERATION]([OPERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_PARENT_OPERATION]
    ON [dbo].[PR_PARENT_OPERATION]([DEVICEID] ASC, [OPERID] ASC);

