CREATE TABLE [dbo].[PR_REPORT_PARAM_TEMPLATES_T] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [TEMPLATEID]  INT              NOT NULL,
    [PARAM_NAME]  NVARCHAR (250)   NOT NULL,
    [PARAM_VALUE] NVARCHAR (4000)  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REPORT_PARAM_TEMPLATES_T_TEMPLATEID] FOREIGN KEY ([TEMPLATEID]) REFERENCES [dbo].[PR_REPORT_PARAM_TEMPLATES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REPORT_PARAM_TEMPLATES_T]
    ON [dbo].[PR_REPORT_PARAM_TEMPLATES_T]([TEMPLATEID] ASC);

