CREATE TABLE [dbo].[PR_REPORTS_REVISIONS] (
    [REVID]    INT      NOT NULL,
    [REPORTID] INT      NOT NULL,
    [S_MDT]    DATETIME NULL
);


GO
CREATE CLUSTERED INDEX [IX_PR_REPORTS_REVISIONS]
    ON [dbo].[PR_REPORTS_REVISIONS]([REVID] ASC);

