CREATE TABLE [dbo].[PR_REV_BOM2] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [REVID]         INT              NOT NULL,
    [BOMID]         INT              NOT NULL,
    [PARTMODELID]   INT              NOT NULL,
    [PARTONLYREVID] INT              NULL,
    [ONLYOPTION]    INT              NULL,
    [ONLYOPTION2]   INT              NULL,
    [ONLYOPTION3]   INT              NULL,
    [QTY]           DECIMAL (10, 4)  NULL,
    [TYPICAL2NAV]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_BOM2_BOMID] FOREIGN KEY ([BOMID]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_PR_REV_BOM2_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_BOM2_ONLYOPTION2] FOREIGN KEY ([ONLYOPTION2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_BOM2_ONLYOPTION3] FOREIGN KEY ([ONLYOPTION3]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_BOM2_PARTMODELID] FOREIGN KEY ([PARTMODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_REV_BOM2_PARTONLYREVID] FOREIGN KEY ([PARTONLYREVID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_PR_REV_BOM2_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_BOM2_GID]
    ON [dbo].[PR_REV_BOM2]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_BOM2_3]
    ON [dbo].[PR_REV_BOM2]([PARTMODELID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_BOM2_2]
    ON [dbo].[PR_REV_BOM2]([REVID] ASC, [BOMID] ASC)
    INCLUDE([ONLYOPTION], [ONLYOPTION2], [ONLYOPTION3]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_BOM2]
    ON [dbo].[PR_REV_BOM2]([REVID] ASC);

