CREATE TABLE [dbo].[PR_REPORTS_2DEVICE] (
    [REVID]  INT            NULL,
    [CRC]    INT            NULL,
    [CMPL]   NVARCHAR (MAX) NULL,
    [NOCMPL] NVARCHAR (MAX) NULL,
    [S_MDT]  DATETIME       NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_PR_REPORTS_2DEVICE_REVID]
    ON [dbo].[PR_REPORTS_2DEVICE]([REVID] ASC);

