CREATE TABLE [dbo].[PR_REV_OVER_MULTIPLI] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [REVID]     INT              NOT NULL,
    [MAPOPERID] INT              NOT NULL,
    [MULTIPLI]  DECIMAL (12, 2)  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_OVER_MULTIPLI_MAPOPERID] FOREIGN KEY ([MAPOPERID]) REFERENCES [dbo].[PR_MAP_OPER] ([ID]),
    CONSTRAINT [FK_PR_REV_OVER_MULTIPLI_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_OVER_MULTIPLI_2]
    ON [dbo].[PR_REV_OVER_MULTIPLI]([MAPOPERID] ASC, [REVID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_OVER_MULTIPLI]
    ON [dbo].[PR_REV_OVER_MULTIPLI]([REVID] ASC) WITH (FILLFACTOR = 90);

