CREATE TABLE [dbo].[PR_REV_PARAMS] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NULL,
    [S_CDT]       DATETIME         NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [REVISIONID]  INT              NOT NULL,
    [PARAMID]     INT              NOT NULL,
    [PVALUE]      SQL_VARIANT      NOT NULL,
    [ONLYOPTION]  INT              NULL,
    [ARC]         INT              NULL,
    [ONLYOPTION2] INT              NULL,
    [ONLYOPTION3] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_REV_PARAMS_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_PARAMS_ONLYOPTION2] FOREIGN KEY ([ONLYOPTION2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_PARAMS_ONLYOPTION3] FOREIGN KEY ([ONLYOPTION3]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_REV_PARAMS_REVISIONID] FOREIGN KEY ([REVISIONID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_PARAMS_PRMS_OPTS]
    ON [dbo].[PR_REV_PARAMS]([REVISIONID] ASC, [PARAMID] ASC, [ONLYOPTION] ASC, [ONLYOPTION2] ASC, [ONLYOPTION3] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_PARAMS_PARAMID]
    ON [dbo].[PR_REV_PARAMS]([PARAMID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_PARAMS_GID]
    ON [dbo].[PR_REV_PARAMS]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_PARAMS_2]
    ON [dbo].[PR_REV_PARAMS]([REVISIONID] ASC, [PARAMID] ASC)
    INCLUDE([ONLYOPTION], [ONLYOPTION2], [ONLYOPTION3]) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_PARAMS]
    ON [dbo].[PR_REV_PARAMS]([REVISIONID] ASC) WITH (FILLFACTOR = 90);

