CREATE TABLE [dbo].[PR_REV_OVERRIDE_ALTERNATIVE] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NOT NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [REVID]         INT              NOT NULL,
    [MAPOPERID]     INT              NOT NULL,
    [TYPICAL2NAV]   INT              NULL,
    [ADDEDBYKB3724] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_OVERRIDE_ALTERNATIVE_MAPOPERID] FOREIGN KEY ([MAPOPERID]) REFERENCES [dbo].[PR_MAP_OPER] ([ID]),
    CONSTRAINT [FK_PR_REV_OVERRIDE_ALTERNATIVE_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_OVERRIDE_ALTERNATIVE2]
    ON [dbo].[PR_REV_OVERRIDE_ALTERNATIVE]([REVID] ASC, [MAPOPERID] ASC);

