CREATE TABLE [dbo].[PR_REV_COMPM] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [REVID]       INT              NOT NULL,
    [MODELID]     INT              NOT NULL,
    [COMPMODELID] INT              NOT NULL,
    [TYPICAL2NAV] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_REV_COMPM_COMPMODELID] FOREIGN KEY ([COMPMODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_REV_COMPM_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_PR_REV_COMPM_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_COMPM]
    ON [dbo].[PR_REV_COMPM]([REVID] ASC) WITH (FILLFACTOR = 90);

