CREATE TABLE [dbo].[PR_REV_OVER_WAITNORM] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [REVID]     INT              NOT NULL,
    [MAPOPERID] INT              NOT NULL,
    [WAITNORM]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [PR_REV_OVER_WAITNORM_MAPOPERID] FOREIGN KEY ([MAPOPERID]) REFERENCES [dbo].[PR_MAP_OPER] ([ID]),
    CONSTRAINT [PR_REV_OVER_WAITNORM_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_OVER_WAITNORM]
    ON [dbo].[PR_REV_OVER_WAITNORM]([REVID] ASC, [MAPOPERID] ASC);

