CREATE TABLE [dbo].[PR_REPORTS_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [VNESHID]  INT              NOT NULL,
    [MODELID]  INT              NOT NULL,
    [REVID]    INT              NULL,
    [CUSTID]   INT              NULL,
    [OPTIONID] INT              NULL,
    [ARC]      INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_PR_REPORTS_T_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_PR_REPORTS_T_OPTIONID] FOREIGN KEY ([OPTIONID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REPORTS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_REPORTS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REPORTS_T_GID]
    ON [dbo].[PR_REPORTS_T]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REPORTS_T_4]
    ON [dbo].[PR_REPORTS_T]([VNESHID] ASC, [MODELID] ASC, [REVID] ASC)
    INCLUDE([CUSTID], [OPTIONID]);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REPORTS_T_3]
    ON [dbo].[PR_REPORTS_T]([VNESHID] ASC, [MODELID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REPORTS_T_2]
    ON [dbo].[PR_REPORTS_T]([VNESHID] ASC, [REVID] ASC) WHERE ([REVID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REPORTS_T]
    ON [dbo].[PR_REPORTS_T]([VNESHID] ASC) WITH (FILLFACTOR = 90);

