CREATE TABLE [dbo].[PR_REV_SUPP_ADD_TIMES_SUGGEST_T] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [VNESHID]       INT              NOT NULL,
    [MAPOPERID]     INT              NULL,
    [ADDVALUE]      DECIMAL (16, 4)  NULL,
    [REMARK]        NVARCHAR (200)   NULL,
    [REVID]         INT              NOT NULL,
    [NAVCODE]       NVARCHAR (20)    NULL,
    [QUALIFICATION] INT              NOT NULL,
    [ISCHECKED]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_SUPP_ADD_TIMES_SUGGEST_T_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_REV_SUPP_ADD_TIMES_SUGGEST_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_REV_SUPP_ADD_TIMES_SUGGEST] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_SUPP_ADD_TIMES_SUGGEST_T_REVID]
    ON [dbo].[PR_REV_SUPP_ADD_TIMES_SUGGEST_T]([REVID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_SUPP_ADD_TIMES_SUGGEST_T]
    ON [dbo].[PR_REV_SUPP_ADD_TIMES_SUGGEST_T]([VNESHID] ASC);

