CREATE TABLE [dbo].[PR_REV_CHANGINGS_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [REVID]   INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_CHANGINGS_T_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_PR_REV_CHANGINGS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_REV_CHANGINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_CHANGINGS_T]
    ON [dbo].[PR_REV_CHANGINGS_T]([VNESHID] ASC);

