CREATE TABLE [dbo].[PR_REV_CHANGINGS_PARAMS] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [VNESHID]    INT              NOT NULL,
    [PARAMID]    INT              NOT NULL,
    [PVALUE]     SQL_VARIANT      NOT NULL,
    [ONLYOPTION] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_CHANGINGS_PARAMS_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_CHANGINGS_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_REV_CHANGINGS_PARAMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_REV_CHANGINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_CHANGINGS_PARAMS]
    ON [dbo].[PR_REV_CHANGINGS_PARAMS]([VNESHID] ASC);

