CREATE TABLE [dbo].[PR_RESOURCE_PLAN_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [EMPID]    INT              NULL,
    [OPERGRID] INT              NULL,
    [ACTION]   INT              NULL,
    [FROMDT]   DATETIME         NULL,
    [TODT]     DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_RESOURCE_PLAN_T_EMPID] FOREIGN KEY ([EMPID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PR_RESOURCE_PLAN_T_OPERGRID] FOREIGN KEY ([OPERGRID]) REFERENCES [dbo].[PR_OPERATIONS_GR] ([ID]),
    CONSTRAINT [FK_PR_RESOURCE_PLAN_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_RESOURCE_PLAN] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_RESOURCE_PLAN_T]
    ON [dbo].[PR_RESOURCE_PLAN_T]([VNESHID] ASC);

