CREATE TABLE [dbo].[PR_REV_OVER_TC_ACTION] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [REVID]     INT              NOT NULL,
    [OPERID]    INT              NOT NULL,
    [TC_MINUTE] DECIMAL (12, 2)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_OVER_TC_ACTION_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_REV_OVER_TC_ACTION_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_OVER_TC_ACTION_2]
    ON [dbo].[PR_REV_OVER_TC_ACTION]([REVID] ASC, [OPERID] ASC);

