CREATE TABLE [dbo].[PR_REPORTS_O] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [OPTIONID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REPORTS_O_OPTIONID] FOREIGN KEY ([OPTIONID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REPORTS_O_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_REPORTS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REPORTS_O]
    ON [dbo].[PR_REPORTS_O]([VNESHID] ASC);

