CREATE TABLE [dbo].[PR_REV_SW] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [REVID]       INT              NOT NULL,
    [SWID]        INT              NOT NULL,
    [SWMODE]      INT              NOT NULL,
    [SWVERSIONID] INT              NULL,
    [ONLYOPTION]  INT              NULL,
    [SWTOOLID]    INT              NOT NULL,
    [ONLYOPTION2] INT              NULL,
    [ONLYOPTION3] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_REV_SW_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_SW_ONLYOPTION2] FOREIGN KEY ([ONLYOPTION2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_SW_ONLYOPTION3] FOREIGN KEY ([ONLYOPTION3]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_PR_REV_SW_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_REV_SW_SWID] FOREIGN KEY ([SWID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_PR_REV_SW_SWTOOLID] FOREIGN KEY ([SWTOOLID]) REFERENCES [dbo].[SW_TOOLS] ([ID]),
    CONSTRAINT [FK_PR_REV_SW_SWVERSIONID] FOREIGN KEY ([SWVERSIONID]) REFERENCES [dbo].[SW_TOOL_VERSIONS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_REV_SW_GID]
    ON [dbo].[PR_REV_SW]([GID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_REV_SW]
    ON [dbo].[PR_REV_SW]([REVID] ASC);

