CREATE TABLE [dbo].[PR_SHARED_OPER_DEVICE] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [DEVICEID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_SHARED_OPER_DEVICE_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_SHARED_OPER_DEVICE_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_SHARED_OPERATION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SHARED_OPER_DEVICE]
    ON [dbo].[PR_SHARED_OPER_DEVICE]([VNESHID] ASC);

