CREATE TABLE [dbo].[PR_SERVICEORDER_SN_CHANGE_T] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [CHANGEID]    INT              NOT NULL,
    [DEVICEID]    INT              NULL,
    [NEWDEVICEID] INT              NULL,
    [REASON]      NVARCHAR (1000)  NULL,
    [RESULT]      NVARCHAR (1000)  NULL,
    [CHANGED]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_SERVICEORDER_SN_CHANGE_T_CHANGEID] FOREIGN KEY ([CHANGEID]) REFERENCES [dbo].[PR_SERVICEORDER_SN_CHANGE] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_SERVICEORDER_SN_CHANGE_T_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_PR_SERVICEORDER_SN_CHANGE_T_NEWDEVICEID] FOREIGN KEY ([NEWDEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SERVICEORDER_SN_CHANGE_T]
    ON [dbo].[PR_SERVICEORDER_SN_CHANGE_T]([CHANGEID] ASC);

