CREATE TABLE [dbo].[PR_SHARED_OPER_GR] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [FROMDEPID] INT              NOT NULL,
    [TODEPID]   INT              NOT NULL,
    [OPERGRID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_SHARED_OPER_GR_FROMDEPID] FOREIGN KEY ([FROMDEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_PR_SHARED_OPER_GR_OPERGRID] FOREIGN KEY ([OPERGRID]) REFERENCES [dbo].[PR_OPERATIONS_GR] ([ID]),
    CONSTRAINT [FK_PR_SHARED_OPER_GR_TODEPID] FOREIGN KEY ([TODEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID])
);

