CREATE TABLE [dbo].[PR_SHARED_OPER_GR_EMP] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_SHARED_OPER_GR_EMP_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PR_SHARED_OPER_GR_EMP_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_SHARED_OPER_GR] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SHARED_OPER_GR_EMP_EMPLID]
    ON [dbo].[PR_SHARED_OPER_GR_EMP]([EMPLID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SHARED_OPER_GR_EMP]
    ON [dbo].[PR_SHARED_OPER_GR_EMP]([VNESHID] ASC);

