CREATE TABLE [dbo].[PR_SHARED_OPER_OPER] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [MAPOPERID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_SHARED_OPER_OPER_MAPOPERID] FOREIGN KEY ([MAPOPERID]) REFERENCES [dbo].[PR_MAP_OPER] ([ID]),
    CONSTRAINT [FK_PR_SHARED_OPER_OPER_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_SHARED_OPERATION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SHARED_OPER_OPER]
    ON [dbo].[PR_SHARED_OPER_OPER]([VNESHID] ASC);

