CREATE TABLE [dbo].[PR_SUPPLY_PREFIX_STATE] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [PREFIXID] INT              NOT NULL,
    [STATE]    INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_SUPPLY_PREFIX_STATE_PREFIXID] FOREIGN KEY ([PREFIXID]) REFERENCES [dbo].[PR_SUPPLY_PREFIX] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PR_SUPPLY_PREFIX_STATE_STATE] FOREIGN KEY ([STATE]) REFERENCES [dbo].[PR_SUPPLY_STATE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SUPPLY_PREFIX_STATE]
    ON [dbo].[PR_SUPPLY_PREFIX_STATE]([PREFIXID] ASC);

