CREATE TABLE [dbo].[PR_SHARED_OPERATION_APP] (
    [SHARE_DOC_ID] INT NOT NULL,
    [DEVICEID]     INT NOT NULL,
    [MAPOPERID]    INT NOT NULL,
    [TODEPID]      INT NOT NULL,
    CONSTRAINT [FK_PR_SHARED_OPERATION_APP_PR_SHARED_OPERATION] FOREIGN KEY ([SHARE_DOC_ID]) REFERENCES [dbo].[PR_SHARED_OPERATION] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SHARED_OPERATION_APP_1]
    ON [dbo].[PR_SHARED_OPERATION_APP]([SHARE_DOC_ID] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_PR_SHARED_OPERATION_APP]
    ON [dbo].[PR_SHARED_OPERATION_APP]([DEVICEID] ASC, [MAPOPERID] ASC) WITH (FILLFACTOR = 90);

