CREATE TABLE [dbo].[PR_TROUBLE_TEMPLATES_T] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [ORDERPOS]    INT              NOT NULL,
    [OPERATIONID] INT              NOT NULL,
    [TODO]        NTEXT            NULL,
    [EMPLOYEEID]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_TROUBLE_TEMPLATES_T_EMPLOYEEID] FOREIGN KEY ([EMPLOYEEID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PR_TROUBLE_TEMPLATES_T_OPERATIONID] FOREIGN KEY ([OPERATIONID]) REFERENCES [dbo].[PR_OPERATIONS] ([ID]),
    CONSTRAINT [FK_PR_TROUBLE_TEMPLATES_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PR_TROUBLE_TEMPLATES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_TROUBLE_TEMPLATES_T]
    ON [dbo].[PR_TROUBLE_TEMPLATES_T]([VNESHID] ASC);

