CREATE TABLE [dbo].[PRR_OVERHOURS_DATA] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NOT NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [VNESHID]       INT              NOT NULL,
    [EMPLID]        INT              NOT NULL,
    [DEPID]         INT              NOT NULL,
    [GROUPINGVALUE] NVARCHAR (200)   NULL,
    [D1]            DECIMAL (20, 6)  NULL,
    [D2]            DECIMAL (20, 6)  NULL,
    [D3]            DECIMAL (20, 6)  NULL,
    [D4]            DECIMAL (20, 6)  NULL,
    [D5]            DECIMAL (20, 6)  NULL,
    [D6]            DECIMAL (20, 6)  NULL,
    [D7]            DECIMAL (20, 6)  NULL,
    [D8]            DECIMAL (20, 6)  NULL,
    [D9]            DECIMAL (20, 6)  NULL,
    [D10]           DECIMAL (20, 6)  NULL,
    [D11]           DECIMAL (20, 6)  NULL,
    [D12]           DECIMAL (20, 6)  NULL,
    [D13]           DECIMAL (20, 6)  NULL,
    [D14]           DECIMAL (20, 6)  NULL,
    [D15]           DECIMAL (20, 6)  NULL,
    [D16]           DECIMAL (20, 6)  NULL,
    [D17]           DECIMAL (20, 6)  NULL,
    [D18]           DECIMAL (20, 6)  NULL,
    [D19]           DECIMAL (20, 6)  NULL,
    [D20]           DECIMAL (20, 6)  NULL,
    [D21]           DECIMAL (20, 6)  NULL,
    [D22]           DECIMAL (20, 6)  NULL,
    [D23]           DECIMAL (20, 6)  NULL,
    [D24]           DECIMAL (20, 6)  NULL,
    [D25]           DECIMAL (20, 6)  NULL,
    [D26]           DECIMAL (20, 6)  NULL,
    [D27]           DECIMAL (20, 6)  NULL,
    [D28]           DECIMAL (20, 6)  NULL,
    [D29]           DECIMAL (20, 6)  NULL,
    [D30]           DECIMAL (20, 6)  NULL,
    [D31]           DECIMAL (20, 6)  NULL,
    [TOTAL_PLUS]    DECIMAL (20, 6)  NULL,
    [TOTAL_MINUS]   DECIMAL (20, 6)  NULL,
    [TOTAL]         DECIMAL (20, 6)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PRR_OVERHOURS_DATA_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PRR_OVERHOURS_DATA_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PRR_OVERHOURS] ([ID]) ON DELETE CASCADE
);

