CREATE TABLE [dbo].[PRR_2WORKSHIFT_DATA] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [EMPLID]      INT              NOT NULL,
    [D1]          NVARCHAR (5)     NULL,
    [D2]          NVARCHAR (5)     NULL,
    [D3]          NVARCHAR (5)     NULL,
    [D4]          NVARCHAR (5)     NULL,
    [D5]          NVARCHAR (5)     NULL,
    [D6]          NVARCHAR (5)     NULL,
    [D7]          NVARCHAR (5)     NULL,
    [D8]          NVARCHAR (5)     NULL,
    [D9]          NVARCHAR (5)     NULL,
    [D10]         NVARCHAR (5)     NULL,
    [D11]         NVARCHAR (5)     NULL,
    [D12]         NVARCHAR (5)     NULL,
    [D13]         NVARCHAR (5)     NULL,
    [D14]         NVARCHAR (5)     NULL,
    [D15]         NVARCHAR (5)     NULL,
    [D16]         NVARCHAR (5)     NULL,
    [D17]         NVARCHAR (5)     NULL,
    [D18]         NVARCHAR (5)     NULL,
    [D19]         NVARCHAR (5)     NULL,
    [D20]         NVARCHAR (5)     NULL,
    [D21]         NVARCHAR (5)     NULL,
    [D22]         NVARCHAR (5)     NULL,
    [D23]         NVARCHAR (5)     NULL,
    [D24]         NVARCHAR (5)     NULL,
    [D25]         NVARCHAR (5)     NULL,
    [D26]         NVARCHAR (5)     NULL,
    [D27]         NVARCHAR (5)     NULL,
    [D28]         NVARCHAR (5)     NULL,
    [D29]         NVARCHAR (5)     NULL,
    [D30]         NVARCHAR (5)     NULL,
    [D31]         NVARCHAR (5)     NULL,
    [TOTAL1]      DECIMAL (16, 2)  NULL,
    [TOTALNIGHT]  DECIMAL (16, 2)  NULL,
    [TOTALDAY]    DECIMAL (16, 2)  NULL,
    [TFROM1]      DATETIME         NULL,
    [TFROM2]      DATETIME         NULL,
    [TTO1]        DATETIME         NULL,
    [TTO2]        DATETIME         NULL,
    [WTID]        INT              NULL,
    [GROUPCOLUMN] NVARCHAR (250)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PRR_2WORKSHIFT_DATA_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PRR_2WORKSHIFT_DATA_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[PRR_2WORKSHIFT] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PRR_2WORKSHIFT_DATA]
    ON [dbo].[PRR_2WORKSHIFT_DATA]([VNESHID] ASC);

