CREATE TABLE [dbo].[PU_SEARCH_RECIPIENTS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NOT NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [SEARCHID] INT              NOT NULL,
    [EMPID]    INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PU_SEARCH_RECIPIENTS_EMPID] FOREIGN KEY ([EMPID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_PU_SEARCH_RECIPIENTS_SEARCHID] FOREIGN KEY ([SEARCHID]) REFERENCES [dbo].[PU_SEARCH] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_PU_SEARCH_RECIPIENTS]
    ON [dbo].[PU_SEARCH_RECIPIENTS]([SEARCHID] ASC);

