CREATE TABLE [dbo].[REP_USERNUMBERS] (
    [REPORTOID] INT      NOT NULL,
    [USERID]    INT      NOT NULL,
    [DD]        DATETIME NOT NULL,
    [LASTNN]    INT      NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_REP_USERNUMBERS]
    ON [dbo].[REP_USERNUMBERS]([REPORTOID] ASC, [USERID] ASC, [DD] ASC) WITH (FILLFACTOR = 90);

