CREATE TABLE [dbo].[REVCH_MODEL_REQOPTIONGR] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [ACTION]      INT              NOT NULL,
    [OPTIONGRID]  INT              NOT NULL,
    [OPTIONGRID2] INT              NULL,
    [OPTIONGRID3] INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [OPTIONGRID4] INT              NULL,
    [OPTIONGRID5] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID_copy] FOREIGN KEY ([OPTIONGRID]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID2_copy] FOREIGN KEY ([OPTIONGRID2]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_PR_MODEL_REQOPTIONGR_OPTIONGRID3_copy] FOREIGN KEY ([OPTIONGRID3]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_REVCH_MODEL_REQOPTIONGR_OPTIONGRID4] FOREIGN KEY ([OPTIONGRID4]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_REVCH_MODEL_REQOPTIONGR_OPTIONGRID5] FOREIGN KEY ([OPTIONGRID5]) REFERENCES [dbo].[PR_MODELTYPE_OPTION_GR] ([ID]),
    CONSTRAINT [FK_REVCH_MODEL_REQOPTIONGR_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[REVCH_MODEL] ([ID])
);

