CREATE TABLE [dbo].[REVCH_CHANGE_COMP] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NOT NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [PACT]        INT              NOT NULL,
    [MODELID]     INT              NOT NULL,
    [COMPMODELID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REVCH_CHANGE_COMP_COMPMODELID] FOREIGN KEY ([COMPMODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_COMP_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_COMP_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[REVCH_CHANGE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_REVCH_CHANGE_COMP]
    ON [dbo].[REVCH_CHANGE_COMP]([VNESHID] ASC);

