CREATE TABLE [dbo].[REVCH_CHANGE_REV] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [REVID]   INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REVCH_CHANGE_REV_REVID] FOREIGN KEY ([REVID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_REV_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[REVCH_CHANGE] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_REVCH_CHANGE_REV_1]
    ON [dbo].[REVCH_CHANGE_REV]([VNESHID] ASC, [REVID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_REVCH_CHANGE_REV]
    ON [dbo].[REVCH_CHANGE_REV]([VNESHID] ASC);

