CREATE TABLE [dbo].[REVCH_MODEL_OPTIONS] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NOT NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [ACTION]        INT              NOT NULL,
    [OPTIONID]      INT              NOT NULL,
    [PREDEFINEDOPT] INT              NULL,
    [OVERPTYPE]     INT              NULL,
    [CMP_OUT2]      NVARCHAR (200)   NULL,
    [CUSTOM4GROUP]  INT              NULL,
    [CUSTOM4ID]     INT              NULL,
    [VNESHID]       INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PR_MODEL_OPTIONS_CUSTOM4GROUP_copy] FOREIGN KEY ([CUSTOM4GROUP]) REFERENCES [dbo].[COM_CUST_GROUP] ([ID]),
    CONSTRAINT [FK_PR_MODEL_OPTIONS_CUSTOM4ID_copy] FOREIGN KEY ([CUSTOM4ID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_PR_MODEL_OPTIONS_OPTIONID_copy] FOREIGN KEY ([OPTIONID]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_MODEL_OPTIONS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[REVCH_MODEL] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_PR_MODEL_OPTIONS_UNI]
    ON [dbo].[REVCH_MODEL_OPTIONS]([VNESHID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PR_MODEL_OPTIONS_GID]
    ON [dbo].[REVCH_MODEL_OPTIONS]([GID] ASC);

