CREATE TABLE [dbo].[REVCH_MODEL_MODELS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [MODELID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REVCH_MODEL_MODELS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_REVCH_MODEL_MODELS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[REVCH_MODEL] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_REVCH_MODEL_MODELS_1]
    ON [dbo].[REVCH_MODEL_MODELS]([VNESHID] ASC, [MODELID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_REVCH_MODEL_MODELS]
    ON [dbo].[REVCH_MODEL_MODELS]([VNESHID] ASC);

