CREATE TABLE [dbo].[REVCH_CHANGE_SW] (
    [ID]              INT              IDENTITY (1, 1) NOT NULL,
    [GID]             UNIQUEIDENTIFIER NOT NULL,
    [S_CR]            INT              NOT NULL,
    [S_CDT]           DATETIME         NOT NULL,
    [S_MR]            INT              NULL,
    [S_MDT]           DATETIME         NULL,
    [ARC]             INT              NULL,
    [VNESHID]         INT              NOT NULL,
    [SWID]            INT              NULL,
    [SWMODE]          INT              NULL,
    [SWVERSIONID]     INT              NULL,
    [ONLYOPTION]      INT              NULL,
    [SWTOOLID]        INT              NULL,
    [ONLYOPTION2]     INT              NULL,
    [ONLYOPTION3]     INT              NULL,
    [PACT]            INT              NOT NULL,
    [SWID_OLD]        INT              NULL,
    [SWTOOLID_OLD]    INT              NULL,
    [SWVERSIONID_OLD] INT              NULL,
    [ONLYOPTION_OLD]  INT              NULL,
    [ONLYOPTION2_OLD] INT              NULL,
    [ONLYOPTION3_OLD] INT              NULL,
    [SWMODE_OLD]      INT              NULL,
    CONSTRAINT [PK__REVCH_CH__3214EC275B02C996] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REVCH_CHANGE_SW_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_ONLYOPTION_OLD] FOREIGN KEY ([ONLYOPTION_OLD]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_ONLYOPTION2] FOREIGN KEY ([ONLYOPTION2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_ONLYOPTION2_OLD] FOREIGN KEY ([ONLYOPTION2_OLD]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_ONLYOPTION3] FOREIGN KEY ([ONLYOPTION3]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_ONLYOPTION3_OLD] FOREIGN KEY ([ONLYOPTION3_OLD]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_SWID] FOREIGN KEY ([SWID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_SWID_OLD] FOREIGN KEY ([SWID_OLD]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_SWTOOLID] FOREIGN KEY ([SWTOOLID]) REFERENCES [dbo].[SW_TOOLS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_SWTOOLID_OLD] FOREIGN KEY ([SWTOOLID_OLD]) REFERENCES [dbo].[SW_TOOLS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_SWVERSIONID] FOREIGN KEY ([SWVERSIONID]) REFERENCES [dbo].[SW_TOOL_VERSIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_SWVERSIONID_OLD] FOREIGN KEY ([SWVERSIONID_OLD]) REFERENCES [dbo].[SW_TOOL_VERSIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_SW_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[REVCH_CHANGE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_REVCH_CHANGE_SW]
    ON [dbo].[REVCH_CHANGE_SW]([VNESHID] ASC);

