CREATE TABLE [dbo].[REVCH_CHANGE_BOM2] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [VNESHID]       INT              NOT NULL,
    [PACT]          INT              NOT NULL,
    [BOMID]         INT              NOT NULL,
    [PARTMODELID]   INT              NOT NULL,
    [PARTONLYREVID] INT              NULL,
    [ONLYOPTION]    INT              NULL,
    [ONLYOPTION2]   INT              NULL,
    [ONLYOPTION3]   INT              NULL,
    [QTY]           DECIMAL (10, 4)  NULL,
    [TYPICAL2NAV]   INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REVCH_CHANGE_BOM2_BOMID] FOREIGN KEY ([BOMID]) REFERENCES [dbo].[PR_MODELTYPE_BOM] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_BOM2_ONLYOPTION] FOREIGN KEY ([ONLYOPTION]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_BOM2_ONLYOPTION2] FOREIGN KEY ([ONLYOPTION2]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_BOM2_ONLYOPTION3] FOREIGN KEY ([ONLYOPTION3]) REFERENCES [dbo].[PR_MODELTYPE_OPTIONS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_BOM2_PARTMODELID] FOREIGN KEY ([PARTMODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_BOM2_PARTONLYREVID] FOREIGN KEY ([PARTONLYREVID]) REFERENCES [dbo].[PR_REVISION] ([ID]),
    CONSTRAINT [FK_REVCH_CHANGE_BOM2_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[REVCH_CHANGE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_REVCH_CHANGE_BOM2]
    ON [dbo].[REVCH_CHANGE_BOM2]([VNESHID] ASC);

