CREATE TABLE [dbo].[SH_CHECK_HISTORY] (
    [OPERID]    INT NOT NULL,
    [SHORDERID] INT NOT NULL,
    [DEVICEID]  INT DEFAULT ((-1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([OPERID] ASC, [SHORDERID] ASC, [DEVICEID] ASC)
);

