CREATE TABLE [dbo].[SH_FILEANDPICT_PARAMS2PACKET] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [PARAMID] INT              NOT NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SH_FILEANDPICT_PARAMS2PACKET_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SH_FILEANDPICT_PARAMS2PACKET]
    ON [dbo].[SH_FILEANDPICT_PARAMS2PACKET]([PARAMID] ASC);

