CREATE TABLE [dbo].[SH_OUTXMLSETTINGS_T] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [MTID]    INT              NOT NULL,
    [MTMODE]  INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SH_OUTXMLSETTINGS_T_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_SH_OUTXMLSETTINGS_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SH_OUTXMLSETTINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SH_OUTXMLSETTINGS_T_2]
    ON [dbo].[SH_OUTXMLSETTINGS_T]([VNESHID] ASC, [MTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SH_OUTXMLSETTINGS_T]
    ON [dbo].[SH_OUTXMLSETTINGS_T]([VNESHID] ASC);

