CREATE TABLE [dbo].[SH_REMOTE_RECIPIENTS_MODELS] (
    [ID]              INT              IDENTITY (1, 1) NOT NULL,
    [GID]             UNIQUEIDENTIFIER NOT NULL,
    [S_CR]            INT              NOT NULL,
    [S_CDT]           DATETIME         NOT NULL,
    [S_MR]            INT              NULL,
    [S_MDT]           DATETIME         NULL,
    [ARC]             INT              NULL,
    [REMOTE_RECIP_ID] INT              NOT NULL,
    [MODELID]         INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SH_REMOTE_RECIPIENTS_MODELS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_SH_REMOTE_RECIPIENTS_MODELS_REMOTE_RECIP_ID] FOREIGN KEY ([REMOTE_RECIP_ID]) REFERENCES [dbo].[SH_REMOTE_RECIPIENTS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SH_REMOTE_RECIPIENTS_MODELS]
    ON [dbo].[SH_REMOTE_RECIPIENTS_MODELS]([REMOTE_RECIP_ID] ASC);

