CREATE TABLE [dbo].[SH_SETTINGS_TO_CUSTOMER] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [SETTINGSID] INT              NOT NULL,
    [MSGTO]      NVARCHAR (500)   NULL,
    [MSGCC]      NVARCHAR (500)   NULL,
    [CUSTOMERID] INT              NOT NULL,
    CONSTRAINT [PK__SH_SETTI__3214EC2750B1B6BF] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SH_SETTINGS_TO_CUSTOMER_DEPID] FOREIGN KEY ([CUSTOMERID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_SH_SETTINGS_TO_CUSTOMER_SETTINGSID] FOREIGN KEY ([SETTINGSID]) REFERENCES [dbo].[SH_SETTINGS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SH_SETTINGS_TO_CUSTOMER]
    ON [dbo].[SH_SETTINGS_TO_CUSTOMER]([SETTINGSID] ASC);

