CREATE TABLE [dbo].[SH_STOCKS_PLACES] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [SCOLUMN]  NVARCHAR (10)    NOT NULL,
    [SROW]     NVARCHAR (10)    NOT NULL,
    [NAME]     NVARCHAR (21)    NOT NULL,
    [DISABLED] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SH_STOCKS_PLACES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SH_STOCKS] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SH_STOCKS_PLACES_UNI]
    ON [dbo].[SH_STOCKS_PLACES]([VNESHID] ASC, [NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SH_STOCKS_PLACES]
    ON [dbo].[SH_STOCKS_PLACES]([VNESHID] ASC);

