CREATE TABLE [dbo].[SL_LAST_TS] (
    [ID]          INT        NOT NULL,
    [LAST_TS]     BINARY (8) NULL,
    [LAST_UPDATE] DATE       NULL,
    CONSTRAINT [PK_SL_LAST_TS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

