CREATE TABLE [dbo].[SL_MODEL_ZIPFILE_GUIDS] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [MODELID]        INT              NOT NULL,
    [SW_TOOL_VER_ID] INT              NOT NULL,
    [CRMGUID]        UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_SL_MODEL_ZIPFILE_GUIDS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SL_MODEL_ZIPFILE_GUIDS] TO [IPG-DOMAIN\IPGL_Integr_MSCRM]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SL_MODEL_ZIPFILE_GUIDS] TO [EMEA\DEPCS]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SL_MODEL_ZIPFILE_GUIDS] TO [IPG-DOMAIN\IPGL_Integr_MSCRM]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SL_MODEL_ZIPFILE_GUIDS] TO [EMEA\DEPCS]
    AS [dbo];

