CREATE TABLE [dbo].[SL_MODEL_ZIPFILE_GUIDS] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [MODELID]        INT              NOT NULL,
    [SW_TOOL_VER_ID] INT              NOT NULL,
    [CRMGUID]        UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_SL_MODEL_ZIPFILE_GUIDS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

