CREATE TABLE [dbo].[SL_OPTION_ZIPFILE_GUIDS] (
    [ID]             INT              IDENTITY (1, 1) NOT NULL,
    [OPTID]          INT              NOT NULL,
    [SW_TOOL_VER_ID] INT              NOT NULL,
    [CRMGUID]        UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_SL_OPTION_ZIPFILE_GUIDS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SL_OPTION_ZIPFILE_GUIDS]
    ON [dbo].[SL_OPTION_ZIPFILE_GUIDS]([OPTID] ASC, [SW_TOOL_VER_ID] ASC);

