CREATE TABLE [dbo].[SL_PRODUCT_CH_SALES_INF] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [OFFICEID] INT              NOT NULL,
    [PENABLE]  INT              NOT NULL,
    [NAME]     NVARCHAR (300)   NULL,
    [DESCSTR]  NVARCHAR (300)   NULL,
    [NPRICE]   DECIMAL (18, 2)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SL_PRODUCT_CH_SALES_INF_OFFICEID] FOREIGN KEY ([OFFICEID]) REFERENCES [dbo].[SL_OFFICES] ([ID]),
    CONSTRAINT [FK_SL_PRODUCT_CH_SALES_INF_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SL_PRODUCT_CH] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SL_PRODUCT_CH_SALES_INF]
    ON [dbo].[SL_PRODUCT_CH_SALES_INF]([VNESHID] ASC);

