CREATE TABLE [dbo].[SM_EMAIL_BOX_CHANGED_SUBSCRIBERS] (
    [ID]              INT              IDENTITY (1, 1) NOT NULL,
    [GID]             UNIQUEIDENTIFIER NULL,
    [S_CR]            INT              NOT NULL,
    [S_CDT]           DATETIME         NOT NULL,
    [S_MR]            INT              NULL,
    [S_MDT]           DATETIME         NULL,
    [ARC]             INT              NULL,
    [SM_EMAIL_BOX_ID] INT              NOT NULL,
    [EMPLOYEE_ID]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SC_DEP_CHANGED_SUBSCRIBERS_EMPLOYEE_ID] FOREIGN KEY ([EMPLOYEE_ID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_SM_SC_DEP_CHANGED_SUBSCRIBERS_SM_EMAIL_BOX_ID] FOREIGN KEY ([SM_EMAIL_BOX_ID]) REFERENCES [dbo].[SM_EMAIL_BOXES] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SC_DEP_CHANGED_SUBSCRIBERS]
    ON [dbo].[SM_EMAIL_BOX_CHANGED_SUBSCRIBERS]([SM_EMAIL_BOX_ID] ASC);

