CREATE TABLE [dbo].[SM_IN_ATTACHEMENTS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [FILENAME]  NVARCHAR (250)   NOT NULL,
    [FILEDATE]  DATETIME         NOT NULL,
    [FILESIZE]  INT              NULL,
    [FILEBLOB]  IMAGE            NULL,
    [ATTID]     NVARCHAR (100)   NULL,
    [BOXID]     INT              NOT NULL,
    [CONTENTID] NVARCHAR (250)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_IN_ATTACHEMENTS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_INBOX] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_IN_ATTACHEMENTS_BOXID_ATTID]
    ON [dbo].[SM_IN_ATTACHEMENTS]([BOXID] ASC, [ATTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SM_IN_ATTACHEMENTS]
    ON [dbo].[SM_IN_ATTACHEMENTS]([VNESHID] ASC);

