CREATE TABLE [dbo].[SM_OUT_ATTACHEMENTS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [FILENAME] NVARCHAR (250)   NOT NULL,
    [FILEDATE] DATETIME         NOT NULL,
    [FILESIZE] INT              NULL,
    [FILEBLOB] IMAGE            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_OUT_ATTACHEMENTS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_OUTGOING] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_OUT_ATTACHEMENTS]
    ON [dbo].[SM_OUT_ATTACHEMENTS]([VNESHID] ASC);

