CREATE TABLE [dbo].[SM_PARAMS_IN_SERVPROT_T_T] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [PARAMID]  INT              NOT NULL,
    [POSORDER] INT              NOT NULL,
    [EXTNAME]  NVARCHAR (1500)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_PARAMS_IN_SERVPROT_T_T_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_SM_PARAMS_IN_SERVPROT_T_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_PARAMS_IN_SERVPROT_T] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_PARAMS_IN_SERVPROT_T_T]
    ON [dbo].[SM_PARAMS_IN_SERVPROT_T_T]([VNESHID] ASC);

