CREATE TABLE [dbo].[SM_PARAMS_IN_SERVPROT_T] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [GROUPNAME] NVARCHAR (150)   NOT NULL,
    [POSORDER]  INT              NOT NULL,
    [EXTNAME]   NVARCHAR (1500)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_PARAMS_IN_SERVPROT_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_PARAMS_IN_SERVPROT] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_PARAMS_IN_SERVPROT_T]
    ON [dbo].[SM_PARAMS_IN_SERVPROT_T]([VNESHID] ASC);

