CREATE TABLE [dbo].[SM_SLA_VIOLATION_EMAILS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SLA_VIOLATION_EMAILS_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_SM_SLA_VIOLATION_EMAILS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SLA] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SLA_VIOLATION_EMAILS]
    ON [dbo].[SM_SLA_VIOLATION_EMAILS]([VNESHID] ASC);

