CREATE TABLE [dbo].[SM_SERVICECASE_ITEMS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [MODELID]  INT              NOT NULL,
    [SN]       NVARCHAR (50)    NOT NULL,
    [DEVICEID] INT              NULL,
    [FRID]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICECASE_ITEMS_DEVICEID] FOREIGN KEY ([DEVICEID]) REFERENCES [dbo].[PR_DEVICE] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_ITEMS_FRID] FOREIGN KEY ([FRID]) REFERENCES [dbo].[FC_REPORT] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_ITEMS_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_ITEMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICECASE] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECASE_ITEMS]
    ON [dbo].[SM_SERVICECASE_ITEMS]([VNESHID] ASC);

