CREATE TABLE [dbo].[SM_SERVICECASE_BP] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [CUSTID]  INT              NOT NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICECASE_BP_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_BP_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICECASE] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SERVICECASE_BP_CUSTID]
    ON [dbo].[SM_SERVICECASE_BP]([VNESHID] ASC, [CUSTID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECASE_BP]
    ON [dbo].[SM_SERVICECASE_BP]([VNESHID] ASC);

