CREATE TABLE [dbo].[SM_SERVICECALL] (
    [ID]            INT              IDENTITY (1, 1) NOT NULL,
    [GID]           UNIQUEIDENTIFIER NULL,
    [S_CR]          INT              NOT NULL,
    [S_CDT]         DATETIME         NOT NULL,
    [S_MR]          INT              NULL,
    [S_MDT]         DATETIME         NULL,
    [ARC]           INT              NULL,
    [DD]            DATETIME         NOT NULL,
    [CUSTID]        INT              NULL,
    [CONTACTID]     INT              NULL,
    [SCTYPE]        INT              NOT NULL,
    [SCDIRECTION]   INT              NOT NULL,
    [SUBJ]          NVARCHAR (1024)  NOT NULL,
    [SCBODY]        NTEXT            NULL,
    [MODELID]       INT              NULL,
    [SN]            NVARCHAR (50)    NULL,
    [CASEID]        INT              NULL,
    [MSGID]         INT              NULL,
    [UNREAD]        INT              NULL,
    [REPLY2ID]      INT              NULL,
    [SENT_DT]       DATETIME         NULL,
    [NEWSERVCASE]   INT              NULL,
    [SENT_UID]      INT              NULL,
    [REPLY_DT]      DATETIME         NULL,
    [REPLY_UID]     INT              NULL,
    [SCBODYRTF]     NTEXT            NULL,
    [SDEPID]        INT              NOT NULL,
    [MSGPLAINTEXT]  INT              NULL,
    [READBY]        INT              NULL,
    [FORWARD2ID]    INT              NULL,
    [EXCLUDEFROMSR] INT              NULL,
    [HIGHLIGHT]     INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICECALL_CASEID] FOREIGN KEY ([CASEID]) REFERENCES [dbo].[SM_SERVICECASE] ([ID]),
    CONSTRAINT [FK_SM_SERVICECALL_CONTACTID] FOREIGN KEY ([CONTACTID]) REFERENCES [dbo].[COM_CUST_CONTACTS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECALL_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_SM_SERVICECALL_DEPID] FOREIGN KEY ([SDEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECALL_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECALL_REPLY_UID] FOREIGN KEY ([REPLY_UID]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECALL_SENT_UID] FOREIGN KEY ([SENT_UID]) REFERENCES [dbo].[DEF_USERS] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECALL_UNREAD]
    ON [dbo].[SM_SERVICECALL]([UNREAD] ASC) WHERE ([UNREAD] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECALL_REPLY2ID]
    ON [dbo].[SM_SERVICECALL]([REPLY2ID] ASC) WHERE ([REPLY2ID] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SERVICECALL_MSGID]
    ON [dbo].[SM_SERVICECALL]([MSGID] ASC) WHERE ([MSGID] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECALL_DD]
    ON [dbo].[SM_SERVICECALL]([DD] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECALL_CASEID]
    ON [dbo].[SM_SERVICECALL]([CASEID] ASC) WHERE ([CASEID] IS NOT NULL);

