CREATE TABLE [dbo].[SM_SERVICECENTER_EMPL] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMPLID]  INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICECENTER_EMPL_EMPLID] FOREIGN KEY ([EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_SM_SERVICECENTER_EMPL_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICECENTER] ([ID]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SERVICECENTER_EMPL_UNIQUE]
    ON [dbo].[SM_SERVICECENTER_EMPL]([EMPLID] ASC, [VNESHID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECENTER_EMPL]
    ON [dbo].[SM_SERVICECENTER_EMPL]([VNESHID] ASC);

