CREATE TABLE [dbo].[SM_SERVICEPROTOCOL_REMOVED] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [VNESHID]     INT              NOT NULL,
    [REMOVEROWID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_REMOVED_REMOVEROWID] FOREIGN KEY ([REMOVEROWID]) REFERENCES [dbo].[PR_OPERATION_UNINSTALL] ([ID]),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_REMOVED_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICEPROTOCOL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICEPROTOCOL_REMOVED]
    ON [dbo].[SM_SERVICEPROTOCOL_REMOVED]([VNESHID] ASC);

