CREATE TABLE [dbo].[SM_SERVICE_CALL_TINT_CC] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [EMAIL]   NVARCHAR (250)   NOT NULL,
    [NAME]    NVARCHAR (250)   NULL,
    [UID]     NVARCHAR (250)   NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICE_CALL_TINT_CC_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICECALL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICE_CALL_TINT_CC]
    ON [dbo].[SM_SERVICE_CALL_TINT_CC]([VNESHID] ASC);

