CREATE TABLE [dbo].[SM_SERVICEPROTOCOL_INSTALLED] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [VNESHID]      INT              NOT NULL,
    [CUSTOMERPART] INT              NOT NULL,
    [INSTALLROWID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_INSTALLED_INSTALLROWID] FOREIGN KEY ([INSTALLROWID]) REFERENCES [dbo].[PR_OPERATION_INSTALL] ([ID]),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_INSTALLED_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICEPROTOCOL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICEPROTOCOL_INSTALLED]
    ON [dbo].[SM_SERVICEPROTOCOL_INSTALLED]([VNESHID] ASC);

