CREATE TABLE [dbo].[SM_SERVICECENTER] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [GID]         UNIQUEIDENTIFIER NULL,
    [S_CR]        INT              NOT NULL,
    [S_CDT]       DATETIME         NOT NULL,
    [S_MR]        INT              NULL,
    [S_MDT]       DATETIME         NULL,
    [ARC]         INT              NULL,
    [SDEPID]      INT              NOT NULL,
    [NAME]        NVARCHAR (50)    NOT NULL,
    [REMARK]      NTEXT            NULL,
    [DEFSERVCENT] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICECENTER_SDEPID] FOREIGN KEY ([SDEPID]) REFERENCES [dbo].[SM_EMAIL_BOXES] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SERVICECENTER_UNIQUE]
    ON [dbo].[SM_SERVICECENTER]([SDEPID] ASC, [DEFSERVCENT] ASC) WHERE ([DEFSERVCENT]=(1));


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SERVICECENTER_NAME]
    ON [dbo].[SM_SERVICECENTER]([SDEPID] ASC, [NAME] ASC);

