CREATE TABLE [dbo].[SM_SERVICEPROTOCOL_TIMES] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [WT_START] DATETIME         NOT NULL,
    [WT_END]   DATETIME         NOT NULL,
    [WT_PAUSE] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_TIMES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICEPROTOCOL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICEPROTOCOL_TIMES]
    ON [dbo].[SM_SERVICEPROTOCOL_TIMES]([VNESHID] ASC);

