CREATE TABLE [dbo].[SM_SERVICECASE] (
    [ID]                  INT              IDENTITY (1, 1) NOT NULL,
    [GID]                 UNIQUEIDENTIFIER NULL,
    [S_S]                 INT              NOT NULL,
    [S_CR]                INT              NOT NULL,
    [S_CDT]               DATETIME         NOT NULL,
    [S_MR]                INT              NULL,
    [S_MDT]               DATETIME         NULL,
    [ARC]                 INT              NULL,
    [CUSTID]              INT              NOT NULL,
    [SUBJ]                NVARCHAR (1024)  NOT NULL,
    [DD]                  DATE             NOT NULL,
    [ND]                  NVARCHAR (12)    NOT NULL,
    [REMARK]              NTEXT            NULL,
    [CREATED4CALLID]      INT              NULL,
    [NNC]                 INT              NULL,
    [DCLOSE]              DATETIME         NULL,
    [RMA_SC_TYPE]         INT              NULL,
    [RMA_SC_REQUESTED]    DATETIME         NULL,
    [SERVORDID]           INT              NULL,
    [SDEPID]              INT              NOT NULL,
    [CUSTID_4SERVORD]     INT              NULL,
    [RESP_EMPLID]         INT              NOT NULL,
    [PARENTID]            INT              NULL,
    [MERGED2ID]           INT              NULL,
    [FAILURE_DESCRIPTION] NTEXT            NULL,
    [RESPSERV]            INT              NULL,
    [REMINDER_DATETIME]   DATETIME         NULL,
    [REMINDER_SENT]       INT              CONSTRAINT [DF_SM_SERVICECASE_REMINDER_SENT] DEFAULT ((0)) NULL,
    [REMINDER_USERID]     INT              NULL,
    [CONTACTID]           INT              NULL,
    [CONTACTID_4SERVORD]  INT              NULL,
    [WAITRESPONSE_FLAG]   INT              NULL,
    [MOD_REQ]             INT              NULL,
    [SHARE2SDEPID]        INT              NULL,
    CONSTRAINT [PK__SM_SERVI__3214EC2757C8C8A2] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICECASE_CONTACTID] FOREIGN KEY ([CONTACTID]) REFERENCES [dbo].[COM_CUST_CONTACTS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_CONTACTID_4SERVORD] FOREIGN KEY ([CONTACTID_4SERVORD]) REFERENCES [dbo].[COM_CUST_CONTACTS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_CUSTID] FOREIGN KEY ([CUSTID]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_CUSTID_4SERVORD] FOREIGN KEY ([CUSTID_4SERVORD]) REFERENCES [dbo].[COM_CUSTOMER] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_PARENTID] FOREIGN KEY ([PARENTID]) REFERENCES [dbo].[SM_SERVICECASE] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_RESP_EMPLID] FOREIGN KEY ([RESP_EMPLID]) REFERENCES [dbo].[COM_EMPLOYEE] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_RESPSERV] FOREIGN KEY ([RESPSERV]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_SDEPID] FOREIGN KEY ([SDEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_SM_SERVICECASE_SERVORDID] FOREIGN KEY ([SERVORDID]) REFERENCES [dbo].[PR_PRORDER] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SERVICECASE_ND]
    ON [dbo].[SM_SERVICECASE]([ND] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECASE_DD]
    ON [dbo].[SM_SERVICECASE]([DD] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICECASE_CREATED4CALLID]
    ON [dbo].[SM_SERVICECASE]([CREATED4CALLID] ASC);

