CREATE TABLE [dbo].[SM_SERVICE_CALL_T] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [CNTID]     INT              NOT NULL,
    [USEASCOPY] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICE_CALL_T_CNTID] FOREIGN KEY ([CNTID]) REFERENCES [dbo].[COM_CUST_CONTACTS] ([ID]),
    CONSTRAINT [FK_SM_SERVICE_CALL_T_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICECALL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICE_CALL_T]
    ON [dbo].[SM_SERVICE_CALL_T]([VNESHID] ASC);

