CREATE TABLE [dbo].[SM_SERVICE_CALL_SHARE] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NOT NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [TODEPID] INT              NOT NULL,
    [REMARK]  NTEXT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICE_CALL_SHARE_TODEPID] FOREIGN KEY ([TODEPID]) REFERENCES [dbo].[SM_EMAIL_BOXES] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SERVICE_CALL_SHARE_VHESHID_TODEPID]
    ON [dbo].[SM_SERVICE_CALL_SHARE]([VNESHID] ASC, [TODEPID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICE_CALL_SHARE]
    ON [dbo].[SM_SERVICE_CALL_SHARE]([VNESHID] ASC);

