CREATE TABLE [dbo].[SM_SLA_LASTNOTIFICATION] (
    [SLAID]      INT  NOT NULL,
    [NOTIFYDATE] DATE NOT NULL,
    [MODE]       INT  NULL,
    [RECID]      INT  NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SM_SLA_LASTNOTIFICATION]
    ON [dbo].[SM_SLA_LASTNOTIFICATION]([SLAID] ASC, [MODE] ASC, [RECID] ASC, [NOTIFYDATE] ASC);

