CREATE TABLE [dbo].[SM_SERVICEPROTOCOL_PARAMS] (
    [ID]         INT              IDENTITY (1, 1) NOT NULL,
    [GID]        UNIQUEIDENTIFIER NULL,
    [S_CR]       INT              NOT NULL,
    [S_CDT]      DATETIME         NOT NULL,
    [S_MR]       INT              NULL,
    [S_MDT]      DATETIME         NULL,
    [ARC]        INT              NULL,
    [PARAMROWID] INT              NULL,
    [VNESHID]    INT              NOT NULL,
    [PARAMID]    INT              NOT NULL,
    [PSETTINGID] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_PARAMS_PARAMID] FOREIGN KEY ([PARAMID]) REFERENCES [dbo].[PR_MODELTYPE_PARAMS] ([ID]),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_PARAMS_PARAMROWID] FOREIGN KEY ([PARAMROWID]) REFERENCES [dbo].[PR_OPERATION_PARAMS] ([ID]),
    CONSTRAINT [FK_SM_SERVICEPROTOCOL_PARAMS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_SERVICEPROTOCOL] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_SERVICEPROTOCOL_PARAMS]
    ON [dbo].[SM_SERVICEPROTOCOL_PARAMS]([VNESHID] ASC);

