CREATE TABLE [dbo].[SM_SCASE_REQUEST_ORDER_MAIL] (
    [ID]        INT             IDENTITY (1, 1) NOT NULL,
    [CASEID]    INT             NOT NULL,
    [USERID]    INT             NOT NULL,
    [FILE_BLOB] VARBINARY (MAX) NOT NULL,
    [FILE_NAME] NVARCHAR (500)  NOT NULL,
    [FILE_SIZE] INT             NULL,
    CONSTRAINT [PK_SM_SCASE_REQUEST_ORDER_MAIL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

