CREATE TABLE [dbo].[SM_WORKORDER_TASKS] (
    [ID]       INT              IDENTITY (1, 1) NOT NULL,
    [GID]      UNIQUEIDENTIFIER NULL,
    [S_CR]     INT              NOT NULL,
    [S_CDT]    DATETIME         NOT NULL,
    [S_MR]     INT              NULL,
    [S_MDT]    DATETIME         NULL,
    [ARC]      INT              NULL,
    [VNESHID]  INT              NOT NULL,
    [TASKID]   INT              NOT NULL,
    [REMARK]   NTEXT            NULL,
    [CMPL]     INT              NULL,
    [OPERID]   INT              NULL,
    [TASKTYPE] INT              NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SM_WORKORDER_TASKS_OPERID] FOREIGN KEY ([OPERID]) REFERENCES [dbo].[PR_OPERATION] ([ID]),
    CONSTRAINT [FK_SM_WORKORDER_TASKS_TASKID] FOREIGN KEY ([TASKID]) REFERENCES [dbo].[SM_SERVICETASKS] ([ID]),
    CONSTRAINT [FK_SM_WORKORDER_TASKS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SM_WORKORDER] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SM_WORKORDER_TASKS]
    ON [dbo].[SM_WORKORDER_TASKS]([VNESHID] ASC);

