CREATE TABLE [dbo].[SRV_CACHE_FC_GETCHILD_FARS] (
    [ID]                 INT      IDENTITY (1, 1) NOT NULL,
    [FC_REPORT_PARENTID] INT      NOT NULL,
    [FC_REPORT_CHILDID]  INT      NOT NULL,
    [FC_REPORT_S_DT]     DATETIME NOT NULL,
    PRIMARY KEY NONCLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SRV_CACHE_FC_GETCHILD_FARS_K2_K3_K4]
    ON [dbo].[SRV_CACHE_FC_GETCHILD_FARS]([FC_REPORT_PARENTID] ASC, [FC_REPORT_CHILDID] ASC, [FC_REPORT_S_DT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SRV_CACHE_FC_GETCHILD_FARS_K2_3]
    ON [dbo].[SRV_CACHE_FC_GETCHILD_FARS]([FC_REPORT_PARENTID] ASC)
    INCLUDE([FC_REPORT_CHILDID]);


GO
CREATE NONCLUSTERED INDEX [IX_SRV_CACHE_FC_GETCHILD_FARS_K2]
    ON [dbo].[SRV_CACHE_FC_GETCHILD_FARS]([FC_REPORT_PARENTID] ASC);

