CREATE TABLE [dbo].[SRV_TRACE] (
    [ID]    BIGINT           IDENTITY (1, 1) NOT NULL,
    [SESSG] UNIQUEIDENTIFIER NOT NULL,
    [SESSN] UNIQUEIDENTIFIER NOT NULL,
    [PRENT] BIGINT           NULL,
    [USRID] VARBINARY (85)   NOT NULL,
    [STAMP] DATETIME         NOT NULL,
    [THRID] INT              NOT NULL,
    [SHRTN] NVARCHAR (256)   NULL,
    [LONGN] NVARCHAR (MAX)   NULL,
    [SIZEE] FLOAT (53)       NULL,
    [LEAVE] BIGINT           NULL,
    [LEVEL] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

