CREATE TABLE [dbo].[SRV_TRACE_SESSION] (
    [ID]    BIGINT           IDENTITY (1, 1) NOT NULL,
    [SESSG] UNIQUEIDENTIFIER NOT NULL,
    [USRID] VARBINARY (85)   NOT NULL,
    [STAMP] DATETIME         NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

