CREATE TABLE [dbo].[SW_TOOL_VERSION_LINKS] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NOT NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [VERID]     INT              NULL,
    [OVERGROUP] INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SW_TOOL_VERSION_LINKS_OVERGROUP] FOREIGN KEY ([OVERGROUP]) REFERENCES [dbo].[SW_TOOL_GROUPS_FGROUP] ([ID]),
    CONSTRAINT [FK_SW_TOOL_VERSION_LINKS_VERID] FOREIGN KEY ([VERID]) REFERENCES [dbo].[SW_TOOL_VERSIONS] ([ID]),
    CONSTRAINT [FK_SW_TOOL_VERSION_LINKS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SW_TOOL_VERSIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SW_TOOL_VERSION_LINKS]
    ON [dbo].[SW_TOOL_VERSION_LINKS]([VNESHID] ASC);

