CREATE TABLE [dbo].[SW_TOOL_GROUPS_FGROUP] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [NAME]    NVARCHAR (200)   NOT NULL,
    [SORT]    INT              NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SW_TOOL_GROUPS_FGROUP_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SW_TOOL_GROUPS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SW_TOOL_GROUPS_FGROUP]
    ON [dbo].[SW_TOOL_GROUPS_FGROUP]([VNESHID] ASC);

