CREATE TABLE [dbo].[SYNC2_TABLES] (
    [ID]              INT              IDENTITY (1, 1) NOT NULL,
    [GID]             UNIQUEIDENTIFIER NULL,
    [S_CR]            INT              NOT NULL,
    [S_CDT]           DATETIME         NOT NULL,
    [S_MR]            INT              NULL,
    [S_MDT]           DATETIME         NULL,
    [ARC]             INT              NULL,
    [TABNAME]         NVARCHAR (100)   NOT NULL,
    [TORDER]          INT              NOT NULL,
    [SQLFILT]         NTEXT            NULL,
    [SQLORD]          NTEXT            NULL,
    [O_ADD]           INT              NULL,
    [DISABLE]         INT              NULL,
    [INCL_CHILDS]     INT              NULL,
    [REMARK]          NTEXT            NULL,
    [BACKDIRECTION]   INT              NULL,
    [PARENTID]        INT              NULL,
    [DELETESQL]       NTEXT            NULL,
    [KEYMARK]         NVARCHAR (10)    NULL,
    [KEYFIELD]        NVARCHAR (50)    NULL,
    [HASLONGBLOB]     INT              NULL,
    [SQL2CHECK]       NTEXT            NULL,
    [SQL2CHECKFILTER] NTEXT            NULL,
    [SQL2CHECKORDER]  NTEXT            NULL,
    [DISABLE_MDT]     INT              NULL,
    [OBJNAME]         NVARCHAR (100)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYNC2_TABLES_PARENTID] FOREIGN KEY ([PARENTID]) REFERENCES [dbo].[SYNC2_TABLES] ([ID])
);

