CREATE TABLE [dbo].[SYNC2_NOTIF_RECIPIENTS] (
    [ID]      INT              IDENTITY (1, 1) NOT NULL,
    [GID]     UNIQUEIDENTIFIER NULL,
    [S_CR]    INT              NOT NULL,
    [S_CDT]   DATETIME         NOT NULL,
    [S_MR]    INT              NULL,
    [S_MDT]   DATETIME         NULL,
    [ARC]     INT              NULL,
    [VNESHID] INT              NOT NULL,
    [NAME]    NVARCHAR (250)   NOT NULL,
    [EMAIL]   NVARCHAR (250)   NOT NULL,
    [UID]     NVARCHAR (250)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYNC2_NOTIF_RECIPIENTS_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[SYNC2_NOTIFICATIONS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_SYNC2_NOTIF_RECIPIENTS]
    ON [dbo].[SYNC2_NOTIF_RECIPIENTS]([VNESHID] ASC);

