CREATE TABLE [dbo].[SYNC2_MODELS_SETUP] (
    [ID]           INT              IDENTITY (1, 1) NOT NULL,
    [GID]          UNIQUEIDENTIFIER NULL,
    [S_S]          INT              NOT NULL,
    [S_CR]         INT              NOT NULL,
    [S_CDT]        DATETIME         NOT NULL,
    [S_MR]         INT              NULL,
    [S_MDT]        DATETIME         NULL,
    [ARC]          INT              NULL,
    [DEPID]        INT              NOT NULL,
    [MODELID]      INT              NULL,
    [MTID]         INT              NOT NULL,
    [TOLOCATIONID] INT              NOT NULL,
    [LASTSYNC]     DATETIME         NULL,
    [LASTCHECK]    DATETIME         NULL,
    CONSTRAINT [PK__SYNC2_MO__3214EC272F9ADBB7] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SYNC2_MODELS_SETUP_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID]),
    CONSTRAINT [FK_SYNC2_MODELS_SETUP_MODELID] FOREIGN KEY ([MODELID]) REFERENCES [dbo].[PR_MODELS] ([ID]),
    CONSTRAINT [FK_SYNC2_MODELS_SETUP_MTID] FOREIGN KEY ([MTID]) REFERENCES [dbo].[PR_MODELTYPE] ([ID]),
    CONSTRAINT [FK_SYNC2_MODELS_SETUP_TOLOCATIONID] FOREIGN KEY ([TOLOCATIONID]) REFERENCES [dbo].[COM_REMOTE] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SYNC2_MODELS_SETUP]
    ON [dbo].[SYNC2_MODELS_SETUP]([TOLOCATIONID] ASC, [MTID] ASC, [MODELID] ASC) WHERE ([MODELID] IS NOT NULL);

