CREATE TABLE [dbo].[temp_ldmGdata] (
    [SN]                         VARCHAR (11)  NOT NULL,
    [PN]                         VARCHAR (50)  NOT NULL,
    [A.CosN]                     INT           NOT NULL,
    [A.Serial]                   VARCHAR (11)  NOT NULL,
    [LegacyLivInv.Cos_Date]      SMALLDATETIME NOT NULL,
    [A.BoxN]                     INT           NOT NULL,
    [LegacyLivInv.Quantity]      TINYINT       NOT NULL,
    [LegacyLivInv.Qty_Init]      TINYINT       NOT NULL,
    [LegacyLivInv.Lambda]        REAL          NULL,
    [LegacyLivInv.ChipType]      VARCHAR (15)  NULL,
    [LegacyLivInv.Avg_P]         REAL          NULL,
    [LegacyLivInv.Ship_Date]     DATETIME2 (3) NULL,
    [LegacyLivInv.Cos_Gps]       VARCHAR (1)   NOT NULL,
    [LegacyLivInv.Shipped]       INT           NOT NULL,
    [LegacyLivInv.Test_Set]      VARCHAR (7)   NOT NULL,
    [LegacyLivInv.Empty]         INT           NOT NULL,
    [LegacyLivInv.Grade]         VARCHAR (5)   NULL,
    [LegacyLivInv.Location]      INT           NOT NULL,
    [LegacyLivInv.Pre_Ship]      INT           NOT NULL,
    [LegacyLivInv.Test_Status]   INT           NOT NULL,
    [LegacyLivInv.Countable]     BIT           NOT NULL,
    [LegacyLivInv.Fma]           INT           NOT NULL,
    [LegacyLivInv.Sorted]        INT           NOT NULL,
    [LegacyLivInv.Station]       VARCHAR (3)   NOT NULL,
    [LegacyLivInv.Pilot_Test]    INT           NOT NULL,
    [LegacyLivInv.Pilot_Sorted]  INT           NOT NULL,
    [LegacyLivInv.Follow_Up]     BIT           NOT NULL,
    [LegacyLivInv.Consolidated]  INT           NOT NULL,
    [LegacyLivInv.Ar_Coeff]      REAL          NULL,
    [LegacyLivQtInv.Ship_Date]   DATETIME2 (3) NULL,
    [LegacyLivQtInv.Quantity]    TINYINT       NOT NULL,
    [LegacyLivQtInv.Qty_Init]    TINYINT       NOT NULL,
    [LegacyLivQtInv.Lambda]      REAL          NULL,
    [LegacyLivQtInv.ChipType]    VARCHAR (17)  NOT NULL,
    [LegacyLivQtInv.Wafer]       VARCHAR (9)   NOT NULL,
    [LegacyLivQtInv.Qt_Date]     SMALLDATETIME NOT NULL,
    [LegacyLivQtInv.Epi]         VARCHAR (5)   NULL,
    [LegacyLivQtInv.N]           TINYINT       NULL,
    [LegacyLivQtInv.Pz]          VARCHAR (10)  NULL,
    [LegacyLivQtInv.Pr]          VARCHAR (7)   NOT NULL,
    [LegacyLivQtInv.WlGroup]     VARCHAR (5)   NOT NULL,
    [LegacyLivQtInv.Submount]    CHAR (1)      NOT NULL,
    [LegacyLivQtInv.Fc]          INT           NOT NULL,
    [LegacyLivQtInv.Ev]          INT           NOT NULL,
    [LegacyLivQtInv.Bond]        VARCHAR (5)   NOT NULL,
    [LegacyLivQtInv.Box_Gps]     VARCHAR (1)   NOT NULL,
    [LegacyLivQtInv.Shipped]     INT           NOT NULL,
    [LegacyLivQtInv.Empty]       INT           NOT NULL,
    [LegacyLivQtInv.Grade]       VARCHAR (5)   NULL,
    [LegacyLivQtInv.Location]    INT           NOT NULL,
    [LegacyLivQtInv.Pre_Ship]    INT           NOT NULL,
    [LegacyLivRes.Channel]       TINYINT       NOT NULL,
    [LegacyLivRes.Diode_N]       INT           NULL,
    [LegacyLivRes.I_Th]          FLOAT (53)    NULL,
    [LegacyLivRes.Slope]         REAL          NULL,
    [LegacyLivRes.Eff_Spec]      REAL          NULL,
    [LegacyLivRes.V_Spec]        FLOAT (53)    NULL,
    [LegacyLivRes.P_Spec]        FLOAT (53)    NULL,
    [LegacyLivRes.Wl_Spec]       FLOAT (53)    NULL,
    [LegacyLivRes.I_Spec]        REAL          NOT NULL,
    [LegacyLivRes.Shipped]       BIT           NULL,
    [LegacyLivRes.Fail_Pass]     BIT           NOT NULL,
    [LegacyLivRes.Cracked]       BIT           NOT NULL,
    [LegacyLivRes.Bar_N]         SMALLINT      NOT NULL,
    [LegacyLivRes.Test_Type]     TINYINT       NOT NULL,
    [LegacyLivRes.Delta_Lambda]  REAL          NULL,
    [LegacyLivRes.P_Max]         REAL          NULL,
    [LegacyLivRes.P_Nonlin]      REAL          NULL,
    [LegacyLivRes.Test_Date]     SMALLDATETIME NULL,
    [LegacyLivRes.Jump]          TINYINT       NOT NULL,
    [FacRetest.CosFacBox]        INT           NULL,
    [FacRetest.CosFacBox_Column] INT           NULL,
    [FacRetest.CosFacBox_Row]    INT           NULL
);

