CREATE TABLE [dbo].[TRB_REQUESTS_CHANGES] (
    [ID]        INT              IDENTITY (1, 1) NOT NULL,
    [GID]       UNIQUEIDENTIFIER NOT NULL,
    [S_S]       INT              NOT NULL,
    [S_CR]      INT              NOT NULL,
    [S_CDT]     DATETIME         NOT NULL,
    [S_MR]      INT              NULL,
    [S_MDT]     DATETIME         NULL,
    [ARC]       INT              NULL,
    [VNESHID]   INT              NOT NULL,
    [FIELDNAME] NVARCHAR (50)    NULL,
    [OLDVALUE]  NVARCHAR (4000)  NULL,
    [NEWVALUE]  NVARCHAR (4000)  NULL,
    [CHANGEDDT] DATETIME         CONSTRAINT [DF_TRB_REQUESTS_CHANGES_CHANGEDDT] DEFAULT (getdate()) NULL,
    [AUTHORID]  INT              NULL,
    [SENDED]    INT              NULL,
    [SENDEDDT]  DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TRB_REQUESTS_CHANGES_AUTHORID] FOREIGN KEY ([AUTHORID]) REFERENCES [dbo].[DEF_USERS] ([ID]),
    CONSTRAINT [FK_TRB_REQUESTS_CHANGES_VNESHID] FOREIGN KEY ([VNESHID]) REFERENCES [dbo].[TRB_REQUESTS] ([ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_TRB_REQUESTS_CHANGES]
    ON [dbo].[TRB_REQUESTS_CHANGES]([VNESHID] ASC);

