CREATE TABLE [dbo].[VR_REQUEST] (
    [ID]                INT              IDENTITY (1, 1) NOT NULL,
    [GID]               UNIQUEIDENTIFIER NOT NULL,
    [S_S]               INT              NOT NULL,
    [S_CR]              INT              NOT NULL,
    [S_CDT]             DATETIME         NOT NULL,
    [S_MR]              INT              NULL,
    [S_MDT]             DATETIME         NULL,
    [ARC]               INT              NULL,
    [ND]                NVARCHAR (10)    NULL,
    [DD]                DATE             NOT NULL,
    [VISITORTYPE]       INT              NOT NULL,
    [DEPID]             INT              NOT NULL,
    [CONTACT]           NTEXT            NOT NULL,
    [ADATE]             DATE             NOT NULL,
    [DDATE]             DATE             NOT NULL,
    [VT_FROM]           DATETIME         NOT NULL,
    [VT_TO]             DATETIME         NOT NULL,
    [VCLIP]             INT              NULL,
    [ACOMMENTS]         NTEXT            NULL,
    [LAST_ARC]          INT              NULL,
    [VISITOR_ADDRESSES] NTEXT            NOT NULL,
    [REMARK]            NTEXT            NULL,
    [COMPANY]           NVARCHAR (1000)  NULL,
    [ALL_COMMENTS]      NTEXT            NULL,
    [VISITORSUBTYPE]    INT              NULL,
    CONSTRAINT [PK__VR_REQUE__3214EC271C342674] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_VR_REQUEST_DEPID] FOREIGN KEY ([DEPID]) REFERENCES [dbo].[COM_DEPARTMENTS] ([ID])
);

