
CREATE view [dbo].[COM_EMPLOYEE_SKILL_PROLONGATION_DATES] WITH SCHEMABINDING
as

    select MAX(P.PROLONG_DATE) as PROLONG_DATE, P.EMPLOYEEID, P.SKILLID 
                from dbo.COM_EMPLOYEE_SKILL_PROLONGATION P
                group by P.SKILLID, P.EMPLOYEEID