







CREATE view [dbo].[COM_EMPLOYEE_SKILL_EXPIRATION_DATES]  
AS

select S.EMPLOYEEID, U.ID as USERID, 
case 
		when S.NOT_EXPIRING=1 AND L.EXPIRATION_TERM_TYPE_ID=1 then DATEADD(day, L.EXPIRATION_TERM, getdate())
		when S.NOT_EXPIRING=1 AND L.EXPIRATION_TERM_TYPE_ID=2 then DATEADD(week, L.EXPIRATION_TERM, getdate())
		when S.NOT_EXPIRING=1 AND L.EXPIRATION_TERM_TYPE_ID=3 then DATEADD(month, L.EXPIRATION_TERM, getdate())
		when S.NOT_EXPIRING=1 AND L.EXPIRATION_TERM_TYPE_ID=4 then DATEADD(year, L.EXPIRATION_TERM, getdate())
		when L.PRODUCTION_SUPPORT=1 AND L.EXPIRATION_TERM_TYPE_ID=1 then ISNULL(P.PROLONG_DATE,DATEADD(day, L.EXPIRATION_TERM, S.SKILL_DATE))
		when L.PRODUCTION_SUPPORT=1 AND L.EXPIRATION_TERM_TYPE_ID=2 then ISNULL(P.PROLONG_DATE,DATEADD(week, L.EXPIRATION_TERM, S.SKILL_DATE))
		when L.PRODUCTION_SUPPORT=1 AND L.EXPIRATION_TERM_TYPE_ID=3 then ISNULL(P.PROLONG_DATE,DATEADD(month, L.EXPIRATION_TERM, S.SKILL_DATE))
		when L.PRODUCTION_SUPPORT=1 AND L.EXPIRATION_TERM_TYPE_ID=4 then ISNULL(P.PROLONG_DATE,DATEADD(year, L.EXPIRATION_TERM, S.SKILL_DATE))
		when L.PRODUCTION_SUPPORT=0 AND L.EXPIRATION_TERM_TYPE_ID=1 then DATEADD(day, L.EXPIRATION_TERM, ISNULL(case when isnull(S.WITHOUT_TRAINING,0)=1 and S.SKILL_DATE is not null and S.SKILL_DATE>C.LAST_DATE then S.SKILL_DATE else C.LAST_DATE end,S.SKILL_DATE))
		when L.PRODUCTION_SUPPORT=0 AND L.EXPIRATION_TERM_TYPE_ID=2 then DATEADD(week, L.EXPIRATION_TERM, ISNULL(case when isnull(S.WITHOUT_TRAINING,0)=1 and S.SKILL_DATE is not null and S.SKILL_DATE>C.LAST_DATE then S.SKILL_DATE else C.LAST_DATE end,S.SKILL_DATE))
		when L.PRODUCTION_SUPPORT=0 AND L.EXPIRATION_TERM_TYPE_ID=3 then DATEADD(month, L.EXPIRATION_TERM, ISNULL(case when isnull(S.WITHOUT_TRAINING,0)=1 and S.SKILL_DATE is not null and S.SKILL_DATE>C.LAST_DATE then S.SKILL_DATE else C.LAST_DATE end,S.SKILL_DATE))
		when L.PRODUCTION_SUPPORT=0 AND L.EXPIRATION_TERM_TYPE_ID=4 then DATEADD(year, L.EXPIRATION_TERM, ISNULL(case when isnull(S.WITHOUT_TRAINING,0)=1 and S.SKILL_DATE is not null and S.SKILL_DATE>C.LAST_DATE then S.SKILL_DATE else C.LAST_DATE end,S.SKILL_DATE))
		else null END as EXPIRATION_DATE, S.SKILLID, E.NAME
from dbo.COM_EMPLOYEE_SKILL S
    left join (select ISNULL(S.SKILLID, S1.SKILLID) as SKILLID, MAX(T.DEND) as LAST_DATE, U.EMPLOYEEID
    from dbo.PR_OPERATION_TIME T   with (nolock)
        join dbo.PR_OPERATION O   with (nolock) on T.OPERID=O.ID
        left join dbo.COM_OPERATION_SKILL S on O.OPERTYPEID=S.OPERFORM_ID
        join dbo.PR_OPERATIONS OP  with (nolock) on O.OPERTYPEID=OP.ID
        left join dbo.COM_OPERATION_GROUP_SKILL S1 on OP.OPERGRID=S1.OPERGROUP_ID
        join DEF_USERS U on T.USERID=U.ID
    where  O.S_S=1000013 
    group by ISNULL(S.SKILLID, S1.SKILLID), U.EMPLOYEEID) C on S.EMPLOYEEID=C.EMPLOYEEID and S.SKILLID=C.SKILLID
    join dbo.DEF_USERS U on S.EMPLOYEEID=U.EMPLOYEEID
    join dbo.COM_EMPLOYEE E on S.EMPLOYEEID=E.ID
    join dbo.COM_SKILLS L on S.SKILLID=L.ID
    left join COM_EMPLOYEE_SKILL_PROLONGATION_DATES P on S.EMPLOYEEID=P.EMPLOYEEID and S.SKILLID=P.SKILLID