

CREATE VIEW [dbo].[FP_MICROLENS_RODS]
AS
SELECT     
	B.ID, 
	B.SN, 
	B.S_S, 
	B.MODELID, 
	M.CODE, 
	M.NAME, 
	B.COMPLETED_DT, 
	B.SCOMPLETED_DT, 
	B.REVID, 
	M.TYPEID,
	(SELECT TOP (1) 
				NN
		FROM dbo.PR_PRORDER AS FS
		WHERE(ID IN(SELECT	
						ORDERID
					FROM dbo.PR_PRORDER_SERVICE AS FST
					WHERE
						(DEVICEID = B.ID)
					)
				)
		ORDER BY ID DESC) AS LASTSERVORDER
	, R.NAME AS REVISION
FROM dbo.PR_DEVICE AS B WITH (nolock) 
LEFT JOIN dbo.PR_MODELS AS M WITH (nolock) ON M.ID = B.MODELID
LEFT JOIN PR_REVISION R ON B.REVID = R.ID
WHERE
	(M.TYPEID = 128) 
AND 
	(B.COMPLETED_DT IS NOT NULL)