CREATE view PR_MAP_OPER_VIEW as
select A.ID,A.S_CDT,A.S_CR,A.S_MDT,A.S_MR,A.MAPID,A.MAPSTAGEID,B.NAME as OPERNAME,B.REVN as OPERREVN,A.REMARK,A.INMAPORDER,B.CODE as OPERCODE
from PR_MAP_OPER A with (nolock)
left join PR_OPERATIONS B with (nolock) on B.ID = A.OPERID