create view PR_MODELTYPE_PARAMS_INLIST with schemabinding as
select A.ID, A.TYPEID from dbo.PR_MODELTYPE_PARAMS A 
where (isnull(A.USEINLIST,0) > 0 or isnull(A.USEINOPLIST,0) > 0)
  and A.PARAMKIND = 1
GO
CREATE NONCLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_INLIST_2]
    ON [dbo].[PR_MODELTYPE_PARAMS_INLIST]([TYPEID] ASC);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_PR_MODELTYPE_PARAMS_INLIST]
    ON [dbo].[PR_MODELTYPE_PARAMS_INLIST]([ID] ASC);

