create view PR_OPERATION_NOCMPL with schemabinding as
select ID,DEVICEID,ORDERID,OPERTYPEID,OPERGR,REVOPERID from dbo.PR_OPERATION 
where COMPLETED_DT is null 
  and S_S in (1000032) /*pending*/
  and USERINPROGRESS is null
  and isnull(HIDDEN,0) <> 1
GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_NOCMPL_OPERTYPEID]
    ON [dbo].[PR_OPERATION_NOCMPL]([OPERTYPEID] ASC)
    INCLUDE([ID], [DEVICEID], [ORDERID]);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_PR_OPERATION_NOCMPL]
    ON [dbo].[PR_OPERATION_NOCMPL]([ID] ASC, [DEVICEID] ASC, [ORDERID] ASC, [OPERTYPEID] ASC, [OPERGR] ASC, [REVOPERID] ASC);

