create view PR_OPERATION_BLOCKOTHERS with schemabinding as
select ID,ORDERID,DEVICEID from dbo.PR_OPERATION 
where COMPLETED_DT is null 
  and isnull(HIDDENOTHER,0) = 1
GO
CREATE UNIQUE CLUSTERED INDEX [IX_PR_OPERATION_BLOCKOTHERS]
    ON [dbo].[PR_OPERATION_BLOCKOTHERS]([ID] ASC, [ORDERID] ASC, [DEVICEID] ASC);

