create view PR_OPERATION_INPROGRESS with schemabinding as
select ID,S_S,USERINPROGRESS,ORDERID,DEVICEID,OPERGR from dbo.PR_OPERATION 
where COMPLETED_DT is null 
  and USERINPROGRESS is not null
GO
CREATE NONCLUSTERED INDEX [IX_PR_OPERATION_INPROGRESS_2]
    ON [dbo].[PR_OPERATION_INPROGRESS]([USERINPROGRESS] ASC, [S_S] ASC)
    INCLUDE([ID], [DEVICEID], [ORDERID], [OPERGR]);


GO
CREATE UNIQUE CLUSTERED INDEX [IX_PR_OPERATION_INPROGRESS]
    ON [dbo].[PR_OPERATION_INPROGRESS]([ID] ASC, [S_S] ASC, [USERINPROGRESS] ASC, [ORDERID] ASC, [DEVICEID] ASC, [OPERGR] ASC);

