create view [dbo].[PR_OPERATIONS_RAW_BYUSER] with schemabinding as
select A.ID as USERID, C.ID as OPERTYPEID, B.ID as LINKID 
from dbo.DEF_USERS A 
inner join dbo.PR_EMPL_TO_OPERGR B on B.EMPLOYEEID = A.EMPLOYEEID
inner join dbo.PR_OPERATIONS C on C.OPERGRID = B.GROUPID 
where C.ID is not null
GO
CREATE UNIQUE CLUSTERED INDEX [IX_PR_OPERATIONS_RAW_BYUSER]
    ON [dbo].[PR_OPERATIONS_RAW_BYUSER]([USERID] ASC, [OPERTYPEID] ASC, [LINKID] ASC);

