
CREATE  VIEW [dbo].[YMA_IN_DIODES3]
AS
SELECT B.ID, B.SN, B.MODELID, M.CODE, M.NAME, B.S_CDT
       , dbo.PR_DEVICE_INVALUE_STR2(B.ID, 2922) AS LOT
       ,(SELECT  TOP (1) CAST(PVALUE AS  nvarchar(50)) AS EXPR1
        FROM  dbo.PR_DEVICE_PRIVAT_VALUES AS V2 WITH (nolock)
        WHERE (DEVICEID = B.ID) AND (PARAMID = 1)
        ORDER  BY B.ID DESC) AS YMALOT
        , dbo.PR_DEVICE_INVALUE_FLOAT2(B.ID, 162) AS PRM_POUT
        , dbo.PR_DEVICE_INVALUE_FLOAT2(B.ID, 163) AS PRM_VOLTAGE
        , dbo.PR_DEVICE_INVALUE_FLOAT2(B.ID, 164) AS PRM_WAVELENGTH
        , dbo.PR_DEVICE_INVALUE_FLOAT2(B.ID, 165) AS PRM_NA
        , dbo.PR_DEVICE_INVALUE_FLOAT2(B.ID, 308) AS PRM_CURRENT
FROM dbo.PR_DEVICE AS B WITH (nolock) 
LEFT  OUTER  JOIN dbo.PR_MODELS AS M WITH (nolock) ON M.ID = B.MODELID
WHERE (B.MODELID IN (SELECT ID FROM dbo.PR_MODELS AS M WITH (nolock) WHERE (TYPEID = 9))) 
  AND B.S_S in (1000010,1000085,1000086,1000030)
  AND (NOT  EXISTS (SELECT ID
                     FROM dbo.PR_OPERATION_INSTALL AS F WITH (nolock)
                    WHERE (PARTID = B.ID) AND (ID NOT  IN (SELECT INSTALLROWID FROM dbo.PR_OPERATION_UNINSTALL AS G)))
       )