CREATE view YMA_NOT_INSTALLED_DIODES2 with schemabinding as
select B.ID,B.MODELID
FROM dbo.PR_DEVICE AS B 
inner JOIN dbo.PR_MODELS AS M ON M.ID = B.MODELID
WHERE M.TYPEID = 9
 AND (B.IMPPACKDEP = 196) 
 AND B.ID not  in (SELECT F.PARTID 
                FROM dbo.PR_OPERATION_INSTALL AS F 
               WHERE F.PARTID is not null and F.ID NOT IN (SELECT G.INSTALLROWID FROM dbo.PR_OPERATION_UNINSTALL AS G))