CREATE PROCEDURE [dbo].[COM_CR_OPER_RELATIVE_PERF]
(
	@START_DATE DATETIME
	,@END_DATE DATETIME
)
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED


	DECLARE @TMP_DEPTS TABLE(
				ID INT PRIMARY KEY
				,NAME NVARCHAR(100)
			)


	DECLARE	@TMP_OPERATIONS TABLE (
				ID INT PRIMARY KEY
				,OPERTYPEID INT
				,DEVICEID INT
				,USR_PER_OPER INT
				,PREP_RESULT INT
			)

	DECLARE	@TMP_OPER_CNT TABLE (
				USERID INT PRIMARY KEY
				,OPER_CNT INT
			)

	DECLARE @TMP_OPER_CNT_FULL TABLE(
				USERID INT PRIMARY KEY
				,OPER_CNT INT
			)

	SELECT @START_DATE = DATEADD(day, DATEDIFF(day, 0,@START_DATE), 0)
	SELECT @END_DATE = DATEADD(DAY, 1, CAST(@END_DATE AS DATE))

	INSERT INTO @TMP_DEPTS
	SELECT 
		T.ID
		,NAME
	FROM [dbo].[COM_ACCESS_DEPARTMENTS] (dbo.DEF_USERID(),3,GETDATE()) T
		JOIN COM_DEPARTMENTS DEPT ON T.ID = DEPT.ID

	--SELECT
	--	OP.ID
	--INTO #TMP_OP_TYPE
	--FROM PR_OPERATION OP 
	--	JOIN PR_OPERATIONS OP_TYPE ON OP.OPERTYPEID = OP_TYPE.ID
	--	JOIN [dbo].[PR_OPERATIONS_GR] OP_TYPE_GR ON OP_TYPE.[OPERGRID] = OP_TYPE_GR.[ID]
	--WHERE
	--	OP_TYPE_GR.DEPARTMENTID IN (SELECT ID FROM @TMP_DEPTS)

	INSERT INTO @TMP_OPERATIONS
	SELECT
		OP.ID
		,OP.OPERTYPEID
		,OP.DEVICEID
		,COUNT(DISTINCT OP_TIME.USERID) AS USR_PER_OPER
		,OP.PREP_RESULT
	FROM PR_OPERATION OP


	JOIN PR_OPERATION_TIME OP_TIME ON OP.ID = OP_TIME.OPERID
		JOIN DEF_USERS USR ON OP_TIME.USERID = USR.ID
			JOIN COM_EMPLOYEE EMP ON USR.EMPLOYEEID = EMP.ID


	JOIN PR_OPERATIONS OP_TYPE ON OP.[OPERTYPEID] = OP_TYPE.ID
		JOIN [dbo].[PR_OPERATIONS_GR] OP_TYPE_GR ON OP_TYPE.[OPERGRID] = OP_TYPE_GR.[ID]
	--JOIN #TMP_OP_TYPE OP_T ON OP.ID = OP_T.ID

	WHERE
		(OP.COMPLETED_DT >= @START_DATE AND OP.COMPLETED_DT < @END_DATE)
	AND
		EMP.DEPID IN (SELECT ID FROM @TMP_DEPTS)
	AND
		OP_TYPE_GR.DEPARTMENTID IN (SELECT ID FROM @TMP_DEPTS)
	GROUP BY
		OP.ID, OP.OPERTYPEID, OP.DEVICEID, OP.PREP_RESULT




	INSERT INTO @TMP_OPER_CNT
	SELECT
		OP_T.USERID
		,COUNT(DISTINCT OPERID) AS OPER_CNT
	FROM PR_OPERATION_TIME OP_T
	JOIN @TMP_OPERATIONS OP ON OP_T.OPERID = OP.ID
	WHERE
		OP.USR_PER_OPER = 1 
	GROUP BY 
		OP_T.USERID


	INSERT INTO @TMP_OPER_CNT_FULL
	SELECT
		OP_T.USERID
		,COUNT(DISTINCT OPERID) AS OPER_CNT
	FROM PR_OPERATION_TIME OP_T
	JOIN @TMP_OPERATIONS OP ON OP_T.OPERID = OP.ID
	GROUP BY 
		OP_T.USERID
----------------------------------------------------------------------
--FIND TOTAL IDLE TIME OF THE EMPLOYEE
/*	DECLARE @DATE DATETIME
	DECLARE	@TMP_CALENDAR TABLE 
			(
				DATE DATETIME
			)

	DECLARE @IDLE_TIME TABLE
			(
				EMP_ID INT
				,IDLE_TIME INT
			)


	SET @DATE = @START_DATE

	WHILE @DATE != @END_DATE
	BEGIN
		INSERT INTO @TMP_CALENDAR VALUES (@DATE);
		SET @DATE = DATEADD(DAY, 1, @DATE);
	END

	;WITH CTE_EMP_CAL AS (
		SELECT DISTINCT
			OP_TIME.EMPID
			,CAL.DATE
		FROM PR_OPERATION_TIME OP_TIME
		JOIN COM_EMPLOYEE EMP ON OP_TIME.EMPID = EMP.ID
		,  @TMP_CALENDAR CAL
		WHERE
			OP_TIME.OPERID IN (SELECT ID FROM @TMP_OPERATIONS)
		)
	,CTE_EMP_ELAPSED AS(
			SELECT
				EMPID
				,SUM(COALESCE(ELAPSEDCORR, ELAPSED, 0))	AS ELAPSED
			FROM PR_OPERATION_TIME 
			WHERE
				OPERID IN (SELECT ID FROM @TMP_OPERATIONS)
			GROUP BY
				EMPID
		)
	,CTE_SUM_IDLE AS (
				SELECT
					EMPID
					,SUM([dbo].[COM_ATTENDANCE_TIME](NULL, CTE_EMP_CAL.EMPID, DATE))  AS SUM_IDLE_TIME
				FROM CTE_EMP_CAL
				GROUP BY EMPID
	)

	INSERT INTO @IDLE_TIME	


	SELECT
		IT.EMPID
		,IT.SUM_IDLE_TIME - ELP.ELAPSED  AS SUM_IDLE_TIME
	FROM CTE_SUM_IDLE IT
	LEFT JOIN CTE_EMP_ELAPSED ELP ON IT.EMPID = ELP.EMPID
	
	*/
----------------------------------------------------------------------
	SELECT
		EMPID
		,NAME
		,DEPT_NAME
		,(SUM(ELAPSED_TIME) - SUM(MANHOUR)) / (SUM(MANHOUR)/100)  AS AVG_DISP
		,ONLY_OP.OPER_CNT AS EMPLOYEE_ONLY_OPERATIONS
		,FULL_OP.OPER_CNT AS EMPLOYEE_COMMON_OPERATIONS
		--,IT.IDLE_TIME
	FROM (

		SELECT
			EMP.ID AS EMPID
			,EMP.NAME
			,USR.ID AS USERID
			,OP_T.OPERID
			,OP_T.ELAPSED_TIME
			,COALESCE(REV_MH.MANHOUR2, OP_TYPE.MANHOUR, 0)+ COALESCE(ADD_MH.MANHOUR, 0) AS MANHOUR
			,DEP.NAME AS DEPT_NAME
		FROM COM_EMPLOYEE EMP
		JOIN @TMP_DEPTS DEP ON EMP.DEPID = DEP.ID

		JOIN DEF_USERS USR ON EMP.ID = USR.EMPLOYEEID
			JOIN (SELECT
						OP_T.USERID
						,OP_T.OPERID
						,CTE.DEVICEID
						,CTE.OPERTYPEID
						,SUM(
								CASE
									WHEN ISNULL(CTE.PREP_RESULT,0) > 1 THEN COALESCE(OP_T.ELAPSEDCORR, OP_T.ELAPSED, 0)/CTE.PREP_RESULT
									ELSE COALESCE(OP_T.ELAPSEDCORR, OP_T.ELAPSED, 0)
								END
							) AS ELAPSED_TIME
						FROM PR_OPERATION_TIME OP_T
						JOIN @TMP_OPERATIONS CTE ON OP_T.OPERID = CTE.ID AND CTE.USR_PER_OPER =1
						GROUP BY 
							OP_T.USERID,OP_T.OPERID, CTE.DEVICEID, CTE.OPERTYPEID
						) OP_T ON USR.ID = OP_T.USERID

				LEFT JOIN PR_DEVICE DEV ON OP_T.DEVICEID = DEV.ID
					LEFT JOIN PR_REV_OVER_MH REV_MH ON DEV.REVID = REV_MH.REVID AND REV_MH.OPERID = OP_T.OPERTYPEID

				LEFT JOIN PR_OPERATIONS OP_TYPE ON OP_T.OPERTYPEID = OP_TYPE.ID
		
				LEFT JOIN (SELECT 
								MH.OPERID
								,DEV_OPT.DEVICEID
								,SUM(MH.MANHOUR2) AS MANHOUR
							FROM PR_OPER_ADD_MH MH
							JOIN PR_DEVICE_OPT DEV_OPT ON DEV_OPT.OPTID = MH.OPTID
						
							GROUP BY MH.OPERID, DEV_OPT.DEVICEID
							) ADD_MH ON ADD_MH.OPERID = OP_T.OPERTYPEID AND ADD_MH.DEVICEID = OP_T.DEVICEID
		WHERE
			NOT EXISTS (SELECT ID FROM DEF_USERSTOGROUP WHERE USERID = USR.ID AND GROUPID = 17)


		) T
	LEFT JOIN  @TMP_OPER_CNT ONLY_OP ON T.USERID = ONLY_OP.USERID
	LEFT JOIN  @TMP_OPER_CNT_FULL FULL_OP ON T.USERID = FULL_OP.USERID

	--LEFT JOIN @IDLE_TIME IT ON T.EMPID = IT.EMP_ID
	WHERE 
		MANHOUR != 0

	GROUP BY 
		EMPID, NAME, DEPT_NAME, ONLY_OP.OPER_CNT,FULL_OP.OPER_CNT--, IDLE_TIME
	ORDER BY 
		AVG_DISP
END