CREATE procedure [dbo].[PR_DEVICE_UPD_STAT]
  @DeviceID int, @OrderID int
as 
 SET nocount on
 
 if @DeviceID is null or @OrderID is null
 begin
   SET nocount off
   return
 end

 declare @now datetime
 declare @v_ELAPSED int,@v_WAITED int,@v_DURATION int,@v_CYCLEFROMBEGIN int,@v_CYCLEFROM1OPER int,@v_ELAPSEDTROUBLE int
        ,@v_ELAPSEDWITHOUTTROUBLE int,@v_WASTROUBLE int,@v_UNINSTALLED int,@v_WAITBEFORE1OPERSTART int
        ,@v_ELAPSED_D decimal(12,2),@v_CYCLEFROM1OPER_D decimal(12,2)
 
 set @now = GETDATE()
 set @v_ELAPSED_D = dbo.PR_DEVICE_STAT_DEC(@DeviceID, @OrderID, 1, @now)
 set @v_ELAPSED = round(@v_ELAPSED_D,0) /*dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 1, @now)*/
 set @v_WAITED = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 2, @now)
 set @v_DURATION = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 4, @now)
 set @v_CYCLEFROMBEGIN = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 3, @now)
 set @v_CYCLEFROM1OPER_D = dbo.PR_DEVICE_STAT_DEC(@DeviceID, @OrderID, 6, @now)
 set @v_CYCLEFROM1OPER = round(@v_CYCLEFROM1OPER_D,0) /*dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 6, @now)*/
 set @v_ELAPSEDTROUBLE = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 9, @now)
 set @v_ELAPSEDWITHOUTTROUBLE = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 11, @now)
 set @v_WASTROUBLE = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 7, @now)
 set @v_UNINSTALLED = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 8, @now)
 set @v_WAITBEFORE1OPERSTART = dbo.PR_DEVICE_STAT(@DeviceID, @OrderID, 5, @now)

 update PR_DEVICE_STATVALUES set
 ELAPSED = @v_ELAPSED
 ,WAITED = @v_WAITED
 ,DURATION = @v_DURATION
 ,CYCLEFROMBEGIN = @v_CYCLEFROMBEGIN
 ,CYCLEFROM1OPER = @v_CYCLEFROM1OPER
 ,ELAPSEDTROUBLE = @v_ELAPSEDTROUBLE
 ,ELAPSEDWITHOUTTROUBLE = @v_ELAPSEDWITHOUTTROUBLE
 ,WASTROUBLE = @v_WASTROUBLE
 ,UNINSTALLED = @v_UNINSTALLED
 ,WAITBEFORE1OPERSTART = @v_WAITBEFORE1OPERSTART
 ,ELAPSED_D = @v_ELAPSED_D
 ,CYCLEFROM1OPER_D = @v_CYCLEFROM1OPER_D
 where DEVICEID = @DeviceID
   and ORDERID = @OrderID
   
 if @@ROWCOUNT = 0
   insert into PR_DEVICE_STATVALUES (DEVICEID,ORDERID,ELAPSED,WAITED,DURATION,CYCLEFROMBEGIN
              ,CYCLEFROM1OPER,ELAPSEDTROUBLE,ELAPSEDWITHOUTTROUBLE,WASTROUBLE,UNINSTALLED
              ,WAITBEFORE1OPERSTART,ELAPSED_D,CYCLEFROM1OPER_D)  
   values (@DeviceID,@OrderID,@v_ELAPSED,@v_WAITED,@v_DURATION,@v_CYCLEFROMBEGIN
             ,@v_CYCLEFROM1OPER,@v_ELAPSEDTROUBLE,@v_ELAPSEDWITHOUTTROUBLE,@v_WASTROUBLE,@v_UNINSTALLED
             ,@v_WAITBEFORE1OPERSTART,@v_ELAPSED_D,@v_CYCLEFROM1OPER_D)


SET nocount off