CREATE PROCEDURE [dbo].[PRR_EMPLOYEE_IDLE_AND_ELAPSED_OLD]
(
    @EMPLOYEE_ID INT
    ,@START_DATE DATETIME
    ,@END_DATE DATETIME
    ,@AVIABLE_OPERATIONS NVARCHAR(MAX)
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
/*
08.07.2014
Граматкин А.В.
Процедура получает время, затраченное на выполнение операций, для Пользователя за период.
Группировка по дням.
*/


DECLARE @DATE DATE;

-- SHARED OPERATIONS
DECLARE @TMP_OPERATIONS TABLE ( -- ONLY NOT SHARED OPERATIONS
                ID INT
                ,USR_PER_OPER INT
            )

DECLARE @TMP_AVIABLE_OPER TABLE (
                ID INT PRIMARY KEY
                ,NAME NVARCHAR(255)
                ,MANHOUR DECIMAL(10,4)
            )

DECLARE @TMP_CALENDAR TABLE(
                DATE DATETIME PRIMARY KEY
                ,WEEK INT
                ,WEEK_NAME NVARCHAR(255)
                ,MONTH INT
                ,MONTH_NAME  NVARCHAR(255)
                )

DECLARE @RES TABLE (
                    DATE DATE
                    ,OPER_ID INT
                    ,ELAPSED_TIME INT
                    ,FORECAST_TIME INT
                )

SELECT @START_DATE = DATEADD(day, DATEDIFF(day, 0,@START_DATE), 0)
SELECT @END_DATE = DATEADD(DAY, 1, CAST(@END_DATE AS DATE))

SET @DATE = @START_DATE

WHILE @DATE != @END_DATE
    BEGIN
        INSERT INTO @TMP_CALENDAR 
        SELECT
            @DATE
            ,DATEPART(WEEK, @DATE)
            ,'Week '+CAST(DATEPART(WEEK, @DATE) AS NVARCHAR(2))+' of '+CAST(YEAR(@DATE) AS NVARCHAR(4))
            ,DATEPART(MONTH, @DATE)
            ,DATENAME(MONTH, @DATE) + ' ' + CAST(YEAR(@DATE) AS NVARCHAR(4)) 
        SET @DATE = DATEADD(DAY,1,@DATE)
    END


;WITH CTE_AV_OP AS (    SELECT CONVERT(INT, Item) AS ID FROM
          ( SELECT Item = x.i.value('(./text())[1]', 'varchar(max)')
            FROM ( SELECT [XML] = CONVERT(XML, '<i>'
            + REPLACE(@AVIABLE_OPERATIONS, ',', '</i><i>') + '</i>').query('.')
              ) AS a CROSS APPLY [XML].nodes('i') AS x(i) ) AS y
          WHERE Item IS NOT NULL
)
INSERT INTO @TMP_AVIABLE_OPER
SELECT
    AV_OP.ID
    ,OP_T.NAME
    ,OP_T.MANHOUR
FROM CTE_AV_OP AV_OP
LEFT JOIN PR_OPERATIONS OP_T ON AV_OP.ID = OP_T.ID


INSERT INTO @TMP_OPERATIONS
    SELECT
        OP.ID
        ,COUNT(DISTINCT OP_TIME.USERID) AS USR_PER_OPER
    FROM PR_OPERATION OP
    JOIN PR_OPERATION_TIME OP_TIME ON OP.ID = OP_TIME.OPERID
    JOIN @TMP_AVIABLE_OPER OP_TYPE ON OP.OPERTYPEID = OP_TYPE.ID
    WHERE
        OP.COMPLETED_DT >= @START_DATE AND OP.COMPLETED_DT < @END_DATE
    GROUP BY
        OP.ID
    HAVING COUNT(DISTINCT OP_TIME.USERID) = 1
-------------------------------------
INSERT INTO @RES
SELECT
    FINISH_DATE
    ,OPER_ID
    ,SUM(ISNULL(TOTAL_OPER_TIME,0)) AS ELAPSED_TIME
    ,MANHOUR AS FORECAST_TIME
FROM (
SELECT
    CAST(OP.COMPLETED_DT AS DATE)  AS FINISH_DATE
    ,CASE -- IF OPERATION WAS EXECUTED AT MORE THEN 1 ITEM DIVIDE TOTAL ELAPSED TIME TO ITEMS COUNT
            WHEN ISNULL(OP.PREP_RESULT,0) > 1 THEN COALESCE(OP_T.ELAPSEDCORR, OP_T.ELAPSED, 0)/OP.PREP_RESULT
            ELSE COALESCE(OP_T.ELAPSEDCORR, OP_T.ELAPSED, 0)
        END AS TOTAL_OPER_TIME
    ,COALESCE(REV_MH.MANHOUR2, OP_TYPE.MANHOUR, 0)+ COALESCE(ADD_MH.MANHOUR, 0)  AS MANHOUR
    ,OP.ID AS OPER_ID
FROM COM_EMPLOYEE EMP
JOIN DEF_USERS USR ON USR.EMPLOYEEID = EMP.ID
    JOIN PR_OPERATION_TIME OP_T ON OP_T.USERID = USR.ID
        JOIN @TMP_OPERATIONS SINGLE_OP ON OP_T.OPERID = SINGLE_OP.ID

        JOIN PR_OPERATION OP ON OP_T.OPERID = OP.ID  AND OP.COMPLETED_DT >= @START_DATE AND OP.COMPLETED_DT < @END_DATE
            JOIN @TMP_AVIABLE_OPER OP_TYPE ON OP.OPERTYPEID = OP_TYPE.ID
            
            LEFT JOIN PR_DEVICE DEV ON OP.DEVICEID = DEV.ID
                    LEFT JOIN PR_REV_OVER_MH REV_MH ON DEV.REVID = REV_MH.REVID AND REV_MH.OPERID = OP.OPERTYPEID
                    LEFT JOIN PR_SUPPLY SUPP ON DEV.SORDERID = SUPP.ID
                    LEFT JOIN PR_MODELS MDL ON DEV.MODELID = MDL.ID
                    LEFT JOIN PR_REVISION REV ON DEV.REVID = REV.ID

            LEFT JOIN (SELECT 
                            MH.OPERID
                            ,DEV_OPT.DEVICEID
                            ,SUM(MH.MANHOUR2) AS MANHOUR
                        FROM PR_OPER_ADD_MH MH
                        JOIN PR_DEVICE_OPT DEV_OPT ON DEV_OPT.OPTID = MH.OPTID
                        
                        GROUP BY MH.OPERID, DEV_OPT.DEVICEID
                        ) ADD_MH ON ADD_MH.OPERID = OP.OPERTYPEID AND ADD_MH.DEVICEID = OP.DEVICEID

            LEFT JOIN PR_PRORDER ORD ON OP.ORDERID = ORD.ID
            

WHERE
    EMP.ID = @EMPLOYEE_ID
) T
WHERE
    ISNULL(T.MANHOUR, 0) != 0
GROUP BY 
    FINISH_DATE, OPER_ID, MANHOUR
ORDER BY FINISH_DATE



IF DATEDIFF(MONTH, @START_DATE,DATEADD(DAY, -1, CAST(@END_DATE AS DATE))) = 0
        SELECT
            CAST(CAL.DATE AS INT) AS PERIOD
            ,CONVERT(NVARCHAR(20), CAL.DATE, 105) AS PERIOD_NAME
            ,SUM(ELAPSED_TIME) AS ELAPSED_TIME
            ,SUM(FORECAST_TIME) AS FORECAST_TIME
        FROM @TMP_CALENDAR CAL
        LEFT JOIN @RES R ON CAL.DATE = R.DATE
        GROUP BY CAST(CAL.DATE AS INT),CONVERT(NVARCHAR(20), CAL.DATE, 105)
         
        ORDER BY PERIOD
    ELSE
        IF DATEDIFF(MONTH, @START_DATE,DATEADD(DAY, -1, CAST(@END_DATE AS DATE))) < 6 
        SELECT
            WEEK AS PERIOD
            ,WEEK_NAME AS PERIOD_NAME
            ,SUM(ELAPSED_TIME) AS ELAPSED_TIME
            ,SUM(FORECAST_TIME) AS FORECAST_TIME
        FROM @TMP_CALENDAR CAL
        LEFT JOIN @RES R ON CAL.DATE = R.DATE
        GROUP BY WEEK, WEEK_NAME
        ORDER BY PERIOD
        ELSE
        SELECT
            MONTH AS PERIOD
            ,MONTH_NAME AS PERIOD_NAME
            ,SUM(ELAPSED_TIME) AS ELAPSED_TIME
            ,SUM(FORECAST_TIME) AS FORECAST_TIME
        FROM @TMP_CALENDAR CAL
        LEFT JOIN @RES R ON CAL.DATE = R.DATE
        GROUP BY MONTH, MONTH_NAME
        ORDER BY PERIOD
END


-- exec report.EMPLOYEE_IDLE_AND_ELAPSED 384, '2014-01-01', '2014-07-15'
-- SELECT DATEDIFF(MONTH, '2014-06-01', '2014-07-15')