CREATE procedure [dbo].[PRR_OVERHOURS_CALC](@RequestID int, @UserID int)
as 
BEGIN
  set nocount on

  delete from PRR_OVERHOURS_DATA where VNESHID = @RequestID
  
  declare @START_DATE datetime
  declare @END_DATE datetime
  declare @OvertimeLength int
  declare @TempEmployee int
  declare @SubstractVacations int = 0
  declare @ExcludeSunday int 
  declare @IncludeAll int
  declare @rootDepID int
  
  select @START_DATE = dbo.COM_ENCODE_DATE(A.YY,A.MM,1)
	,@OvertimeLength = A.LESSMINUTES
	,@TempEmployee = isnull(A.INCLTEMP,0)
	,@ExcludeSunday = isnull(A.EXCSUNDAY,0)
	,@IncludeAll = isnull(A.INCLWITHOUT,0)
	,@rootDepID = A.DEPID
  from PRR_OVERHOURS A with(nolock)
  where A.ID = @RequestID


DECLARE @DT DATE

SET @END_DATE = dateadd(month,1,@START_DATE)


DECLARE @DEP TABLE (ID INT)
DECLARE @CALENDAR TABLE (DT DATE, [MONTH] INT, [YEAR] INT, [DAY] INT)
DECLARE @RES TABLE (EMPLOYEE_ID INT, EMPLOYEE NVARCHAR(255), EMPLOYEE_PERSONALNO nvarchar(50), DEPARTMENT_ID INT, DBEG DATETIME, DEND DATETIME,ADDID int,WORKDAY date)

DECLARE @DAYS TABLE (DAY INT)
DECLARE @DAY INT = 1

WHILE @DAY <= 31
BEGIN
	INSERT INTO @DAYS VALUES (@DAY)
	SET @DAY += 1
END

SET @DT = @START_DATE
WHILE @DT < @END_DATE
BEGIN
	INSERT INTO @CALENDAR VALUES(@DT
		,MONTH(@DT) 
		,YEAR(@DT)
		,DAY(@DT)
		)
	SET @DT = DATEADD(DAY, 1, @DT)
END

insert into @DEP (ID)
select ID from dbo.COM_GETCHILD_DEPARTMENTS2(@rootDepID,1)


/*KB4052 4. Сотрудники, которые меняли отдел в течении месяца, должны появиться в отчёте отдела, к которому они были приписаны в последний день месяца.*/
declare @LastMonthDate datetime = dateadd(day,-1,@END_DATE)
declare @empl table (ID int,DEPID int)
insert into @empl (ID,DEPID)
select A.EMPLID 
      ,A.DEPID
from dbo.COM_EMPLOYEE_IN_DEP_TABLE2(@rootDepID,@LastMonthDate,@LastMonthDate,1) A


INSERT INTO @RES(EMPLOYEE_ID,EMPLOYEE,EMPLOYEE_PERSONALNO,DEPARTMENT_ID,DBEG,DEND,ADDID)
SELECT
	EMP.ID AS EMPLOYEE_ID
	,EMP.NAME AS EMPLOYEE
	,EMP.PERSONALNO AS EMPLOYEE_PERSONALNO
	,(select top 1 DEPID from @empl where ID = EMP.ID) AS DEPARTMENT_ID
	,CASE 
		WHEN DBEG < @START_DATE THEN @START_DATE
			ELSE DBEG
	END AS DBEG
	,CASE
		WHEN DEND > @END_DATE THEN @END_DATE
			ELSE DEND
	END AS DEND
    ,AT.ID
FROM COM_ADDED_WORKTIME AT with(nolock)
left JOIN COM_EMPLOYEE EMP with(nolock) ON AT.EMPLID = EMP.ID
WHERE ISNULL(EMP.ISTEMP, 0) IN (0, @TempEmployee)
  AND EMP.ID IN (SELECT ID FROM @empl)
  AND (		(AT.DBEG >= @START_DATE AND AT.DBEG < @END_DATE)
		OR	(AT.DEND >= @START_DATE AND AT.DBEG < @END_DATE)
		OR	(AT.DBEG < @START_DATE AND AT.DEND > @END_DATE)
	   )
  AND isnull(AT.OVERTIME_TYPE,1)=1

update @RES set WORKDAY = dbo.COM_ADDEDTIME_WORKDAY(ADDID,EMPLOYEE_ID,DBEG)

DECLARE @T TABLE ([DAY] INT
		,[MONTH] INT
		,[YEAR] INT
		,DEPARTMENT_ID INT
		,EMPLOYEE_ID INT
		,EMPLOYEE NVARCHAR(255)
		,EMPLOYEE_PERSONALNO nvarchar(50)
		,DURATION decimal(16,2)
		)
		
DECLARE @TWithoutSunday TABLE ([DAY] INT
		,[MONTH] INT
		,[YEAR] INT
		,DEPARTMENT_ID INT
		,EMPLOYEE_ID INT
		,EMPLOYEE NVARCHAR(255)
		,EMPLOYEE_PERSONALNO nvarchar(50)
		,DURATION decimal(16,2)
		)

INSERT INTO @T([DAY]
		,[MONTH]
		,[YEAR]
		,DEPARTMENT_ID
		,EMPLOYEE_ID
		,EMPLOYEE
		,EMPLOYEE_PERSONALNO
		,DURATION)
	SELECT
		C.[DAY]
		,C.[MONTH]
		,C.[YEAR]
		,R.DEPARTMENT_ID
		,R.EMPLOYEE_ID
		,R.EMPLOYEE
		,R.EMPLOYEE_PERSONALNO
		/*,DATEDIFF(MINUTE, R.DBEG, R.DEND) AS DURATION*/  /*KB2631*/
		,dbo.COM_SUBSTRACT_ADDEDWT_BAL(R.ADDID,R.DBEG, R.DEND,R.EMPLOYEE_ID) as DURATION
	FROM 
	(	SELECT
			D.[DAY]
			,T.[MONTH]
			,T.[YEAR]
		FROM @DAYS D 
		CROSS JOIN (SELECT DISTINCT C.[MONTH], C.[YEAR]  FROM @CALENDAR C) T ) C
	LEFT JOIN @RES R ON DAY(R.WORKDAY) = C.[DAY] AND MONTH(R.WORKDAY) = C.[MONTH] AND YEAR(R.WORKDAY) = C.[YEAR]
	WHERE
		DATEDIFF(MINUTE, R.DBEG, R.DEND) >= @OvertimeLength
		
INSERT INTO @TWithoutSunday([DAY]
		,[MONTH]
		,[YEAR]
		,DEPARTMENT_ID
		,EMPLOYEE_ID
		,EMPLOYEE
		,EMPLOYEE_PERSONALNO
		,DURATION)
	SELECT
		C.[DAY]
		,C.[MONTH]
		,C.[YEAR]
		,R.DEPARTMENT_ID
		,R.EMPLOYEE_ID
		,R.EMPLOYEE
		,R.EMPLOYEE_PERSONALNO
		/*,DATEDIFF(MINUTE, R.DBEG, R.DEND) AS DURATION*/ /*KB2631*/
		,dbo.COM_SUBSTRACT_ADDEDWT_BAL(R.ADDID,R.DBEG, R.DEND,R.EMPLOYEE_ID) as DURATION
	FROM 
	(	SELECT
			D.[DAY]
			,T.[MONTH]
			,T.[YEAR]
		FROM @DAYS D 
		CROSS JOIN (SELECT DISTINCT C.[MONTH], C.[YEAR]  FROM @CALENDAR C) T ) C
	LEFT JOIN @RES R ON DAY(R.WORKDAY) = C.[DAY] AND MONTH(R.WORKDAY) = C.[MONTH] AND YEAR(R.WORKDAY) = C.[YEAR]
	WHERE DATEDIFF(MINUTE, R.DBEG, R.DEND) >= @OvertimeLength 
	  and dbo.COM_DAY_OF_WEEK(R.DBEG)<>7

IF @SubstractVacations = 1
BEGIN
	INSERT INTO @T ([DAY]
		,[MONTH]
		,[YEAR]
		,DEPARTMENT_ID
		,EMPLOYEE_ID
		,EMPLOYEE
		,EMPLOYEE_PERSONALNO
		,DURATION)
	SELECT 
		DAY(DBEG) AS [DAY]
		,MONTH(DBEG) AS [MONTH]
		,YEAR(DBEG) AS [YEAR]
		,(select top 1 DEPID from @empl where ID = V.EMPLID) as DEPID
		,V.EMPLID
		,EMP.NAME
		,EMP.PERSONALNO
		--,-1 * SUM(V.SHORTDURATION) AS DURATION
		,-1*sum(VM.WORKMINUTES)
	FROM COM_VACATION V with(nolock)
	left JOIN COM_EMPLOYEE EMP with(nolock) ON V.EMPLID = EMP.ID
    outer apply (select sum(isnull(WORKMINUTES,0)) as WORKMINUTES from dbo.COM_VACATION_MINUTES_BYDAYS2(V.ID)) VM
	WHERE V.DBEG >= @START_DATE AND V.DBEG < @END_DATE
	  AND V.S_S = 1000141/**APPROVED*/
	  AND EMP.ID IN (SELECT EMPLOYEE_ID FROM @RES)
	  AND V.SHORTDURATION IS NOT NULL
	  and V.VACATIONTYPE = 30 /*KB917*/	
	  AND ISNULL(EMP.ISTEMP, 0) IN (0, @TempEmployee)
	GROUP BY DAY(DBEG),MONTH(DBEG),YEAR(DBEG),EMP.DEPID,V.EMPLID,EMP.NAME,EMP.PERSONALNO

	INSERT INTO @TWithoutSunday ([DAY]
		,[MONTH]
		,[YEAR]
		,DEPARTMENT_ID
		,EMPLOYEE_ID
		,EMPLOYEE
		,EMPLOYEE_PERSONALNO
		,DURATION)
	SELECT 
		DAY(DBEG) AS [DAY]
		,MONTH(DBEG) AS [MONTH]
		,YEAR(DBEG) AS [YEAR]
		,(select top 1 DEPID from @empl where ID = V.EMPLID) as DEPID
		,V.EMPLID
		,EMP.NAME
		,EMP.PERSONALNO
		--,-1 * SUM(V.SHORTDURATION) AS DURATION
		,-1*sum(VM.WORKMINUTES)
	FROM COM_VACATION V with(nolock)
	left JOIN COM_EMPLOYEE EMP with(nolock) ON V.EMPLID = EMP.ID
    outer apply (select sum(isnull(WORKMINUTES,0)) as WORKMINUTES from dbo.COM_VACATION_MINUTES_BYDAYS2(V.ID)) VM
	WHERE V.DBEG >= @START_DATE AND V.DBEG < @END_DATE
	  AND V.S_S = 1000141/**APPROVED*/
	  AND EMP.ID IN (SELECT EMPLOYEE_ID FROM @RES)
	  /*and EMP.DEPID IN (SELECT ID FROM @DEP)*/
	  AND V.SHORTDURATION IS NOT NULL
	  and V.VACATIONTYPE = 30 /*KB917*/	
	  AND ISNULL(EMP.ISTEMP, 0) IN (0, @TempEmployee)
	GROUP BY DAY(DBEG),MONTH(DBEG),YEAR(DBEG),EMP.DEPID,V.EMPLID,EMP.NAME,EMP.PERSONALNO

END

if @IncludeAll = 1 
begin
	insert into @T(DAY,MONTH,YEAR,DEPARTMENT_ID,EMPLOYEE_ID,EMPLOYEE,EMPLOYEE_PERSONALNO,DURATION)
	select 1
	 	,B.MONTH
		,B.YEAR 
		,(select top 1 DEPID from @empl where ID = EMP.ID) AS DEPARTMENT_ID
		,EMP.ID AS EMPLOYEE_ID
		,EMP.NAME AS EMPLOYEE
		,EMP.PERSONALNO AS EMPLOYEE_PERSONALNO
		,0
	from COM_EMPLOYEE EMP with(nolock)
	cross join (select distinct MONTH,YEAR from @CALENDAR) B
	where ISNULL(EMP.ISTEMP, 0) IN (0, @TempEmployee)
	  and EMP.ID in (select ID from @empl)
	  and EMP.S_S = 1
	  and not exists (select K.DAY from @T K where K.MONTH = B.MONTH and K.YEAR = B.YEAR and K.EMPLOYEE_ID = EMP.ID)
end  


insert into PRR_OVERHOURS_DATA ([GID],[S_CR],[S_CDT],[VNESHID]
           ,[EMPLID]
           ,[DEPID]
           ,[GROUPINGVALUE]
           ,[D1],[D2],[D3],[D4],[D5],[D6],[D7],[D8],[D9],[D10]
           ,[D11],[D12],[D13],[D14],[D15],[D16],[D17],[D18],[D19],[D20]
           ,[D21],[D22],[D23],[D24],[D25],[D26],[D27],[D28],[D29],[D30],[D31]
           ,[TOTAL_PLUS]
           ,[TOTAL_MINUS]
           ,[TOTAL])
SELECT newid(),@UserID,getdate(),@RequestID
		,P.EMPLOYEE_ID
		,P.DEPARTMENT_ID
		,str(P.DEPARTMENT_ID)+str(P.[YEAR])+str(P.[MONTH]) as GROUPINGVALUE
		,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20],[21],[22],[23],[24],[25],[26],[27],[28],[29],[30],[31]
		,CASE WHEN @ExcludeSunday=1 then TOTAL_PLUS_WS.DURATION ELSE TOTAL_PLUS.DURATION END AS TOTAL_PLUS
		,CASE WHEN @ExcludeSunday=1 then TOTAL_MINUS_WS.DURATION ELSE TOTAL_MINUS.DURATION END AS TOTAL_MINUS
		,CASE WHEN @ExcludeSunday=1 then TOTAL_WS.DURATION ELSE TOTAL.DURATION END AS TOTAL
FROM 
(SELECT 
	[DAY]
	,[MONTH]
	,[YEAR]
	,DEPARTMENT_ID
	,EMPLOYEE_ID
	,EMPLOYEE
	,EMPLOYEE_PERSONALNO
	,case when DURATION > 0 then DURATION / 60.00 else 0 end AS DURATION
FROM @T
WHERE (DURATION <> 0 or @IncludeAll = 1)
)
 T
PIVOT (SUM(DURATION) FOR [DAY] IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20],[21],[22],[23],[24],[25],[26],[27],[28],[29],[30],[31]) ) AS P

LEFT JOIN (SELECT EMPLOYEE_ID
                ,[YEAR]
				,[MONTH]
				, SUM( CAST(DURATION AS DECIMAL(16,2)) / 60.00) AS DURATION 
				FROM @T 
				WHERE DURATION > 0 
				GROUP BY EMPLOYEE_ID,[YEAR],[MONTH]) TOTAL_PLUS ON P.EMPLOYEE_ID = TOTAL_PLUS.EMPLOYEE_ID and P.[YEAR] = TOTAL_PLUS.[YEAR] and P.[MONTH] = TOTAL_PLUS.[MONTH]
LEFT JOIN (SELECT EMPLOYEE_ID
                 ,[YEAR]
				 ,[MONTH]
				 , SUM( -1* CAST(DURATION AS DECIMAL(16,2)) / 60.00) AS DURATION
				 FROM @T 
				 WHERE DURATION < 0 
				 GROUP BY EMPLOYEE_ID,[YEAR],[MONTH]) TOTAL_MINUS ON P.EMPLOYEE_ID = TOTAL_MINUS.EMPLOYEE_ID and P.[YEAR] = TOTAL_MINUS.[YEAR] and P.[MONTH] = TOTAL_MINUS.[MONTH]
LEFT JOIN (SELECT EMPLOYEE_ID
                 ,[YEAR]
				 ,[MONTH]
				 , SUM( CAST(DURATION AS DECIMAL(16,2)) / 60.00) AS DURATION 
				 FROM @T
				 GROUP BY EMPLOYEE_ID,[YEAR],[MONTH]) TOTAL ON P.EMPLOYEE_ID = TOTAL.EMPLOYEE_ID and P.[YEAR] = TOTAL.[YEAR] and P.[MONTH] = TOTAL.[MONTH]

LEFT JOIN (SELECT EMPLOYEE_ID
                ,[YEAR]
				,[MONTH]
				, SUM( CAST(DURATION AS DECIMAL(16,2)) / 60.00) AS DURATION 
				FROM @TWithoutSunday 
				WHERE DURATION > 0 
				GROUP BY EMPLOYEE_ID,[YEAR],[MONTH]) TOTAL_PLUS_WS ON P.EMPLOYEE_ID = TOTAL_PLUS_WS.EMPLOYEE_ID and P.[YEAR] = TOTAL_PLUS_WS.[YEAR] and P.[MONTH] = TOTAL_PLUS_WS.[MONTH]
LEFT JOIN (SELECT EMPLOYEE_ID
                 ,[YEAR]
				 ,[MONTH]
				 , SUM( -1* CAST(DURATION AS DECIMAL(16,2)) / 60.00) AS DURATION
				 FROM @TWithoutSunday 
				 WHERE DURATION < 0 
				 GROUP BY EMPLOYEE_ID,[YEAR],[MONTH]) TOTAL_MINUS_WS ON P.EMPLOYEE_ID = TOTAL_MINUS_WS.EMPLOYEE_ID and P.[YEAR] = TOTAL_MINUS_WS.[YEAR] and P.[MONTH] = TOTAL_MINUS_WS.[MONTH]
LEFT JOIN (SELECT EMPLOYEE_ID
                 ,[YEAR]
				 ,[MONTH]
				 , SUM( CAST(DURATION AS DECIMAL(16,2)) / 60.00) AS DURATION 
				 FROM @TWithoutSunday
				 GROUP BY EMPLOYEE_ID,[YEAR],[MONTH]) TOTAL_WS ON P.EMPLOYEE_ID = TOTAL_WS.EMPLOYEE_ID and P.[YEAR] = TOTAL_WS.[YEAR] and P.[MONTH] = TOTAL_WS.[MONTH]
WHERE 
	DEPARTMENT_ID IS NOT NULL


set nocount off
    
END