CREATE procedure [dbo].[SL_APPROVE_OPTION] @aID int, @aUserID int , @aMode int
as 
set nocount on

update SL_OPTIONS
   set S_CR = B.S_CR
      ,S_CDT = B.S_CDT
      ,S_MR  = B.S_MR
      ,S_MDT = B.S_MDT
      ,S_S = B.S_S
      ,CODE = B.CODE
      ,DEPARTMENTID = B.DEPARTMENTID
      ,NAME = B.NAME
      ,GROUPID = B.GROUPID
      ,GROUPNAME = B.GROUPNAME
      ,TAGS = B.TAGS
      ,PRTYPE = B.PRTYPE
      ,CMP_OUT = B.CMP_OUT
      ,CMP_REQ = B.CMP_REQ
      ,SPEC = B.SPEC
      ,CUSTOM4GROUP  = B.CUSTOM4GROUP
      ,CUSTOM4ID  = B.CUSTOM4ID
      ,OPICT = B.OPICT
      ,APPROVEDBY = @aUserID
      ,APPROVEDDT = getdate()
      ,CMP_BLOCK = B.CMP_BLOCK
      ,TYPEID = B.TYPEID
from SL_OPTIONS A
left join SL_OPTIONS_V B on B.ID = A.ID
where A.ID = @aID

if @@rowcount = 0
begin
	insert into SL_OPTIONS (ID,GID,S_CR,S_CDT,S_MR,S_MDT,S_S,CODE,NAME,GROUPID,GROUPNAME,TYPEID,TAGS,PRTYPE,CMP_OUT,CMP_REQ,SPEC,OPICT,CUSTOM4GROUP,MTNAME,DEPARTMENTID,CUSTOM4ID,APPROVEDBY,APPROVEDDT,CMP_BLOCK)
	select ID,GID,S_CR,S_CDT,S_MR,S_MDT,S_S,CODE,NAME,GROUPID,GROUPNAME,TYPEID,TAGS,PRTYPE,CMP_OUT,CMP_REQ,SPEC,OPICT,CUSTOM4GROUP,MTNAME,DEPARTMENTID,CUSTOM4ID,@aUserID,getdate(),CMP_BLOCK
	from SL_OPTIONS_V where ID = @aID
end


delete from SL_OPTION_FILES where OPTID = @aID

insert into SL_OPTION_FILES (ID,GID,S_CR,S_CDT,S_MR,S_MDT,OPTID,FILENAME,FILESIZE,FILEDATE,FILEBLOB,FILEDESC,FILEGROUP,FILESOURCE,FILESOURCEID)
select ID,GID,S_CR,S_CDT,S_MR,S_MDT,OPTID,FILENAME,FILESIZE,FILEDATE,FILEBLOB,FILEDESC,FILEGROUP,FILESOURCE,FILESOURCEID 
from SL_OPTION_FILES_V where OPTID = @aID


set nocount off