CREATE PROCEDURE [dbo].[SM_COPY_SERVICECALLS] @oldCaseID int, @UserID int, @newCaseID int ,@aMode int 
AS
BEGIN
set nocount on

/* 4 KB871*/

declare @oldCaseN nvarchar(50)
declare @newCaseN nvarchar(50)
 
select @newCaseN = ND from SM_SERVICECASE where ID = @newCaseID

select @oldCaseN = B.ND
from  SM_SERVICECASE B with (nolock)
where B.ID = @oldCaseID

declare @aCallID int
declare @copyCallID int

DECLARE cur_SM_COPY_SERVICECALL CURSOR FAST_FORWARD READ_ONLY FOR
SELECT ID from SM_SERVICECALL where CASEID=@oldCaseID
                    
OPEN cur_SM_COPY_SERVICECALL

FETCH NEXT FROM cur_SM_COPY_SERVICECALL INTO @aCallID

WHILE @@FETCH_STATUS=0
BEGIN
    
    insert into SM_SERVICECALL(GID,S_CR,S_CDT,DD,CUSTID,CONTACTID,SCTYPE,SCDIRECTION,SUBJ,SCBODY,MODELID,SN,CASEID,MSGID,UNREAD,REPLY2ID,SENT_DT,NEWSERVCASE,SENT_UID,REPLY_DT,REPLY_UID,SCBODYRTF,SDEPID,MSGPLAINTEXT,READBY,FORWARD2ID,EXCLUDEFROMSR,HIGHLIGHT)
    select newid(),@UserID,getdate(),DD,CUSTID,CONTACTID,SCTYPE,SCDIRECTION,replace(S.SUBJ,'##'+@oldCaseN+'##','##'+@newCaseN+'##'),SCBODY,MODELID,SN,@newCaseID,null,UNREAD,REPLY2ID,SENT_DT,NEWSERVCASE,SENT_UID,REPLY_DT,REPLY_UID,SCBODYRTF,SDEPID,MSGPLAINTEXT,READBY,FORWARD2ID,EXCLUDEFROMSR,HIGHLIGHT
    from SM_SERVICECALL S where S.ID = @aCallID

    set @copyCallID = SCOPE_IDENTITY()

    insert into SM_SERVICECALL_FILES(GID,S_CR,S_CDT,VNESHID,FILENAME,FILESIZE,FILEDESC,FILEDATE,FILEBLOB,FILEPREVIEW)
    select newid(),@UserID,getdate(),@copyCallID,FILENAME,FILESIZE,FILEDESC,FILEDATE,FILEBLOB,FILEPREVIEW
    from SM_SERVICECALL_FILES where VNESHID = @aCallID

    insert into SM_SERVICE_CALL_T(GID,S_CR,S_CDT,VNESHID,CNTID,USEASCOPY)
    select newid(),@UserID,getdate(),@copyCallID,CNTID,USEASCOPY
    from SM_SERVICE_CALL_T where VNESHID = @aCallID

    insert into SM_SERVICE_CALL_T_CC(GID,S_CR,S_CDT,VNESHID,CNTID)
    select newid(),@UserID,getdate(),@copyCallID,CNTID
    from SM_SERVICE_CALL_T_CC where VNESHID = @aCallID

    insert into SM_SERVICE_CALL_TINT(GID,S_CR,S_CDT,VNESHID,EMAIL,NAME,UID)
    select newid(),@UserID,getdate(),@copyCallID,EMAIL,NAME,UID
    from SM_SERVICE_CALL_TINT where VNESHID = @aCallID

    insert into SM_SERVICE_CALL_TINT_CC(GID,S_CR,S_CDT,VNESHID,EMAIL,NAME,UID)
    select newid(),@UserID,getdate(),@copyCallID,EMAIL,NAME,UID
    from SM_SERVICE_CALL_TINT_CC where VNESHID = @aCallID   
    
    FETCH NEXT FROM cur_SM_COPY_SERVICECALL INTO @aCallID
END

CLOSE cur_SM_COPY_SERVICECALL
DEALLOCATE cur_SM_COPY_SERVICECALL

set nocount off
END